### ISSUE TITLE
Allow all HTTP 2xx codes in out_http to result in success

### ISSUE THREAD

**Issue by salekseev** [fluent/fluent-bit#109]
At https://github.com/fluent/fluent-bit/blob/master/plugins/out_http/http.c#L394 you only check for http return code 200 but all 2xx codes mean success per https://httpstatuses.com, in particular my application returns 204.

**Comment by edsiper** [comment]
oh, first time I see 204 in use :) . So it should support the following:

- 200: OK
- 201: Created
- 202: Accepted
- 203: no authorative resp
- 204: No Content
- 205: Reset content

the following statuses should not apply for our use case: 206 (partial), 207 (multi status), 208 (already reported).

Just fixed by https://github.com/fluent/fluent-bit/commit/529522f59deffe3106f5a19be485ae3ef7cfb812

**Comment by salekseev** [comment]
Nice. Thanks a ton.

**Comment by salekseev** [comment]
Seems to work just fine btw:
```
$ /opt/fluent-bit/bin/fluent-bit -i cpu -o http://devfluentrelay101.athenahealth.com:8080/test -v
Fluent-Bit v0.8.6
Copyright (C) Treasure Data

[2016/09/22 19:19:00] [ info] starting engine
[2016/09/22 19:19:00] [error] [TLS] Invalid CA file: /etc/ssl/certs/ca-certificates.crt
[2016/09/22 19:19:00] [debug] [router] default match rule cpu.0:http.0
[2016/09/22 19:19:05] [debug] [out_http] http_status=204
[2016/09/22 19:19:10] [debug] [out_http] http_status=204
[2016/09/22 19:19:14] [debug] [out_http] http_status=204

**Comment by edsiper** [comment]
thanks. btw, did you backported the patch ?, I applied the fix just on master branch.

**Comment by salekseev** [comment]
Yep. Just cherry-picked the commit into 0.8 branch and works beautifully.
Thanks again.

**Comment by edsiper** [comment]
:+1:
