### ISSUE TITLE
What is the reason why "dyntag" APIs were deprecated in the current fluent-bit version?

### ISSUE THREAD

**Issue by aniketoss** [fluent/fluent-bit#1210]
Hi. Since we had needed "dyntag" functionality to fulfill our platform's requirement,  our team used fluent-bit 0.13 in our platform. 

after we finish the discussion about migration of fluent-bit, we decided to update fluent-bit version from 0.13 to 1.0.4. 

under the investigation of fluent-bit 1.0.4 source code, i saw all of the dyntag APIs deprecated. but i cant find any clues why "dyntag APIs were deprecated.

based on my code review, i conclude the current fluent-bit can not support dynamic tag functionality, isn't it?

if right, what is the reason why "dyntag" APIs were deprecated in the current fluent-bit version?

if not, will you have any plan to support dynamic tag functionality at the future version up?

**Comment by edsiper** [comment]
@aniketoss 

a bit of story, dynamic tags were introduced when we had simple/fixed tags in place, so we extended functionality using dynamic tags. Then as the core increase, the Tagging mechanism have to be changed because we had similar functions for static tags and dynamic tags.

Once the new Storage system was placed, the caller that ingest data (input plugin on this case) just set the desired Tag, if no Tag is defined the plugin instance name is used. So for short: we have the same flexibility than before but with a clean API. Migration is just to remove the old_flag and use new API to ingest records as before.
