### ISSUE TITLE
a question about buffering feature 

### ISSUE THREAD

**Issue by aniketoss** [fluent/fluent-bit#1364]
Hi. I have a question while testing buffering feature.

my conf file used by fluent-bit is the following.

[SERVICE]
    # Flush
    # =====
    # Set an interval of seconds before to flush records to a destination
    Flush        5

    # Daemon
    # ======
    # Instruct Fluent Bit to run in foreground or background mode.
    Daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # By default 'info' is set, that means it includes 'error' and 'warning'.
    Log_Level    info

    # Parsers_File
    # ============
    # Specify an optional 'Parsers' configuration file
    Parsers_File parsers.conf

    storage.path              /var/log/flb-storage/
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M

[INPUT]
    Name cpu
    Tag cpu.local
    Interval_Sec 1
    storage.type filesystem

[OUTPUT]
    Name stdout
    Retry_Limit False
    Match *

When I set "Retry_Limit" to Flase, if FLB_OUTPUT_RETURN(FLB_RETRY) occurs, fluent-bit try to create new chunks continuously and all of them are stored in "var/log/flb-storage" since there are no limitation to the size of buffering directories.

so, my question is the following.

if i need to limit the size of buffering directory, Do i implement it myself?

or Can i use other fluent-bit's features to limit the size of buffering directory?

**Comment by gitfool** [comment]
@edsiper I've got a similar question. Maybe I'm missing something but infinite retry with filesystem storage doesn't seem to apply back-pressure and so consumes lots of disk space.

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        daemon                      false
        flush                       1
        log_level                   ${FLB_LOG_LEVEL}
        parsers_file                parsers.conf
        http_server                 true
        http_listen                 0.0.0.0
        http_port                   2020
        storage.path                /var/log/fluent-bit-storage/
        storage.sync                normal
        storage.checksum            false
        storage.backlog.mem_limit   10mb

    @INCLUDE inputs.conf
    @INCLUDE filters.conf
    @INCLUDE outputs.conf

  inputs.conf: |
    [INPUT]
        name                tail
        tag                 kube.*
        path                /var/log/containers/*.log
        db                  /var/log/fluent-bit-kube.db
        exclude_path        *cluster-autoscaler*,*fluent-bit*
        parser              docker
        docker_mode         true
        buffer_chunk_size   64kb
        buffer_max_size     64kb
        mem_buf_limit       10mb
        skip_long_lines     true
        refresh_interval    5
        storage.type        filesystem

  parsers.conf: |
    [PARSER]
        name          docker
        format        json
        time_key      time
        time_format   %Y-%m-%dT%H:%M:%S.%L
        time_keep     false

    [PARSER]
        name          json
        format        json
        time_key      time
        time_format   %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        name          k8s-nginx-ingress
        format        regex
        regex         ^(?<host>[^ ]*) - \[(?<real_ip>[^ ]*)\] - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<last>[^$]*)
        time_key      time
        time_format   %d/%b/%Y:%H:%M:%S %z

  filters.conf: |
    [FILTER]
        name                  kubernetes
        match                 kube.*
        kube_url              https://kubernetes.default.svc.cluster.local:443
        merge_log             true
        keep_log              false
        k8s-logging.parser    true
        k8s-logging.exclude   true

    [FILTER]
        name                  lua
        match                 *
        script                filters.lua
        call                  transform

  filters.lua: |
    function transform(tag, timestamp, record)
        if record["kubernetes"] then
            record["Service"] = record["kubernetes"]["container_name"]
        end

        if record["RenderedMessage"] then
            record["Message"], record["RenderedMessage"] = record["RenderedMessage"], nil
        else
            record["Message"], record["log"] = record["log"], nil
        end

        return 1, timestamp, record
    end

  outputs.conf: |
    [OUTPUT]
        name                    es
        match                   *
        host                    logs
        port                    80
        logstash_format         true
        type                    _doc
        replace_dots            true
        retry_limit             false
```

I currently have a node with over 30,000 `flb` files consuming ~236MB of disk space. 🤔

**Comment by edsiper** [comment]
I will investigate because the only expected behavior is to face storage file system grow just if you get new data ingestion. Retries are chunks that resides already in memory and already hitted the storage interface.

**Comment by gitfool** [comment]
@edsiper the files are still hanging around, the number of which are slowly but surely increasing.

I enabled `trace_output` on the `es` output and tailing the fluent-bit log is interesting... old records from a couple of weeks ago are going by _very_ slowly, with ~5-20 seconds or more between record traces.

**Comment by beckjim** [comment]
> Maybe I'm missing something but infinite retry with filesystem storage doesn't seem to apply back-pressure and so consumes lots of disk space.

Are there any news on this question?
Is there a way to limit disk space usage and to apply back-pressure for this use case?

Otherwise filesystem storage seems hardly usable at the moment ...
Actually an explicit configuration parameter for max. disk usage would be perfect. Reaching that limit should trigger back pressure ...

**Comment by nikinaydenov** [comment]
Hi,
there is no reason to use filesystem buffering with the tail input. It is intended for tcp or udp based inputs (forward, syslog, ...)  or other inputs that lack persistence in the source. Tail and systemd (journald) are the best examples that do not need buffering to filesystem. The files are already persisted in the original location and you have full access to them. In your particular case I am not so right, because when some container die its logs disappear, but this is completely another problem. For that reason I avoid tailing the docker logs and use the fluentd log driver. 

When I try to use buffering to filesystem with es output and just stop the nginx sitting between fluent-bit and elasticsearch I see the files created in buffering directory. When I recover the nginx, fluent-bit reconnects and soon some logs (in my case 2 files out of 6 in the buffer dir) vanish and I see the logs in the elasticsearch. After more than 10 minutes 2 more was processed. This happens around the time when another logs was processed. In this particular case tail input. I decide to test is it a coincident - it is. Decide to just wait. And after 5 more minutes another one was processed.  And short after it the last one. All logs was processed. I think there is nothing missing, but with huge delay. Retry_Limit was set to 100 and 10. No difference in the behavior. The number of files in the buffer directory varies, but as whole the behavior do not change: some of the files are processed with 10-15 minutes delay.

The same tested with memory buffering. No problem found - no delay after network connection recovery.

**Comment by edsiper** [comment]
Extended details of Buffering & Storage:

https://docs.fluentbit.io/manual/administration/buffering-and-storage#chunks-memory-filesystem-and-backpressure
