### ISSUE TITLE
in_statsd: new input plugin

### ISSUE THREAD

**Issue by talawahtech** [fluent/fluent-bit#1546]
**Is your feature request related to a problem? Please describe.**
I am currently interested in collecting and storing performance logs from cadvisor using its ability to export data to  [statsd](https://github.com/google/cadvisor/blob/master/docs/storage/statsd.md). But this would also be a general solutions for storing performance logs from other systems that support statsd as an output format.

**Describe the solution you'd like**
A new input plugin that accepts data in the statsd format. Similar in concept to [in_collectd](https://github.com/fluent/fluent-bit/pull/1506).
 
**Additional context**
There are cases where it is preferable to store performance related data in a "logging" backend instead of a traditional metrics backend. Oftentimes this allows for better correlation against related data and more sophisticated querying.

**Comment by fujimotos** [comment]
I've been working on this issue since today, and will update
the status as it proceeds.

**Comment by fujimotos** [comment]
@eduardo I reached the point that I can receive and parse incoming statsd
packets. For instance, I can parse an input metric `foo|99:c` into:

    {"bucket":"foo","value":99,"type":c}
    
Now I'm seeing that there are two possible ways to go. One way is to emit
each packet as a separate record per received. In this case, we'll get
records like below:

    {"bucket":"foo","value":99,"type":c}

Another way is to aggregate records in `in_statsd` and emits the resulting
statistics at a certain interval (just as a normal statsd server would do).
In this case, we'll get records like the following:

    { counters:
       { 'statsd.bad_lines_seen': 0,
         'statsd.packets_received': 1,
         'statsd.metrics_received': 1
         'foo': 99},
      timers: {},
      gauges: { 'statsd.timestamp_lag': 0 },
      timer_data: {},
      counter_rates:
       { 'statsd.bad_lines_seen': 0,
         'statsd.packets_received': 0.1,
         'statsd.metrics_received': 0.1,
         'foo': 9.9 },
      sets: {},
      pctThreshold: [ 90 ] }

Which way do you think is appropriate? The easier route is the former 
(= emits incoming records as is), but I think it depends on how the new
plugin is supposed to behave.

**Comment by fujimotos** [comment]
After some thought, I've come to the conclusion that we should process
incoming metrics in `in_statsd`, since many messages in statsd do not
make much sense without some aggregation.

For instance, according to the spec, `foo:+99|g` means "add 99 to the
latest gauge value of foo". So naturally it is expected of `in_statsd` to
keep the state of gauges and produce the consolidated results.

Indeed, this is what many statsd-compatible servers do. For example,
If a client inputs the following datagrams:

```
baa:99|g
baa:+1|g
baa:-10|g
```

a statsd-compatible server is expected to produce the following output:

```
stats.gauges.baa 90
```

I have spent much of today implementing `in_statsd` to emit events as just
described above (and almost done it). I think I can post a PR shortly...

**Comment by edsiper** [comment]
from a consumer perspective, what makes easier to process the metrics or aggregate them later in a database?, what do you see in some use cases ?

**Comment by fujimotos** [comment]
@edsiper  I posted a draft of the statsd plugin to #1741.

> from a consumer perspective, what makes easier to process the metrics or aggregate them later in a database?, what do you see in some use cases ?

The big picture here is, I think, many consumers expect `in_statsd`
to do the aggregating task for them.

In general, consumers seem to be interested in doing visualization over
aggregated statistics (like plotting _average_ server response time),
and not much interested in tinkering with raw data by themselves.

I assume this is the reason why [telegraf's statsd input](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd
) writes aggregated
statistics, rather than the raw metrics, into InfluxDB. 

Probably we can add a "raw_metric" option to `in_statsd` to pass through
raw values to the output plugin (it is easy to implement). That way we can
cover both use cases.

**Comment by fujimotos** [comment]
> The big picture here is, I think, many consumers expect in_statsd
> to do the aggregating task for them.

I read my comment this morning, and thought I was not clear enough. 

I see several products exist that support `statsd` input port. All of them
seem to implement `statsd`-like data aggregation by default.

* DataDog (dogstatsd)
  https://docs.datadoghq.com/developers/dogstatsd/
* InfluxDB (Telegraf)
  https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd
* Collectd (plugin_statsd)
  https://collectd.org/wiki/index.php/Plugin:StatsD

Reflecting on this, I thought it's very likely that users would expect
our statsd plugin to behave all much the same way. Without such a
functionality, the plugin would seem unsatisfactory to users.

If we want the "save the raw data" feature, I think we can implement
it on top of the current feature set (e.g. adding "raw_value" flag
should be easy enough).

* I'm not sure this is common use case though, since no other product
  provides such a feature.

Anyway I believe #1741 is a good first cut at adding statsd support, and
should be mergeable.

**Comment by fujimotos** [comment]
@edsiper I did a bit of research on this matter and posted a PR to #1741.
I think this one is the most compatible solution with statsd, and should make
Fluent Bit on par with other products in this area.

* https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_statsd
* https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd

I'd greatly appreciate if I can get some feedback from you on that patch.

**Comment by fujimotos** [comment]
@talawahtech If possible, can you check #1741 and give us some feedback?
I'd like to hear your opinion on how the plugin is expected to work.

**Comment by fujimotos** [comment]
> from a consumer perspective, what makes easier to process the metrics or aggregate them later in a database?, what do you see in some use cases ?

@edsiper After re-reading your comment, I posted a simpler patch at #1756,
which focuses on handling statsd protocol messages.

It can emit incoming metrics as msgpack records without loss of information,
and should meet @talawahtech's following requirement well.

> There are cases where it is preferable to store performance related data in a "logging" backend instead of a traditional metrics backend. Oftentimes this allows for better correlation against related data and more sophisticated querying.

I'm looking forward to your review and feedback!

**Comment by edsiper** [comment]
FYI: PR #1756 reviewed and commented

**Comment by talawahtech** [comment]
@fujimotos yes, I think the approach in #1756 is more in line with how I plan to use it. I haven't gotten a chance to test it out yet, but I will try and provide feedback when I do. Thanks for working on this!

**Comment by edsiper** [comment]
Implemented by @fujimotos on #1756
