### ISSUE TITLE
STREAM Processor: support GROUP BY on fields that are not in the SELECT and fields that are in SELECT but not in GROUP BY

### ISSUE THREAD

**Issue by hansmeijerprotegrity** [fluent/fluent-bit#1754]
## Bug Report

**Describe the bug**
When using stream processor we use it as an aggregate function, i.e.:
CREATE STREAM agg_stream WITH (tag='json_subkey') AS SELECT json_field1['description'], logtype, level, origin['hostname'], SUM(summary_field) from STREAM:in_data GROUP BY json_field1['description'], logtype, level, origin['hostname'];
Instead we would like it to support also doing GROUP BY on fields that are not in the SELECT clause and fields and also have fields in the SELECT clause that are not in the GROUP BY.

**To Reproduce**
Preferrably in the above scenario we would like it to support this sample:
CREATE STREAM agg_stream WITH (tag='json_subkey') AS SELECT json_field1['description'], logtype, level, origin['hostname'], userinfo['username'], SUM(summary_field) from STREAM:in_data GROUP BY json_field1['description'], level, origin['hostname'], origin['ip'];
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:
CREATE STREAM agg_stream WITH (tag='json_subkey') AS SELECT json_field1['description'], logtype, level, origin['hostname'], userinfo['username'], SUM(summary_field) from STREAM:in_data GROUP BY json_field1['description'], level, origin['hostname'], origin['ip'];

**Expected behavior**
GROUP BY supported both for fields in the SELECT CLAUSE but also fields that are only in the GROUP BY and not in the SELECT CLAUSE.
**Screenshots**
<!--- If applicable, add screenshots to help explain your problem. -->

**Your Environment**
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**
We are trying to do some aggregation of records that are basically the same but differs on some fields, and these we do not want to aggregate on since they will disallow the aggregation to function.

**Comment by koleini** [comment]
@hansmeijerprotegrity Thanks for submitting the issue.

Regarding `also have fields in the SELECT clause that are not in the GROUP BY`:

Note that your query

```
SELECT json_field1['description'], logtype, level, origin['hostname'], userinfo['username'], SUM(summary_field) from STREAM:in_data GROUP BY json_field1['description'], level, origin['hostname'], origin['ip']
```

is not valid. When using `GROUP BY`, you have to apply an aggregation functions over the keys in SELECT clause, except the key is in `GROUP BY` clause. That means, in your example, you can have `json_field1['description']`, `level`, and `origin['hostname']` in your `SELECT` clause without aggregation function (since we are grouping the records based on them), but `userinfo['username']` can't be there without any aggregation function applied (you can run similar query against a database and see how it responds).

Regarding `doing GROUP BY on fields that are not in the SELECT clause`:
Yes, that is a valid query, although you are removing some information from your output records, for instance, the value of `origin['ip']`, which the grouping is based on. I can send a fix.

**Comment by hansmeijerprotegrity** [comment]
Thanks Masoud
Please send a fix if you the possibility.

Kind regards
Hans
