### ISSUE TITLE
Match is Not Clearly Defined in the Docs

### ISSUE THREAD

**Issue by kaizen1** [fluent/fluent-bit#1792]
First, under Configuration File documentation, this sentence makes no sense in English. 

**Match | It sets a pattern to match certain records Tag.** 

And the Match examples in the docs do not help because they don't explain what the match is AGAINST.  Against a data stream? Against a config parameter? Match against what?
 
--> Which leads to further confusion.
From the docs:
 
_The following command will load the tail plugin and read the content of lines.txt file. Then the grep filter will apply a regular expression rule over the log field (created by tail plugin) and only pass the records which field value starts with aa:_

  `bin/fluent-bit -i tail -p 'path=lines.txt' -F grep -p 'regex=log aa' -m '*' -o stdout`

Since a Regex is a matching function, the documentation isn't clear on the difference between the Match parameter within a FILTER section and a grep filter type with a regex.

Also, OUTPUT has a Match * throughout the docs with no explanation what you're matching AGAINST. What are you matching?

The terminology/functionality is confusingly overlapping.

**Comment by fujimotos** [comment]
@kaizen1 You really need to move to https://github.com/fluent/fluent-bit-docs,
since this is a documentation matter.

> And the Match examples in the docs do not help because they don't explain what the match is AGAINST. Against a data stream? Against a config parameter? Match against what?

The core concept you need to grasp is that Fluent Bit is _a tag-based routing
system._ Every incoming record has a single tag associated with it. These tags
determine which filters to apply to each record.

For example, suppose you have the following configuration:

```
[INPUT]
  Name Dummy
  Tag foo.dummy

[INPUT]
  Name Dummy
  Tag bar.dummy

[FILTER]
  Name record_modifier
  Match foo.*
  Record note FILTER_APPLIED

[OUTPUT]
  Name stdout
  Match *
```

This configuration creates two input streams of records: the first one
emits records with "foo.dummy" tag, and the second one emits records with
"bar.dummy" tag. The `record_modifier` filter has a Match condition `foo.*`,
so it is only applied to the former records, while the `stdout` output
is applied to every record.

So if you run your Fluent Bit with this configuration, you'll see the
following output:

```
$ fluent-bit -c example.conf
...
[0] foo.dummy: [1575948810.000229380, {"message"=>"dummy", "note"=>"FILTER_APPLIED"}]
[0] bar.dummy: [1575948810.000263104, {"message"=>"dummy"}]
```

If you want to only output records of "bar.dummy", all you need to do
is to modify the Match condition of `stdout` to `bar.*` (or `bar.dummy`).

That's fairly straightforward, isn't it?

> First, under Configuration File documentation, this sentence makes no sense in English.
 
I prepared a patch that updates the description so that it says more
clearer about what the `Match` option is supposed to match against.

https://github.com/fluent/fluent-bit-docs/commit/dd944fe7f306af75b25891833ccefba307838732

If this seems good to you, I will make it a PR.

**Comment by kaizen1** [comment]
This is an excellent explanation. It helps. But one remaining source of confusion that I had is that records _**cannot**_ flow through a FILTER **_without_** altering the record stream. The docs need to say this. For example, in Rsyslog, records can flow through filters **without** altering the stream (omit a STOP). This allows for sending input records to multiple outputs since there were not removed or narrowed. This is not possible now in Fluent Bit and since people ASSUME it exists, we get confusion.

**Comment by fujimotos** [comment]
I made fluent/fluent-bit-docs@dd944fe a PR.

> But one remaining source of confusion that I had is that records cannot flow through a FILTER without altering the record stream

Yes, that's true. Rsyslog fans out events to multiple filters whereas
Fluent Bit percolates a single input stream to outputs.

This really feels to me a cultural difference. This data model might look
alien to those who are coming from syslog, but it is the norm in Fluentd
ecosystem (in fact, Fluentd behaves in much the same way).

**Comment by edsiper** [comment]
thanks, closing since this is already fixed by @fujimotos

**Comment by kaizen1** [comment]
But if we have a TCP input stream, you are saying we need to listen on multiple ports to accomplish what rsyslog does on a single port. Not good.

**Comment by edsiper** [comment]
@kaizen1 

- the solution for that scenario in Fluentd is tag-rewrite, which means re-tag  a record based in a criteria.  In Fluent Bit tag rewrite aims to be implemented by end of January, check v1.4 milestone: 

https://github.com/fluent/fluent-bit/milestone/7

the current workaround in Fluent Bit is to use the Stream Processor, which allows you to create new tagged streams of data and send them to different locations:

- https://docs.fluentbit.io/stream-processing/

despite Stream Processing is a workaround, tag-rewrite is the right thing.

**Comment by kaizen1** [comment]
@edsiper 
Thanks for the information. I was able to work around. By using your "record drop" data I could see how many records I had. I was really after a counter of each regex so it works for now.

**Comment by adrian-skybaker** [comment]
What patterns does match support? Presumably it's not a regex? Can I match against multiple patterns?

**Comment by MikeTomlin19** [comment]
> What patterns does match support? Presumably it's not a regex? Can I match against multiple patterns?

I'd like to know the same and can't find it documented anywhere.

**Comment by duijf** [comment]
You can find docs on `match` here: https://docs.fluentd.org/configuration/config-file#how-do-the-match-patterns-work

**Comment by solaris-ventus** [comment]
> > What patterns does match support? Presumably it's not a regex? Can I match against multiple patterns?
> 
> I'd like to know the same and can't find it documented anywhere.
https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml/configuration-file
```
Match_Regex
```
