### ISSUE TITLE
Can't Use Multiple Filters on Single Input

### ISSUE THREAD

**Issue by kaizen1** [fluent/fluent-bit#1800]
1. I have a single INPUT name tcp
2. I have two different FILTER (each is a different grep - regex)
3. Each FILTER has its own OUTPUT file

This does not work. I get no output.

If I have single FILTER/OUTPUT it works OK. So I do not have INPUT or regex problem.

Is single grep-regex FILTER a limitation ?

**Comment by edsiper** [comment]
records flow across filters and output based on tag/match rules:

https://docs.fluentbit.io/manual/getting_started/routing

please share your configuration file so we can advise

**Comment by kaizen1** [comment]
Thanks. 


[INPUT]
    Name     tcp
    Listen   0.0.0.0
    Port     5140
    Alias    Analysis
    Tag      Analysis_Count

[FILTER]
    Name   grep
    Match  *
    Regex  message aa
    Alias  ALERT

[FILTER]
    Name   grep
    Match  *
    Regex  message bb
    Alias  WARN

How do I get two separate output files? 
The first filter wipes out all bb records.

**Comment by DrPyser** [comment]
I'm confused. 

Is it possible to use multiple filters(an ordered chain of filters) for the data stream from a single input? I also think I'm encountering issues where log stream is never outputted when I have multiple filters configured.
It should be possible, since different filters and filter instances accomplish different goals in the processing pipeline.
For example, in my case I want to 
* modify the records by lifting keys, renaming keys, ...
* rewrite the tag before forwarding the records(i.e. using `forward` output).

Thanks!

**Comment by DrPyser** [comment]
Hmm, I think it was my rewrite_tag filter that wasn't working. 
It seems to work with two filters.
