### ISSUE TITLE
td-agent-bit 1.3.7 version is not supporting kafka plugin for windows

### ISSUE THREAD

**Issue by yeruvass** [fluent/fluent-bit#1944]
kafka output plugin is not available for td-agent-bit 1.3.7 version.

td-agent-bit version :- 1.3.7
environment :- Windows

Problem statement :- kafka plugin is not available in td-agent-bit 1.3.7 version. check below screenshot.

<img width="576" alt="td-agent-bit" src="https://user-images.githubusercontent.com/5181193/74309674-bbccbb80-4d84-11ea-9bfb-7910c277bfc2.png">

Please let me know how to include kafka plugin for td-agent-bit 1.3.7

**Comment by fujimotos** [comment]
@yeruvass Yes, we stopped to bundle kafka plugin since v1.3.7.

This is due to the plugin being dependent on the non-standard DLL (ssleay.dll)
and it turned out to be causing a lot of troubles for users (#1646, #1837 etc.)

We are planning to re-include the plugin once we resolve the issue, but sadly
we are not getting there yet.

**Comment by yeruvass** [comment]
Is Kafka output plugin available in 1.3.6 version ??

**Comment by fujimotos** [comment]
> Is Kafka output plugin available in 1.3.6 version ??

Yes. It is. The Kafka plugin is included in v1.3.6 or before

**Comment by aymericDD** [comment]
@fujimotos Do you know when the issues will be resolved?

**Comment by simontilmant** [comment]
+1 interested in a way to enable kafka output plugin on Windows

**Comment by aymericDD** [comment]
Still needed
