### ISSUE TITLE
Fluent-bit logs not being sent to specified log file

### ISSUE THREAD

**Issue by estroz** [fluent/fluent-bit#218]
Setting a log file path, either using the `-l` option or the `Log_File` key in my conf file, does not create a log file when using the `-d` option. I've tested this by using the `forward` output plugin and an unbound port (24225) as in the following command:
```
fluent-bit -d -l /var/log/fluent-bit.log -i cpu -t fluent_bit -o forward://127.0.0.1:24225
```

Omitting the `-d` option from the above command (or `Daemon` from my conf file) results in the following output in stdout:
```
[2017/03/29 01:51:18] [ info] [engine] started
[2017/03/29 01:51:23] [error] [io] TCP connection failed: 127.0.0.1:24225
[2017/03/29 01:51:23] [error] [out_fw] no upstream connections available
```
which is as expected. None of this information is logged to the log file when using the `-d` and `-l` options together, and the file is not created. However the log file is correctly created and written to when running without `-d` and with `-l /var/log/fuent-bit.log`.

**Comment by edsiper** [comment]
thanks for report this problem.

troubleshooting...

**Comment by edsiper** [comment]
I've found the problem happens because of the following:

- doing fork() after threads are created is not right, threads are destroyed (log is destroyed)
- when switching to daemon mode, the child process does a chdir('/'), so an absolute path is required for the log file

@estroz I've pushed a test branch called __log-test__, would you please checkout the latest changes and try:

- recompile new code
- use an absolute path for the log file

**Comment by estroz** [comment]
@edsiper works as expected now. thank you!

**Comment by edsiper** [comment]
awesome!
