### ISSUE TITLE
Kubernetes filter cuts off first character from pod name

### ISSUE THREAD

**Issue by Oduig** [fluent/fluent-bit#2342]
## Bug Report

**Describe the bug**

Kubernetes filter cuts off first character from pod name

**To Reproduce**

Add a default Kubernetes filter configured with default settings as mentioned here: https://docs.fluentbit.io/manual/pipeline/filters/kubernetes

**Expected behavior**

Payload contains a field `kubernetes` with a field `pod_name` with value `my_pod`. Instead, the value is `y_pod`.

**Your Environment**

Docker container `fluent/fluent-bit:1.3.11`
Version 1.3.11
Running on Azure Kubernetes as a DaemonSet

**Additional context**

The hard coded regex mentioned in documentation (https://docs.fluentbit.io/manual/pipeline/filters/kubernetes) is as follows.

```
(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
```

I think the first `[a-z0-9]` is in the wrong place and it should be:

```
(?<pod_name>(?:[a-z0-9][-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
```

Let me know if you need more information.

**Comment by edsiper** [comment]
@Oduig would you please share your full name of the log file being monitored that generates the problem ?

note: that file name is processed and used as a Tag, then the regex is applied on top of it.

**Comment by Oduig** [comment]
Sure. It happens for all our Kubernetes containers, here is one of them:

`/var/log/containers/volta-ws-api-6d846db864-m6lgk_dev_volta-ws-api-b058884e94f4b8b958079a71730302861a93a5aa6dc49e265fcecaf553c11c51.log`

With the regex I proposed as a `Regex_Parser`, the problem is solved.

**Comment by edsiper** [comment]
Testing the example file name and the original regex, I don't see such problem:

https://rubular.com/r/c0sOylwGZkBP8J

would you please provide a problematic file name that triggers the issue ?

**Comment by Oduig** [comment]
@edipser Oddly, it seems to work now. I saw the issue several times, and afterI changed the regex the problem went away. I reverted my change and it's still working as intended. Can't for the life of me imagine what caused this, but it should not be your problem to figure it out. Thank you for taking the time!

**Comment by nirousseau** [comment]
I have been able to reproduce this issue recently with fluentbit `1.9.6`.

The issue comes from misconfigured pipelines with the `kubernetes` filter.

Let's assume you have two distinct flows, using two `tail` inputs :

```
[INPUT]
    Name                        tail
    Path                        /var/log/containers/*_nginx-ingress_*.log
    db                          /var/log/flb-storage/ngx.db
    multiline.parser            docker, cri
    Tag                         ngx.*
    Ignore_Older                14d
    Skip_Long_Lines             Off
    Skip_Empty_Lines            On
    storage.type                filesystem

[INPUT]
    Name                        tail
    Path                        /var/log/containers/*.log
    db                          /var/log/flb-storage/kube.db
    Exclude_Path                /var/log/containers/*_nginx-ingress_*.log
    multiline.parser            docker, cri
    Tag                         kube.*
    Buffer_Chunk_Size           32k
    Buffer_Max_Size             32k
    Ignore_Older                14d
    Skip_Long_Lines             On
    Skip_Empty_Lines            On
    Mem_Buf_Limit               128M
    Static_Batch_Size           50M
    storage.type                filesystem
```

if you want to add kubernetes `pod` metadata to your log, you have to configure `kubernetes` filters. The configuration below is **CORRECT** :

```
[FILTER]
    Name                        kubernetes
    Match                       ngx.*
    Kube_Tag_Prefix             ngx.var.log.containers.
    Buffer_Size                 256k
    Merge_Log                   On
    Merge_Log_Trim              On
    Merge_Parser                custom-nginx-ingress
    Keep_Log                    Off
    Annotations                 Off

[FILTER]
    Name                        kubernetes
    Match                       kube.*
    Kube_Tag_Prefix             kube.var.log.containers.
    Buffer_Size                 256k
    Merge_Log                   On
    Merge_Log_Key               log_processed
    Keep_Log                    Off
    K8S-Logging.Parser          On
    K8S-Logging.Exclude         On
    Annotations                 Off
```

When using multiple inputs, logs will be tagged with a distinct prefix. My mistake was to not correctly override `Kube_Tag_Prefix` using the correct tag, corresponding to its input. 

In order to illustrate it, the configuration below is **NOT CORRECT** :

```
[FILTER]
    Name                        kubernetes
    Match                       ngx.*
    Buffer_Size                 256k
    Merge_Log                   On
    Merge_Log_Trim              On
    Merge_Parser                custom-nginx-ingress
    Keep_Log                    Off
    Annotations                 Off

[FILTER]
    Name                        kubernetes
    Match                       kube.*
    Buffer_Size                 256k
    Merge_Log                   On
    Merge_Log_Key               log_processed
    Keep_Log                    Off
    K8S-Logging.Parser          On
    K8S-Logging.Exclude         On
    Annotations                 Off
```

I would expect that It should not process records for `ngx.*` pipeline, because there are no records with prefix `kube.var.log.containers.` that will match the filter match "ngx.*". However, if you leave the default value (that is `kube.var.log.containers.`) for the kubernetes filter handling "ngx.*" logs, fluentbit will truncate the first char of the pod name when resolving metadata :

```
[filter:kubernetes:kubernetes.2] HTTPresponse
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"ginx-ingress-controller-66d7f9bf87-x5qww\" not found","reason":"NotFound","details":{"name":"ikita-controller","kind":"pods"},"code":404}
```

It seems to be linked with the regex using in the input "`Tag_Regex` parameter" (https://docs.fluentbit.io/manual/pipeline/inputs/tail) : 
```
(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
```
when entered in a regex debugger : https://regex101.com/r/CjQJl1/1

From my observations, logs are processed instead of being skipped, and it will end up using the "group 2", truncating the first char, replicating the issue described here.

I would categorize it as a bug in fluentbit, but it comes from a misconfiguration first !
