### ISSUE TITLE
Consider Alpine Glibc as base image

### ISSUE THREAD

**Issue by StevenACoffman** [fluent/fluent-bit#239]
Given the difficulties with working with musl on stock Alpine linux:
+ Jemalloc (memory allocator) on Musl cannot be integrated properly
+ Musl functions bootstrap have a compatibility issue when loading Golang shared libraries
+ Alpine linux musl Time format parser does not support glibc extensions #231 

Please consider using `FROM frolvlad/alpine-glibc` as your alpine base image [found here](https://github.com/frol/docker-alpine-glibc). In my testing, it appears to resolve most issues with very little hassle.

Thanks again for an excellent solution and a thoroughly enjoyable experience.

**Comment by edsiper** [comment]
Due to security reasons (meaning maintenance over the time), Google Debian based image was chosen. 

At the moment I would not pick a forked and modified image unless there is a proof of continuous security checks over it base content. 

I understand it allows to deploy Fluent Bit in a smaller image, but from our perspective security is first. If the Alpine Linux team start maintaining officially, that would change things a bit.

**Comment by edsiper** [comment]
Closing this issue. If the image becomes officially supported we can add it to our Docker hub repo.

**Comment by StevenACoffman** [comment]
@edsiper Do you have issue links for the other two alpine issues? I might work on patches for musl as an alternative.
For security, you'd need to basically fork that image and maintain it yourself, so I understand. If I work on getting musl to support the other pieces, maybe it would be worth revisiting.
