### ISSUE TITLE
1.5.6: error: invalid argument type 'char *(*)(int, int)' to unary expression

### ISSUE THREAD

**Issue by yurivict** [fluent/fluent-bit#2573]
Log: http://beefy6.nyi.freebsd.org/data/121amd64-default/548931/logs/errors/fluent-bit-1.5.6.log

FreeBSD 12.1
clang-8

**Comment by fujimotos** [comment]
> Log: http://beefy6.nyi.freebsd.org/data/121amd64-default/548931/logs/errors/fluent-bit-1.5.6.log

@yurivict This error is due to the POSIX incompatibility of FreeBSD.

FreeBSD exports a function symbol named `timezone`, while other
UNIX-like OSs use that symbol to store a current timezone.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=24590

I implemented a fix for this issue last month in #2493, so is should
be resolved once the patch gets merged into the main line.

**Comment by edsiper** [comment]
PR merged, thanks
