### ISSUE TITLE
[windows] Build with Toolset 120xp not supported

### ISSUE THREAD

**Issue by hidiego** [fluent/fluent-bit#2693]
## Bug Report

**Describe the bug**
Compilation for under windows xp toolset 120 fails, is it supported? Am I doing something wrong?

**To Reproduce**
Clone the repository and in the build folder execute `cmake -G "Visual Studio 12 2013" -A WIN32 ..`
the .sln file is generated but when trying to compile it give tons of syntax errors:

[ErrorOutput.log](https://github.com/fluent/fluent-bit/files/5392361/ErrorOutput.log)

**Comment by edsiper** [comment]
cc: @fujimotos

**Comment by fujimotos** [comment]
This is probably due to the use of `uint_fast32_t` in crc32.h. It seems
that Visual Studio < 2015 does not support that type.

@hidiego We are currently bilding the Windows port against MSVC 2017/2019,
so MSVC 2013 is not supported.

Is there any particular requirement that you should use the older version?

**Comment by hidiego** [comment]
Hi, well I wanted to make take some of the potential of this library to Windows XP.
It's legit not to support it really, so thanks for the answer :)
