### ISSUE TITLE
kinesis_firehose output plugin: milliseconds/microseconds do not work in time_key_format (%L or %f)

### ISSUE THREAD

**Issue by Walderman** [fluent/fluent-bit#2861]
## Bug Report

**Describe the bug**
Trying to use kinesis_firehouse with fluent-bit (version 1.6)
I specify time_key and time_key_format as per documentation (https://docs.fluentbit.io/manual/pipeline/outputs/firehose)
but %L or %f is not rendered

**To Reproduce**
[OUTPUT]
    name kinesis_firehose
    match *
    region <region>
    delivery_stream <__delivery_stream__>
    time_key time
    time_key_format %Y/%m/%d %H:%M:%S.%L

or

[OUTPUT]
    name kinesis_firehose
    match *
    region <region>
    delivery_stream <__delivery_stream__>
    time_key time
    time_key_format %Y/%m/%d %H:%M:%S.%f

```
{"time": "2020/12/13 19:41:40.%L"}
or
{"time": "2020/12/13 20:01:14.%f"}
```

**Expected behavior**
kinesis_firehose supports milliseconds and microseconds and they are correctly rendered on output logs

**Your Environment**
AWS EMR: emr-6.2.0
* Version used:
1.6
* Operating System and version:
Red Hat
* Filters and plugins:
kinesis_firehose

**Comment by fako** [comment]
I have the same issue

**Comment by lakestonelabs** [comment]
I too ran into the same issue. I tracked the code back it library for 'strftime' which is here github.com/lestrrat-go/strftime and the firehose plugin looks to be invoking that library and it's support for millisecond/microsecond correctly.

**Comment by hackery** [comment]
@lakestonelabs not sure you have the right library there, as Fluent-Bit is written in C, not Go.
At the time you were writing, the Firehose output was using the C standard library `strftime`; since [Jan 2023](https://github.com/fluent/fluent-bit/commit/f3e480ac84126254484a869219fce598e847a3ed) it has used a home-brewed `flb_aws_strftime_precision` function which handles sub-second precision (but has bugs per this and other github issues, e.g. #7538).
