### ISSUE TITLE
in_head: flexible log key name

### ISSUE THREAD

**Issue by mahdi-asadpour-rr** [fluent/fluent-bit#299]
When input type is "head" (or "tail" and perhaps others) and output "es" (such as below), the result entry in the elasticsearch is indexed under a broad term such as "head" which could be misleading. As a user, I'd like to see the tag (here: "cpu_temperature") is also included.

[INPUT]
    Name             head
    Tag                 cpu_temperature
    File                /sys/class/thermal/thermal_zone0/temp

[OUTPUT]
    Name            es
    Match            *
    Host              localhost
    Port                9200
    Index              logs
    Type               test

**Comment by edsiper** [comment]
@mahdi-asadpour-rr 

The thing is that in_head plugin uses a hard coded key name which is __head__, so since this is part of the message, Elasticsearch will use the information that is getting. We will make sure to add this feature.

As a workaround I'd suggest you try to set a Elasticsearch Type called cpu_temperature (not ideal but a workaround in the meanwhile we implement the feature).

@nokute78 do you think you can add an option called __key__ in the configuration of in_head ? so the user can define how he wants to call the key of the message  ?, e.g:

```
$ bin/fluent-bit -i head -p file=/proc/cpuinfo -o stdout:
[0] head.0: [1497634150, {"head"=>"34900\x0a"}]
```

with __key__ property:

```
$ bin/fluent-bit -i head -p file=/proc/cpuinfo -p key=cpu_temp -o stdout:
[0] head.0: [1497634150, {"cpu_temp"=>"34900\x0a"}]
```

**Comment by nokute78** [comment]
I pushed #300.

**Comment by edsiper** [comment]
PR #300 have been merged. 

@mahdi-asadpour-rr please use the new configuration __key__ to specify the desired field name of the message.

**Comment by mahdi-asadpour-rr** [comment]
@nokute78 @edsiper thanks, it works.
