### ISSUE TITLE
Fluent bit not parsing msec time correctly %s.%L

### ISSUE THREAD

**Issue by capricornusx** [fluent/fluent-bit#3072]
## Bug Report

```
[PARSER]
    Name         nginx-json
    Format       json
    Time_Key     @timestamp
    Time_Format  %s.%L
```
I use time format `%s.%L` for parsing unixtime.msec like `1550000000.444` on nginx logs, but result timestamp in elasticsearch is different ( not equal original time in log).
 
**Environment**
* Version used: **Fluent Bit v1.6.10**
* Operating System and version: **Ubuntu 20.04.2 LTS**
* Filters: defaults

**links**
 - [my configuration gist](https://gist.github.com/capricornusx/f077d5ef39161e431f824d261a311eae)
 - [parsers json](https://docs.fluentbit.io/manual/pipeline/parsers/json) 
 - [documentation](https://fluentbit.io/documentation/0.13/parser/)

**Comment by agup006** [comment]
Hey @capricornusx , I think you might have an older link to the documentation, latest can be found at the following link: https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch. 

From the included configuration - The parameter `Current_Time_Index On` - means that you are using the current time for index generation instead of message record.

I would recommend using the Time_Key @timestamp to ensure that it uses the log fields time key instead of current time
