### ISSUE TITLE
Unable to add nested json fields in log events 

### ISSUE THREAD

**Issue by atreyd** [fluent/fluent-bit#3181]
We are using the fluentbit as log driver for containerised microservices running on ECS. We have also adopted a standard logging JSON schema which is used by all the microservices to generate log in a standard format.
Standard format includes Service.Name and Event.Date fields which are mandatory for adding logs to Elasticsearch.
However there are certain log events which are generated before the standard logger is initialised or sometimes developers miss to add the logger on each and every log event.
So we are looking to add the Service.Name and Event.Date fields through fluentbit for the events which doesn't have Service.Name and Event.Date.
The issue is that we have Service and Event as a nested json array and hence it is required to add Name and Date into nested json format inside Service and Event map respectively.
Does any fluentbit filter supports adding new fields in a nested JSON format ?

**Comment by agup006** [comment]
You could use the modify filter: https://docs.fluentbit.io/manual/pipeline/filters/modify and it's conditional logic to check for those fields

Additionally, if you need a nested JSON after using the modify filter you can use the `Nest` filter: https://docs.fluentbit.io/manual/pipeline/filters/nest#example-1-nest-and-lift-undo

Since this is more of a question I'm going to close this github issue for now.
