### ISSUE TITLE
Buffering & storage issue

### ISSUE THREAD

**Issue by RiccardoManfrin** [fluent/fluent-bit#3218]
## Bug Report

**Describe the bug**
Ciao,

[This](https://docs.fluentbit.io/manual/administration/buffering-and-storage#output-section-configuration) section of the doc says 

> If for some reason Fluent Bit get's offline because of a network issue, it will continuing buffering CPU samples but just keeping a maximum of 5M of the newest data.

I'm tring to forward logs between two fluentbit instances sitting in the same network, but I'm not seeing any buffered logs being forwarded to the receiver when it is restarted after a period of inactivity.

**To Reproduce**

- Example log message if applicable:

```
fluentbit_1.7.1 | [2021/03/11 23:28:26] [debug] [output:forward:forward.0] request 447 bytes to flush
fluentbit_1.7.1 | [2021/03/11 23:28:26] [debug] [task] created task=0x7f1dd9631560 id=1 without routes, dropping.
fluentbit_1.7.1 | [2021/03/11 23:28:26] [debug] [task] destroy task=0x7f1dd9631560 (task_id=1)
fluentbit_1.7.1 | [2021/03/11 23:28:26] [error] [net] TCP connection failed: 192.168.178.31:24224 (Connection refused)
fluentbit_1.7.1 | [2021/03/11 23:28:26] [error] [net] cannot connect to 192.168.178.31:24224
fluentbit_1.7.1 | [2021/03/11 23:28:26] [debug] [upstream] connection #46 failed to 192.168.178.31:24224
fluentbit_1.7.1 | [2021/03/11 23:28:26] [error] [output:forward:forward.0] no upstream connections available
```

- Steps to reproduce the problem:

1. start both forwarder and receiver
2. kill receiver and wait for some time
3. restart receiver

**Expected behavior**
I thought that the sender instance of fluentbit would cache the logs not successfully delivered up to 5M and than flush them when the receiver was restarted.

**Your Environment**
* Version used: FLuentbit 1.7.1
* Configuration:
The forwarder config is:

```
[SERVICE]
   Flush 5
   Daemon Off
   Log_Level debug

[INPUT]
   Name systemd
   Tag events
   Path /var/log/journal/
   Systemd_Filter SYSLOG_FACILITY=23

[OUTPUT]
   Name forward
   Match events
   Host 192.168.178.31
   Port 24224
   storage.total_limit_size  5M
```

The receiver config is

```
[SERVICE]
   Flush 5
   Daemon Off
   Log_Level debug

[INPUT]
   Name forward
   Listen 192.168.178.31
   Port 24224

[OUTPUT]
   Name stdout
   Match *
```
* Environment name and version:
Sender:  Centos 7, Docker version 20.10.3, build 48d30b5, docker.io/fluent/fluent-bit:1.7.1
Receiver: Ubuntu 20.04, Docker version 19.03.8, build afacb8b7f0, docker.io/fluent/fluent-bit:1.7.1

**Comment by JeffLuoo** [comment]
@RiccardoManfrin 
hi, buffered chunks will be retried to send with a limit (default is 1). Which means that if Fluent Bit fails to send the chunk to destination, then it will schedule a retry for the task. If the retry task failed as well, then this chunk will be dropped (we lost the data). You might need to configure `retry_limit` to any number you need in order to keep the data chunk https://docs.fluentbit.io/manual/administration/scheduling-and-retries#example

**Comment by RiccardoManfrin** [comment]
@JeffLuoo so there is not in general a mechanism/configuration in fluentbit to specify the maximum retention queue size of messages yet to be forwarded. Can you confirm this?

**Comment by JeffLuoo** [comment]
The `storage.total_limit_size` is used to limit the buffer queue size but it respects the `retry_limit`, which means that even if you specify an large queue size, the chunk will still be dropped after first retry (if failed).
So for your question:

so there is not in general a mechanism/configuration in fluentbit to specify the maximum retention queue size of messages yet to be forwarded
-You can configure it by setting `storage.total_limit_size` but you also need to set `retry_limit false` in your output plugin.

Why a delay for back pressure is treated differently from a delay for connection issues, in this case?
- No. Fluent Bit handles both of them by using either memory (default) or file system. You need to configure `storage.type filesystem` in your output plugin in order to use the disk to buffer chunks. 

More details can be found here: https://docs.fluentbit.io/manual/administration/buffering-and-storage

**Comment by RiccardoManfrin** [comment]
Thanks for the explanation! Very helpful 
Last question: Is the retry period equivalent to the `[SERVICE]` `Flush` value in seconds?

**Comment by JeffLuoo** [comment]
Nope. Retry period is not equivalent to the `Flush` value in SERVICE section. Example for `Flush 5`: Fluent Bit will flush data to the output plugin each 5 seconds which means that during the 5s, output plugin will be waiting for the logs from the input plugin. And the `retry` period is decided by the Fluent Bit engine and there is an algorithm to decide when will the next retry happen. The behaviour is to use exponential backoff with jitter to decide the next retry time.

**Comment by RiccardoManfrin** [comment]
Super clear thanks
