### ISSUE TITLE
Multiple Regex entries for grep filter not working

### ISSUE THREAD

**Issue by cokegen** [fluent/fluent-bit#3259]
## Bug Report

**Describe the bug**
More than one `Regex` entry being specified for the grep filter do not work. Multiple `Exclude` entries on the contrary DO work just fine if you give it a try.

**To Reproduce**
```
[SERVICE]
    Flush 1
    Daemon Off
    Log_Level debug
    Parsers_File parsers.conf
[INPUT]
    Name dummy
    Tag kube.*
    Rate 1
    Dummy {"app":"apple-ftest-1","date":"Tue Mar 16 02:58:19 UTC 2021"}
[FILTER]
    Name grep
    match kube.*
    Regex app /^apple-ftest-1$/
    Regex date /^Mon$/
[OUTPUT]
    name stdout
    match *
```
```
[2021/03/19 22:08:10] [ info] [sp] stream processor started
[2021/03/19 22:08:12] [debug] [task] created task=0x7fc23642f3a0 id=0 OK
[0] kube.*: [1616191691.266293762, {"app"=>"apple-ftest-1", "date"=>"Tue Mar 16 02:58:19 UTC 2021"}]
```
- Steps to reproduce the problem:
Launch fluent-bit with the provided config and see result

**Expected behavior**
The entry should not make it to stdout, since the second Regex entry should prevent it.

**Comment by atheriel** [comment]
This issue is actually more extensive:

* The order of `Regex` entries matters, but the order of `Exclude` entries does not.
* Mixing `Regex` and `Exclude` entries will result in the `Exclude` entries being ignored if *any* of the `Regex` entries match.

In practice we've gotten around this by having multiple `grep` filters, but that seems silly given that the plugin explicitly supports many entries.

**Comment by atheriel** [comment]
Still an active issue.

**Comment by atheriel** [comment]
Still an active issue.

**Comment by atheriel** [comment]
Still an active issue.
