### ISSUE TITLE
Elasticsearch Output: check 'error' flag from HTTP response

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#329]
raised by @fusakla on our Slack channel:

Hi, just wanted to ask. Fluent-bit doesn't support ACKing from elasticsearch about message ingestion right?
From code it looks like it only checks HTTP status of elastic response but when error occurs elastic returns status 200 but in JSON response is `"errors":true`

So i found these error only with `tcpflow` on elastic host. Fluent-bit is writing status 200 and everything is looking fine but no messages are ingested in elastic.

example of elasticsearch response from tcpflow:

```TTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 1283

{"took":68,"errors":true,"items":[{"index":{"_index":"logstash-2017.07.11","_type":"fluentd","_id":"AV0x15fvh7ClmEbhyzH_","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to pars
e","caused_by":{"type":"illegal_state_exception","reason":"Mixing up field types: class org.elasticsearch.index.mapper.KeywordFieldMapper$KeywordFieldType != class org.elasticsearch.index.mapper.TextFie
ldMapper$TextFieldType on field unparsed"}}}},{"index":{"_index":"logstash-2017.07.11","_type":"fluentd","_id":"AV0x15fvh7ClmEbhyzIA","status":400,"error":{"type":"mapper_parsing_exception","reason":"fa
iled to parse","caused_by":{"type":"illegal_state_exception","reason":"Mixing up field types: class org.elasticsearch.index.mapper.KeywordFieldMapper$KeywordFieldType != class org.elasticsearch.index.ma
pper.TextFieldMapper$TextFieldType on field unparsed"}}}},{"index":{"_index":"logstash-2017.07.11","_type":"fluentd","_id":"AV0x15fvh7ClmEbhyzIB","status":400,"error":{"type":"mapper_parsing_exception",
"reason":"failed to parse","caused_by":{"type":"illegal_state_exception","reason":"Mixing up field types: class org.elasticsearch.index.mapper.KeywordFieldMapper$KeywordFieldType != class org.elasticsea
rch.index.mapper.TextFieldMapper$TextFieldType on field unparsed"}}}}]}```

**Comment by edsiper** [comment]
I've pushed a patch into git master and 0.11 branches to address the issue.

**Comment by FUSAKLA** [comment]
great i see the commit only in `0.11` branch but it looks good. I wanted to make pullrequest but I'm not C developer and result would be way way worse:)

nice feature would be if function `elasticsearch_error_check` return also the error type from response.
problem is as i see that it returns error for each message in chunk so the types can differ per response.

but at least write out the whole json to log on if there is an error on debug level because as i said..
There is no reasonable way to debug these errors otherwise. (tcpflow is in my opinion pretty extreme tool)

this is just nice to have i leave it to your consideration

possible problem i see is the retry.
Now i found the `retry_limit` option which probably solves my concern (that bluent-bit would be stuck on retrying request which would never succeed)  but lot of these errors from elasticsearch which can be detected from the request body are not solvable with retry i think.

Maybe use of retry on real HTTP error only would be better.
And in case of the error from request body just log it.

These useless retries could considerably slow down the pipeline

**Comment by edsiper** [comment]
The current implementation when it finds an error, prints out the JSON payload coming from Elasticsearch so the user can get an idea about what's going on.

Additionally (today), I've added the option to read the response with verbose mode for cases where records are ingested properly.

Now about retries, we cannot implement/interpret every error response as this could mean to implement all use cases where elastic would fail (and this will means to do the same for all output plugins that uses a different backend system). It's better to provide the user the error message and let him try to fix it; note that sometimes the error can be only on elasticsearch side.

**Comment by FUSAKLA** [comment]
Yes sorry I must have misunderstood the code.

This is solution I had in mind also.
Great I'm looking forward to testing it.

Thanks

**Comment by edsiper** [comment]
Fixed.
