### ISSUE TITLE
Can I modify tag by Parser ?

### ISSUE THREAD

**Issue by VinkDong** [fluent/fluent-bit#330]
Hi, Can I modify tag by Parser?  I want to send journald logs (use 0.12 dev version) to kubernetes plug, it seems like use tag name to send Kube API,  How can I do?

**Comment by edsiper** [comment]
Altering the tag is not a supported feature at the moment (it will be shortly). What I suggest is that you use one wildcard in the Tag config so it will be auto-populated with the Systemd Unit name.

**Comment by VinkDong** [comment]
Yeah, I see it, can we make kubernetes filter plug work with systemd input plugs？

**Comment by edsiper** [comment]
Yes, that feature in the filter will be available shortly, it will be part of 0.12 release. I will let you know once is ready (help to test it is welcome)

**Comment by edsiper** [comment]
@VinkDong 

I've pushed the required changes for filter_kubernetes to interpret logs coming from Systemd. The changes are in GIT master (v0.12) and the Docker Image is being built (fluent/fluent-bit:0.12-dev). 

I did some basic tests emulating Systemd input since I don't have a K8s cluster with Systemd at the moment. If you can give it a try and send some feedback will be appreciated.

**Comment by VinkDong** [comment]
Ok, I will give it a try as soon

**Comment by edsiper** [comment]
@VinkDong did you manage to test it ?

**Comment by edsiper** [comment]
Closing this as Fixed (systemd input plugin and filter_kubernetes are operational)
