### ISSUE TITLE
Question: Any plans for alternative image registry?

### ISSUE THREAD

**Issue by poksiala** [fluent/fluent-bit#3432]
**Is your feature request related to a problem? Please describe.**
Systems pulling from Docker Hub might run into rate limits. In your helm chart the default is "pullPolicy=Always" which may augment this issue.

**Describe the solution you'd like**
A mirror for for Fluent images. For example quay.io.

**Describe alternatives you've considered**
Hosting my own mirror, but would not like to do it.

**Additional context**
In larger cluster a crash looping fluent-bit daemonset might in a short span of time issue tens of requests towards Docker Hubs "rate limits of 100 container image requests per six hours".
I tried to search old issues for duplicates in this repo and fluent/fluentd, but could not find any.

**Comment by gabegorelick** [comment]
Publishing images to an additional registry is definitely a must now that Dockerhub severely rate limits image pulls. 

Github packages is something I've seen used a lot by projects transitioning from Dockerhub since it's free for open source repos. It should hopefully be fairly straightforward to publish from the existing GitHub Actions publish workflow.

AWS's ECR also has a free public registry. It has quite a [few](https://gallery.ecr.aws/x1v8g9p0/fluent/fluent-bit) [fluent-bit](https://gallery.ecr.aws/n1k6e5t7/fluent/fluent-bit) [images](https://gallery.ecr.aws/metaplay/fluent/fluent-bit) [of](https://gallery.ecr.aws/metaplay-dev/fluent/fluent-bit) [unknown](https://gallery.ecr.aws/j8c2d7j7/fluent-bit) [provenance](https://gallery.ecr.aws/p3p7n3v4/fluent/fluent-bit), so publishing official images there would be nice to replace all those. https://gallery.ecr.aws/bitnami/fluent-bit looks to be a decent image, but it uses Bitnami's custom base image instead of Fluent Bit's distroless image. There's also https://gallery.ecr.aws/aws-observability/aws-for-fluent-bit, but that also diverges a fair amount from the vanilla fluent-bit images.

**Comment by gabegorelick** [comment]
Still an issue. AFAIK only Dockerhub is pushed to in the release workflow: https://github.com/fluent/fluent-bit/blob/ebe3df398dd8fcf349d62e8235315b7bcd2e05bc/.github/workflows/publish-release.yaml#L72

**Comment by edsiper** [comment]
FYI: The Fluentd project (fluent organization) is under the Docker OSS program, we don't have rate limits.

Currently, we have more than 2M  pulls per day without any issue. 

Closing this ticket since this is no longer a problem, thanks to everyone for raising the concern.

**Comment by gabegorelick** [comment]
Thanks for the confirmation.

> Docker OSS program

For anyone wondering about this, it refers to https://www.docker.com/blog/expanded-support-for-open-source-software-projects:

> To support the open source community, Docker has created a special program for Open Source projects to get continued free access and freedom from restrictions for their communities and their users. For the approved, non-commercial, open source projects, we are thrilled to announce that we will suspend data pull rate restrictions, where no egress restrictions will apply to any Docker users pulling images from the approved OSS namespaces.

So users should not be subjected to the 100 pull per 6 hr limit, or any similar limits.

**Comment by patrick-stephens** [comment]
All images are also mirrored under ghcr.io now as well: `ghcr.io/fluent/fluent-bit`.
