### ISSUE TITLE
Will fluent-bit break data in between to keep track of 2MB chunk size for tail plugin

### ISSUE THREAD

**Issue by chillaxd** [fluent/fluent-bit#345]
Hi @edsiper 

Fluent-bit tail plugin internally chunks incoming data on 2MB size, I read it somewhere in some forum. Please correct me if I am wrong. And if it is like that will it be possible to variablize the value based on requirement?

My query is:
 Will fluent-bit take care of "not-to-break" data in between to keep track of that 2MB size? 

I have tested with couple of data, and I have observed if for one character it cross the size limit, fluent-bit will put that line into the next chunk. 
I just want to clarify whether that is the expected behaviour from fluent-bit in all cases?

**Comment by edsiper** [comment]
@chillaxd 

1. it is like that will it be possible to variablize the value based on requirement?

That's a hard coded value. If you have a special use case where you need to change this let me know to understand the problem you are trying to fix.

2. Will fluent-bit take care of "not-to-break" data in between to keep track of that 2MB size?

Data will always be split internally in chunks and that chunk is immutable until it reach the output plugin who likely will generate a new modified copy (e.g: elasticsearch requires special JSON format instead of Fluent Bit chunk data representation).

In general when the input plugins "insert" data into the engine, the engine will create it own chunks.

**Comment by edsiper** [comment]
Closing this ticket for now.
