### ISSUE TITLE
Does it can support multiple parser for single input(forward)? 

### ISSUE THREAD

**Issue by keyolk** [fluent/fluent-bit#348]
Lets say I have multiple container running on docker,
All those send logs to fluent-bit using fluentd logging driver.

I may can use Forward INPUT to process them.
It seems that forward input not supports parser, is right ? 
And ... other input also only one parser can be used for.

Is there a way to attach variety parsers for a input ?

**Comment by edsiper** [comment]
@keyolk 

in Fluent Bit 0.12 the way to accomplish this it's using the new [Filter Parser](http://fluentbit.io/documentation/0.12/filter/parser.html). 

You can add many as you require and do normal tag/match rules to apply them.

**Comment by vikasmishra17** [comment]
Hi,

Fluent-bit is not picking the picking the messages that the server is receiving through tcpdump, Instead of that Fluent-bit is sending the system syslogs to the server itself.

My configuration

[INPUT]
Name syslog
mode tcp
Listen 0.0.0.0
Port 514
tag syslog.tcp
Parser syslog-modified

[FILTER]
Name parser
Match syslog.*
Parser syslog-modified
Preserve_Key On
Reserve_Data On
Key_Name log

[OUTPUT]
name stdout
match *
& We are not getting any thing in the logs too
