### ISSUE TITLE
Support AWS profile credential_process

### ISSUE THREAD

**Issue by rittneje** [fluent/fluent-bit#3621]
As best I can tell, currently Fluent Bit only supports AWS profiles that directly specify `aws_access_key_id`, `aws_secret_access_key`, and `aws_session_token` in the ~/.aws/credentials file. https://github.com/fluent/fluent-bit/blob/master/src/aws/flb_aws_credentials_profile.c

Please add support for specifying `credential_process` in the ~/.aws/config file. https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

Our use case is we have a single process running that fetches role credentials from IoT Core. https://aws.amazon.com/blogs/security/how-to-eliminate-the-need-for-hardcoded-aws-credentials-in-devices-by-using-the-aws-iot-credentials-provider/ So using a credential process makes the most sense.

It would be best if this also abided by the `AWS_CONFIG_FILE` environment variable if it is set.

**Comment by rittneje** [comment]
cc @PettitWesley

**Comment by PettitWesley** [comment]
I've added this on the AWS backlog, but with many higher priority requests outstanding right now, its unlikely we will get to this soon.

So you must come up with an alternate plan:
1. Are you interested in contributing support for this feature? It seems like basically fluent bit would need to exec some provided command and process the output to get the credentials. The expected output for credential processes is the same as we get from IMDS for creds, so code already exists to parse the response. I'm happy to provide pointers on which pieces in the code to change if you choose this route. 
2. Find some alternative. Could you build some process around your credential process which makes it automatically get creds and write them to the ~/.aws/credentials file? If you did this, I could fairly simply add an option to the code in Fluent Bit to auto-refresh from the cred file periodically, so that it would uptake updates to that file. Would this workaround be feasible for you?

**Comment by rittneje** [comment]
I'm not very familiar with C, but I'm willing to give implementing it a whirl. Any pointers you can provide would be much appreciated.

**Comment by megaloni** [comment]
@PettitWesley - definitely interested in adding support for this, but at a bare minimum your second option would be an acceptable fallback option.

**Comment by PettitWesley** [comment]
@megaloni @rittneje The code for processing AWS shared cred file is here: https://github.com/fluent/fluent-bit/blob/master/src/aws/flb_aws_credentials_profile.c

Unfortunately its not my best code. 

But you would basically need to update the parsing logic to support finding a new property name in the file: https://github.com/fluent/fluent-bit/blob/master/src/aws/flb_aws_credentials_profile.c#L35

And then I think you just run the provided command, using the exec syscall. 

This function can parse the cred response from the credential process I think, since its the same format used by IMDS: https://github.com/fluent/fluent-bit/blob/master/src/aws/flb_aws_credentials_http.c#L391

**Comment by rittneje** [comment]
@PettitWesley In the code I see some references to FluentBit being single-threaded with some async event loop construct. Do we need to care about that in the context of exec'ing the credential process and waiting for its response? If so, how do we do that?

**Comment by PettitWesley** [comment]
@rittneje I think the exec call needs to be made synchronously and fluent bit needs to wait for the response. I don't think we need to worry about the event loop, trying to integrate with that to do something async is probably overkill. The credential_process should respond with creds fairly quickly?

**Comment by rittneje** [comment]
> The credential_process should respond with creds fairly quickly?

Ultimately that will depend on what the credential_process is. In our case I would expect it to respond in a few seconds at most, at least under normal circumstances. For what it's worth, the Go SDK uses a 60 second timeout for this by default.

https://github.com/aws/aws-sdk-go/blob/56a221fbe3bd48a9808a4d2f2667b6a3677e5d76/aws/credentials/processcreds/provider.go#L148-L149

**Comment by rittneje** [comment]
@PettitWesley Also, I am not very familiar with Windows development. Would it be acceptable for `credential_process` support to initially be Linux-only (or at least Unix-only)?

**Comment by rittneje** [comment]
@PettitWesley I decided to conditionally compile credential_process support for Linux only to reduce the scope of work, between implementation and testing. I hope to raise the PR soon.

**Comment by PettitWesley** [comment]
@rittneje Awesome! And yeah, I agree Linux/Unix only is perfectly acceptable. A lot of users will be pleased. Windows can be added later.
