### ISSUE TITLE
[http_client] cannot increase buffer on k8s

### ISSUE THREAD

**Issue by upstream-dmahlberg** [fluent/fluent-bit#3918]
## Bug Report

**Describe the bug**
We occasionally get warnings like this thrown by fluent-bit 1.8.2:
```
[ warn] [http_client] cannot increase buffer: current=512000 requested=544768 max=512000
```

Note that we do not use kinesis firehose.

**To Reproduce**
- Indeterminable. It does not seem to depend on the number of pods or the general load of the cluster, and no source of this could be determined.

**Expected behavior**
- No warnings are thrown.

**Your Environment**

* Version used: 1.8.2 (installed via official helm chart)
* Configuration:
```
service: |
      [SERVICE]
          Flush 5
          Daemon Off
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
          storage.path /var/log/fluentbit-buffer/
          storage.metrics On
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          Exclude_Path /var/log/containers/calico-node*.log
          storage.type  filesystem
          Parser my-parser
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          Annotations Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host <redacted>
          Logstash_Format On
          Retry_Limit 10
          Trace_Error On
          Replace_Dots On
          Suppress_Type_Name On
    customParsers: |
      [PARSER]
          Name my-parser
          Format regex
          Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.19.11
* Server type and version: MS AKS cluster
* Filters and plugins: tail, kubernetes, es

**Additional context**
I'm starting to think the fluent-bit respone buffer might be a little too small for some of the responses elasticsearch sends, especially when an error occurs - elasticsearch's JSON responses can get quite large...

**Comment by yz271544** [comment]
I have the same problem, how can I solve it?

**Comment by agup006** [comment]
You may be able to try http_buffer_size parameter within the elasticsearch output

**Comment by upstream-dmahlberg** [comment]
I cannot reproduce this error anymore since I had to revert to 1.7.9 due to another issue in 1.8.2 regarding filesystem buffered chunks. I will reinvestigate when I update to 1.8 again.

**Comment by rifqifatih** [comment]
Same issue installed with helm chart `0.16.2` -> fluent bit `1.8.3`

**Comment by mjiderhamn** [comment]
I'm running into the same issue. I too was able to work around the issue by downgrading to 1.7.9. I believe this issue needs to be reopened.

@agup006 , adding
```
[OUTPUT]
  Name es
 ...
  http_buffer_size 65536
```
results in
```
[2022/01/28 14:58:25] [error] [config] es: unknown configuration property 'Http_Buffer_Size'. The following properties are allowed: index, type, suppress_type_name, http_user, http_passwd, cloud_id, cloud_auth, aws_auth, aws_region, aws_sts_endpoint, aws_role_arn, aws_external_id, logstash_format, logstash_prefix, logstash_prefix_key, logstash_dateformat, time_key, time_key_format, time_key_nanos, include_tag_key, tag_key, buffer_size, path, pipeline, generate_id, id_key, replace_dots, current_time_index, trace_output, and trace_error.
```

**Comment by brsolomon-deloitte** [comment]
This should be reopened - still persists on fluent-bit helm chart 0.19.20 (app version 1.8.13).

I don't believe that OUTPUT.Buffer_Size is the culprit here.

From https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch, Elasticsearch output Buffer_Size is 

> the buffer size used to read the response from the Elasticsearch HTTP service. 

It seems apparent the buffer in question is a different one.

For example, we have set `Buffer_Size 64KB` for Elasticsearch output, re-deployed and still see:

> [2022/03/09 17:49:31] [ warn] [http_client] cannot increase buffer: current=32000 requested=64768 max=32000

all over the logs.

Notice that `max=32000` is displayed here which indicates it's not influenced by the Elasticsearch output Buffer_Size at all...

**Comment by gabileibo** [comment]
@brsolomon-deloitte same for us. These logs are also clogging our whole log pipeline.

**Comment by gabileibo** [comment]
@brsolomon-deloitte Figured it out, `Buffer_Size 64KB` should be set in the kubernetes `[Filter]`. This resolved the issue for me!

**Comment by brsolomon-deloitte** [comment]
@gabileibo - yep! We noticed that and also that `INPUT.tail` accepts both a `Buffer_Chunk_Size` and `Buffer_Max_Size`. We ended up with:

```
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On
          Buffer_Chunk_Size 64KB
          Buffer_Max_Size 128KB
      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
          Buffer_Size 256KB
```

Also found the upstream [`values.yaml`](https://github.com/fluent/helm-charts/blob/f74513de05d969fc3db3517cadb53163b1c6772c/charts/fluent-bit/values.yaml#L268) helpful.

Not ideal since it involves some code duplication, but it makes the warnings & errors go bye-bye.

**Comment by brsolomon-deloitte** [comment]
(The dead giveaway was that `Buffer_Chunk_Size` and `Buffer_Max_Size` for `INPUT.tail` both default to 32k, and that was the value that was showing up as the 'cannot exceed' threshold in the logs.

**Comment by trallnag** [comment]
Consider setting `buffer_size` to `0`

**Comment by sdickhoven** [comment]
the `http_client` is used in a few different places by various fluentbit components (e.g. when shipping logs to stackdriver/splunk/newrelic/etc. or when interrogating the kubernetes api).

only a few of the modules that use `http_client` override the default buffer size ([of 4k](https://github.com/fluent/fluent-bit/blob/1fa0e94a09e4155f8a6d8a0efe36a5668cdc074e/include/fluent-bit/flb_http_client.h#L28)):

https://github.com/fluent/fluent-bit/search?q=flb_http_buffer_size

one of them is the `filter_kubernetes` module:

https://github.com/fluent/fluent-bit/blob/1fa0e94a09e4155f8a6d8a0efe36a5668cdc074e/plugins/filter_kubernetes/kube_meta.c#L387

in our case the problem was that we have a fairly large kubernetes cluster. so when retrieving pod metadata from the kubernetes api, fluentbit ran out of buffer space.

the solution was:

```
[FILTER]
    Name         kubernetes
    Buffer_Size  512k   # was 32k
    ...
```

(`512k` is probably a bit overkill but it'll allow us to grow the cluster without ever having to worry about this again)

**Comment by sdickhoven** [comment]
on a related note i'd like to give kudos to the maintainers/contributors of fluentbit! 💪 

i found the fluentbit source code to be very well organized and therefore very easy to understand.

it took me no more than half an hour to track down what our problem was by looking through the source code... and i'm an absolute n00b when it comes to fluentbit.

**Comment by antoniocascais** [comment]
Going to dig this up because I found this issue while looking into something similar.

In 2 of our filters, we set `Buffer_Size` to 2mb:
```
Buffer_Size 2MB
```

But looking at the logs of one specific fluent-bit instance, we see the error message:
```
cannot increase buffer: current=2000000 requested=2032768 max=2000000
```

This looks weird because it seems like fluent-bit is not converting MB to B properly, so I tried to change Buffer_Size:
```
Buffer_Size 2000000B
```

Now the error is gone.
Did I just hit a weird edge-case bug? Or am I doing something wrong? :thinking:

**Comment by binhoul** [comment]
> 

Indeed. the answer is in the doc
https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/unit-sizes

**Comment by binhoul** [comment]
> Going to dig this up because I found this issue while looking into something similar.
> 
> In 2 of our filters, we set `Buffer_Size` to 2mb:
> 
> ```
> Buffer_Size 2MB
> ```
> 
> But looking at the logs of one specific fluent-bit instance, we see the error message:
> 
> ```
> cannot increase buffer: current=2000000 requested=2032768 max=2000000
> ```
> 
> This looks weird because it seems like fluent-bit is not converting MB to B properly, so I tried to change Buffer_Size:
> 
> ```
> Buffer_Size 2000000B
> ```
> 
> Now the error is gone. Did I just hit a weird edge-case bug? Or am I doing something wrong? 🤔

Indeed. the answer is in the doc
https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/unit-sizes

**Comment by antoniocascais** [comment]
I don't understand. Isn't `2MB` valid?

Looks correct to me:
![image](https://user-images.githubusercontent.com/28305187/201051383-2f7f7b88-d857-417d-884d-c963f95fc78b.png)

**Comment by dko-slapdash** [comment]
BTW, ES really send that large output sometimes. E.g. when it's overloaded:

<img width="2016" alt="CleanShot 2023-02-02 at 23 44 45@2x" src="https://user-images.githubusercontent.com/46383452/216542139-a668db0d-1263-4fca-a43a-eccd25cc2ef9.png">

**Comment by mohijeet-changejar** [comment]
For me it was HTTP BUFFER_SIZE of es plugin as i changed it to 2MB from 512kb (default) now that error is gone which was making some retry mechanism, now i am unable to understand how does that thing is causing retry mechanism since this values is just to make sure http response is available for debug purpose correct?

**Comment by LHozzan** [comment]
Hi there.
Just a five cents from me: It will be good, if FluentBit just not log only
```
[ warn] [http_client] cannot increase buffer:...
```
but log source plugin as well (e.g. for ES):
```
[ warn] [es.http_client] cannot increase buffer:...
```
or for Kubernetes:
```
[ warn] [kube.http_client] cannot increase buffer:...
```
This information will have higher value for staff to track down, which plugin is affected by the resource limitation.

Yop, we are facing same problem, but our source of problem is Kubernetes plugin. It seems, that Kubernetes API return too big payload. Even, if we want to log only labels, annotation we dont need in our case.

BR!

**Comment by StianOvrevage** [comment]
If you use the [fluent-operator helm chart](https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/values.yaml) with the default `kubernetes` setup you can fix the issue with this helm value:

```
fluentbit:
  filter:
    kubernetes:
      bufferSize: 2MB
```

**Comment by danmoji** [comment]
my example output that stopped the errors, 
setup  buffer_size to false:

 [OUTPUT]
        Name                es
        Match               systemd
        Host                ${ELASTIC_IP}
        Port                9200
        HTTP_User           fluent-bit-robot
        HTTP_Passwd         ${ELASTIC_PASSWD}
        Index               test-systemd
        Retry_Limit         False
        tls                 On
        tls.verify          Off
        Trace_Error         On
        Replace_Dots        On
        suppress_type_name  On
        buffer_size         false

**Comment by caiotaavares** [comment]
For me the fix was:

```
    [FILTER]
        Name kubernetes
        ...
        Buffer_Size       2MB
```

```
    [OUTPUT]
        Name              loki
        ...
        Buffer_Size       2MB
        ...
```
