### ISSUE TITLE
Root cert for packages fluentbit io is expired 

### ISSUE THREAD

**Issue by cork** [fluent/fluent-bit#4119]
I've checked the CentOS, ​Ubuntu, ​Debian, Raspbian and Yocto repos and they are all reporting 403 forbidden. Taken from fluent/fluent-bit-packaging#17 it looks to have been like this since mars.

Is linux packaging still supported and if so why haven't anything happened around this?

**Comment by agup006** [comment]
Hey @cork not sure what you mean, the latest packages are all available via repo. We are seeing a couple hundred thousand downloads a day through these

We don't have URLs to access, only the latest via rpm/deb repos.

**Comment by cork** [comment]
```
https://packages.fluentbit.io/debian/buster/ => 403
https://packages.fluentbit.io/ubuntu/focal => 403
https://packages.fluentbit.io/centos/ => 403
https://packages.fluentbit.io/amazonlinux/2/ => 403
```

**Comment by cork** [comment]
So if you want to install the package you can't use the repos as no file is accessible from them.

**Comment by DanielAGW** [comment]
Same thing for me, I'm getting The repository 'http://packages.fluentbit.io/ubuntu/focal focal Release' no longer has a Release file.
The entire http://packages.fluentbit.io returns 403 forbidden for any endpoint

**Comment by HoyluBert** [comment]
I have a similar experience. I think the issue is with the certification path in use by the server serving the packages. 
Output from apt update:

```bash
Err:13 https://packages.fluentbit.io/ubuntu/bionic bionic Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification.
```

My guess is, that this is caused by the expiration of the Let's Encrypt intermediate and root certificates, which happened the last 2 days.

**Comment by DanielAGW** [comment]
@edsiper Hi there, the issue is still there. Packages return 403 error - https://packages.fluentbit.io/ubuntu/focal 
It's the same issue as this one https://github.com/fluent/fluent-bit/issues/4181
It's still not possible to install the package in Ubuntu Focal and probably many others as well. I strongly believe this issue should be reopened and fixed - even though it's not directly related with the codebase itself.
![image](https://user-images.githubusercontent.com/12436808/142777452-ddd5ecba-959e-4171-92c1-d20edb5aee89.png)

**Comment by edsiper** [comment]
403 error is HTTP Forbidden error, the repository is not browsable. It has nothing to do with certificates. closing.
