### ISSUE TITLE
no log shows several  minutes after startup 

### ISSUE THREAD

**Issue by yangvipguang** [fluent/fluent-bit#4308]
Version: 1.8.9

configuration Fluent bit
![image](https://user-images.githubusercontent.com/11416887/141132673-755da8ee-99b9-4203-b6ea-006122f2cd65.png)

everything looks like well. Fluent bit log has no errors. But after startup  for several minutes， then  no logs  show like below.
![image](https://user-images.githubusercontent.com/11416887/141132333-7ff46fc8-1f47-4c48-80ce-aecd4f8cbbc6.png)

![image](https://user-images.githubusercontent.com/11416887/141132423-b39fc676-5785-4ca7-bcda-609fecc49c62.png)

**Comment by leonardo-albertovich** [comment]
Maybe setting the log level to debug could help determine what exactly is fluent-bit doing in this case?

**Comment by yangvipguang** [comment]
@leonardo-albertovich   But the  debug log looks like no errors.  
![image](https://user-images.githubusercontent.com/11416887/141225437-7a5b3f11-e054-40ac-b718-62d59d489c7b.png)

There are only logs at the moment of startup, there will be no logs after a few seconds。
![image](https://user-images.githubusercontent.com/11416887/141225703-d2831493-2a17-4cb1-ba89-0339b04b3943.png)

**Comment by yangvipguang** [comment]
![image](https://user-images.githubusercontent.com/11416887/141228302-14ac2fc6-1895-4747-8c3a-d6660bc758c2.png)
But  the  log file always exists. 
![image](https://user-images.githubusercontent.com/11416887/141228376-bb81eedd-74e0-49dc-89d1-6ae79e9b8dcc.png)

**Comment by leonardo-albertovich** [comment]
Would you be able to send me a full copy of the log? You can do it here or in private in the fluent slack server.

I see that at 10:16:56 the files are skipped in a `tail_scan_path` call which is executed in fixed intervals to detect new files. In theory that behavior is correct and those files should already be in the tail list but more context is required to understand the subtleties of this case.

A complete dump of your configuration would also help as well as some information about your log rotation mechanism, I suspect what happened in your last message could have been that the file was deleted and recreated as an empty file (instead of being truncated) which is why fluent-bit detected it that way (next time it happens run `ls -lah` and stat so you get proper information about the file (creation/modification/access times) and its size).
