### ISSUE TITLE
Support floats for Time_Key field in json parser

### ISSUE THREAD

**Issue by eugene-katsevman** [fluent/fluent-bit#4316]
We use json parser with custom float timestamp field. Nowhere in documentation I could find that floats are not supported

I would like to alter the code below so float data would be used instead of being thrown out the window

https://github.com/fluent/fluent-bit/blob/0111149ce44b28cb6b5af710009bd3a2c14d8eb9/src/flb_parser_json.c#L178

Also, it would be great to shed some light on this issue in the manuals.

For not we started to duplicate timestamp in a separate field as a string, but for that to work we need to redeploy everything. So it will be okay eventually.

**Additional context**
subsec precision is great then one has huge amount of logs per second

**Comment by BertelBB** [comment]
The issue is not just with floating points, but all other data types except strings.
I would also like to be able to parse floats and bools. There are some cases where I want to make a decision based on a boolean field.

Currently the only way to do that is to first convert the field into a string and then parse it. The documentation is very lacking on this crucial detail; `regular expression only work if the field being inspected is of type string`

However, I wonder why fluent-bit doesn't just cast fields to string before applying a regular expression to them? @edsiper 
It could even be optional to cast by adding a property to the **parser** filter
```
# custom_parser.conf
[PARSER]
    name        float-time
    format      regex
    regex       ^(?<time>.*)$
    time_key    time
    time_keep   off
    time_format %s.%L

# fluent-bit.conf
[FILTER]
    name           parser
    match          floating.point
    parser         float-time
    key_name       ts
    cast_to_string on
```

I have a workaround for this issue in case anyone is looking for one

**general.lua**
```lua
function ts_to_string(tag, ts, record)
  if (record["ts"] == nil) then
    return 0, ts, record
  end
  
  local r = record
  r["ts"] = tostring(record["ts"])
  return 1, ts, r
end
```

**fluent-bit.conf**
```
[FILTER]
    name   lua
    match  <your tag>
    script /fluent-bit/scripts/general.lua
    call   ts_to_string
    
[FILTER]
    name         parser
    match        <your tag>
    parser       float-time
    key_name     ts
    reserve_data on
```
