### ISSUE TITLE
Key_value_does_not_match is true if the key does not exist

### ISSUE THREAD

**Issue by jefferbrecht** [fluent/fluent-bit#4319]
## Bug Report

**Describe the bug**
When using `Condition Key_value_does_not_match` or `Condition Key_value_does_not_equal` in a `modify` filter, it will return `true` even if the key does not exist.

**To Reproduce**
- config:
```
[FILTER]
        Condition Key_value_does_not_equal foo test
        Match     *
        Name      modify
        Add       a b
```

- Steps to reproduce the problem:
Run Fluent Bit containing the above config and write this to the log file: `{"abc": "def"}`

Fluent Bit outputs: `[0] log: [1636743396.156716335, {"abc"=>"def", "a"=>"b"}]`

**Expected behavior**
Since the `foo` key does not exist, the `"a"=>"b"` record should not be added. From the `modify` [docs](https://docs.fluentbit.io/manual/pipeline/filters/modify): "Key_value_does_not_match (...) Is true if key KEY exists and its value does not match VALUE"

**Your Environment**
* Version used: v1.8.7

Workaround: the desired behaviour can be achieved by adding `Condition Key_exists foo` to the filter.

**Comment by nokute78** [comment]
Thank you for reporting.

I sent a patch https://github.com/fluent/fluent-bit/pull/4321.

**Comment by jefferbrecht** [comment]
Thanks, I can confirm this works as expected in 1.8.11.

**Comment by ggermis** [comment]
It took me a while to find out why our logs weren't working anymore due to this change.

We use the `Key_value_does_not_equal` condition to check if some logs are audit logs and then add a tag before sending them off to fluentd which uses the tag to put the log in the correct elasticsearch index. 

It would have been nice if this sort of change could be incorporated into the [upgrade notes](https://docs.fluentbit.io/manual/installation/upgrade-notes) since it breaks existing configurations..

Our configuration (working until `v1.8.10`):

```
      [FILTER]
          Name modify
          Match kube.*
          Condition Key_value_equals kubernetes.namespace int
          Condition Key_value_does_not_equal logtype AUDIT
          Add fluentd.destination application-logs
``` 

Only our audit information is logged with a `logtype` key. The normal application logs don't have this key

So in versions prior to `1.8.10` this would simply add the `fluentd.destination` key to the logs and have fluentd put them in the correct index, but as of `1.8.10` the `fluentd.destination` tag was not added anymore causing our logs to go "missing"...

**Comment by nokute78** [comment]
@ggermis Thank you for reporting.

According to the documentation,  a description of `Key_value_does_not_equal` is  `Is true if KEY exists and its value is not VALUE`.
In my understanding, it should be false if the key doesn't exist.
FYI: The description is same in the v1.7 documentation.
https://docs.fluentbit.io/manual/v/1.7/pipeline/filters/modify

As you know, there was inconsistency between the implementation and the documentation.
My patch https://github.com/fluent/fluent-bit/pull/4321 is to fix it.

It fixed the issue and also caused breaking change.
Sorry for it.
