### ISSUE TITLE
Fluent bit stops sending logs to any other output when any of the outputs goes offline

### ISSUE THREAD

**Issue by merveyilmaz-netrd** [fluent/fluent-bit#4373]
## Bug Report

**Describe the bug**
Hi all, i am working with tail input and 3 ouputs(Kafka, Elastic Search and splunk). I am testing for our production enviroment. I am tailing log files and sending logs to Kafka, Elastic Search and Splunk. I closed the splunk service and 10 minutes later fluentbit  -stopped sending logs to other outputs too. (Kafka and Elastic) Why Fluentbit stop sending logs when any of the outputs is offline?

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**
 continue to send logs to kafka and elastic search

**Screenshots**

**Your Environment**

* Version used: 1.8.8
* Configuration: here is my configuration file:
[SERVICE]
    Flush     5
    Daemon    off
    Log_Level debug
    HTTP_Server on
    HTTP_Listen 0.0.0.0
    HTTP_Port 2020
    storage.path /opt/flb-storage
    storage.sync normal
    storage.backlog.mem_limit 200MB

[INPUT]
    Name  tail
    Path  /opt/flb/*
    Tag   test
    storage.type filesystem
    Mem_Buf_Limit 500MB

[OUTPUT]
    Name  es
    Match test
    Host  XX.XXX.XXX.XXX
    Port  9200
    Index my_index
    Retry_Limit False

[OUTPUT]
    Name        kafka
    Match       test
    Brokers      XX.XXX.XXX.XXX:9092
    Topics      logForwarding
    rdkafka.message.timeout.ms 0
    Retry_Limit False

[OUTPUT]
    Name        splunk
    Match       test
    Host         XX.XXX.XXX.XXX
    Port        8088
    splunk_token randomrandomrandom
    splunk_send_raw on
    TLS         On
    TLS.Verify  Off
    Retry_Limit false

* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: Centos7.9
* Filters and plugins: Tail, Es, Kafka, Elastic Search

**Additional context**

**Comment by merveyilmaz-netrd** [comment]
@edsiper i need some help. Is there a bug in this version?

**Comment by merveyilmaz-netrd** [comment]
> @edsiper i need some help. Is there a bug in this version?
Some times later i got these errors:

Nov 26 10:09:10 104-1 td-agent-bit: [lib/chunkio/src/cio_file.c:415 errno=24] Too many open files
Nov 26 10:09:10 104-1 td-agent-bit: [2021/11/26 10:09:09] [error] [storage] [cio file] cannot open chunk: tail.0/25485-1637852827.916930213.flb

**Comment by merveyilmaz-netrd** [comment]
> > @edsiper i need some help. Is there a bug in this version?
> Some times later i got these errors:
> 
> Nov 26 10:09:10 104-1 td-agent-bit: [lib/chunkio/src/cio_file.c:415 errno=24] Too many open files Nov 26 10:09:10 104-1 td-agent-bit: [2021/11/26 10:09:09] [error] [storage] [cio file] cannot open chunk: tail.0/25485-1637852827.916930213.flb

**Comment by merveyilmaz-netrd** [comment]
> @edsiper i need some help. Is there a bug in this version?

Some times later i got these errors:
Nov 26 10:09:10 104-1 td-agent-bit: [lib/chunkio/src/cio_file.c:415 errno=24] Too many open files
Nov 26 10:09:10 104-1 td-agent-bit: [2021/11/26 10:09:09] [error] [storage] [cio file] cannot open chunk: tail.0/25485-1637852827.916930213.flb

**Comment by TomasKohout** [comment]
Hi, we have the same issue. We are forwarding logs to fluentd and if, for some reason, is fluentd saturated and stops accepting new connections due to buffer_overflow action set to block, fluent-bit will stash logs on filesystem (which is good), but then it won't send them until restarted (which could be too late, because pods doesn't have to exist anymore so it will fail to obtain kubernetes metadata). 

When this happens, fluent-bit will consum a whole mem_buff_limit. Is there some remedy for this behavior?

**Comment by kc8421** [comment]
The same kind of behaviour was captured in our test environment with version 1.8.10 (Windows Server 2016), when Fluent Bit on the receiving side (RHEL 8.4) was down by accident. Instead of Kafka, our configuration was using the forward plugin. Only after the restart, new chunks were being processed. Before restart it was producing only these kinds of log lines:

[2021/11/30 12:50:40] [error] [input:emitter:re_emitted_fluentbit] error registering chunk with tag: fluentbit/20211130/fluentbit.20211130T120000Z.serverxxx.log

**Comment by TomasKohout** [comment]
As mentioned in [issue](https://github.com/fluent/fluent-bit/issues/4376) [this](https://github.com/fluent/fluent-bit/commit/ac5d89f99fa87d1d84d573f62ddf9cd6634bdf79) PR looks promising. :slightly_smiling_face:
