### ISSUE TITLE
Fallback on output error send to other output

### ISSUE THREAD

**Issue by jonabrenman** [fluent/fluent-bit#4441]
**Error handling as fallback from es output to other output**

**It will be very useful to add any fallback on ouput failed in adition for the retries for example if es output fails because elastic search is down send the logs to a bucket s3 or other output as a queue, etc**

**I would like to have a fallback strategy because we dont have too much space in our vms and is going to be more resilient without loose any log**

**Comment by patrick-stephens** [comment]
Personally this feels like trying to work around an Elastic issue: if it is important then it should not fail and accept data via HA or redundant options.

What's the issue with just having another output regardless? Why does it need the complexity of only being triggered if the main is down? I would probably just send to another output all the time and provide a ring buffer there.

How would you then get the data from the fallback to the main?
What happens if the fallback is down but the main is up, or both are down? Do we have fallbacks for fallbacks, how far to go? If one thing is down due to a networking failure then it's likely any other option would also be down.

**Comment by jonabrenman** [comment]
Hi Patrik, in my case is elastic but its never mind witch output is it.
I think is a good idea to have a way to put a fallback output just in case the first one fail so the behaviour is:

1) Main output fail, send to fallback
2) fallback ok? flush from buffer, not ok? retry to main source somewhile.
3) both outputs are down, then retry later.

Lets suppose that elastic is in HA and we have a lot of nodes but we have some troubles with the main dns or all the node are yellow or something like that, i'd like to send to s3 that i know that it always "" works.. but if i send it all the time then i dont know which log failed when pushing to elastic to try the ingest later again.

If i have a new bucket s3 as fallback then i know all the info there, there are records that couldn't be processed by elastic and then i can just put them to the elastic without any complexity, otherwise i need to search if all the items for example in the last 5 minutes in a bucket are in elastic to add them if they are not in elastic.

Hope it's clear know my point, otherwise let me know and i will try to explain it better.
Thank you!

**Comment by patrick-stephens** [comment]
Probably a duplicate of #1632
