### ISSUE TITLE
CVE-2018-12886 found in recent scan of 1.8.11

### ISSUE THREAD

**Issue by Carus11** [fluent/fluent-bit#4472]
Hi There,
A recent scan of fluent-bit:1.8.11 with our security tool, Prisma, is reporting the following high vulnerability:

```
Scan results for image fluent/fluent-bit:1.8.11 sha256:19d0ddffa07f20d1949ac98d7b9eb148dab680fa5ce58c6cb02426f0027b810f

Vulnerabilities
+----------------+----------+------+---------+---------+--------+-------------+------------+----------------------------------------------------+
|      CVE       | SEVERITY | CVSS | PACKAGE | VERSION | STATUS |  PUBLISHED  | DISCOVERED |                    DESCRIPTION                     |
+----------------+----------+------+---------+---------+--------+-------------+------------+----------------------------------------------------+
| CVE-2018-12886 | high     | 8.10 | gcc-8   | 8.3.0-6 | open   | > 2 years   | < 1 hour   | stack_protect_prologue in cfgexpand.c and          |
|                |          |      |         |         |        |             |            | stack_protect_epilogue in function.c in GNU        |
|                |          |      |         |         |        |             |            | Compiler Collection (GCC) 4.1 through 8 (under     |
|                |          |      |         |         |        |             |            | certain circumsta...                               |
+----------------+----------+------+---------+---------+--------+-------------+------------+----------------------------------------------------+
```

Just wondering how we could address this.

Thanks.

**Comment by patrick-stephens** [comment]
Do you run on ARM? The CVE specifically states it affects ARM: https://avd.aquasec.com/nvd/cve-2018-12886/
@edsiper can probably answer on the specific combination of circumstances required but if you're not running ARM then that's an easy waiver.

This issue was ignored by the regular Trivy scan as it is marked as `unfixed` currently. It looks like the only fix for GCC is to step up major version: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85434

Some vendors have backported the changes, e.g. https://access.redhat.com/security/cve/CVE-2018-12886. Red Hat also determined a lower score than NVD but that may be due to other mitigations.
Debian has not: https://security-tracker.debian.org/tracker/CVE-2018-12886

**Comment by Carus11** [comment]
@patrick-stephens thank you for a speedy response! 
We are not running arm, I am going to close this, thank you.
