### ISSUE TITLE
unable to install on ubuntu 16.04

### ISSUE THREAD

**Issue by prashant-warrier-echelonvi** [fluent/fluent-bit#4481]
## Bug Report

**I'm unable to install the `td-agent-bit` package on Ubuntu 16.04**

**To Reproduce**
On a machine running Ubuntu 16.04, perform the following steps:
1. Apt update and apt install `ca-certificates` 

```bash
sudo apt update;

sudo apt install ca-certificates -y;
```

2. Add server GPG key: 

```bash
wget -qO - https://packages.fluentbit.io/fluentbit.key | sudo apt-key add -
```

3. Add this line to either `/etc/apt/sources.list` or `/etc/apt/sources.list.d/td-agent-bit.list` 

```bash
deb https://packages.fluentbit.io/ubuntu/xenial xenial main
```

4. Apt update 

```bash
sudo apt update
```

5. Install the `td-agent-bit` package 

```bash
sudo apt-get install td-agent-bit -y
```

**Expected behavior**
1. The GPG key is added
2. `apt update` happens
3. The package gets installed at the end of step 5 above :point_up: 

**What is happening**
1. Unable to add the GPG key either via `curl` or via `wget` - `gpg` says `no valid OpenPGP data found`.
```
wget -qO - https://packages.fluentbit.io/fluentbit.key | sudo apt-key add -
gpg: no valid OpenPGP data found.
```

2. `apt-get update` fails with the following lines being printed:  

```bash

Ign:10 https://packages.fluentbit.io/ubuntu/xenial xenial/main i386 Packages
Ign:11 https://packages.fluentbit.io/ubuntu/xenial xenial/main all Packages
Ign:12 https://packages.fluentbit.io/ubuntu/xenial xenial/main Translation-en_US
Ign:13 https://packages.fluentbit.io/ubuntu/xenial xenial/main Translation-en
Fetched 109 kB in 37s (2,898 B/s)
Reading package lists... Done
W: The repository 'https://packages.fluentbit.io/ubuntu/xenial xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://packages.fluentbit.io/ubuntu/xenial/dists/xenial/main/binary-amd64/Packages  server certificate verification failed
. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Some index files failed to download. They have been ignored, or old ones used instead.

``` 

3. Consequently, I am unable to install `td-agent-bit` on a machine running ubuntu 16.04 because apt cannot find the package: 

```
sudo apt-get install td-agent-bit -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package td-agent-bit
```

**Your Environment**

* Version used: `1.8`
* Server type and version: Linode VM running Ubuntu 16.04
* Operating System and version: `Ubuntu 16.04.5 LTS`, `xenial`

**Additional context**
We have certain applications running on this machine, and we would like to ship logs from these applications from this machine to elasticsearch.

**Comment by patrick-stephens** [comment]
I've tried to reproduce this locally with a container to represent the 16.04 server and am seeing no issues. It possibly was a transient issue so can you retry?

Launch the container: `docker run --rm -it ubuntu:16.04`
Inside the container
```
apt update
apt install -y ca-certificates wget apt-transport-https
wget -qO - https://packages.fluentbit.io/fluentbit.key | apt-key add -
echo "deb https://packages.fluentbit.io/ubuntu/xenial xenial main" >> /etc/apt/sources.list
apt update
apt-get install td-agent-bit -y
```
All works fine here for me.

I was a bit suspicious that there was an issue accessing the https://packages.fluentbit.io site from your node - are there any proxies or other netwok firewalls in the way that may be blocking or affecting it?

**Comment by jpveritone** [comment]
I'm hitting the same error and its because cert has expired
`openssl s_client -showcerts -connect packages.fluentbit.io:443
CONNECTED(00000005)
depth=1 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
depth=1 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
depth=3 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
`

so I tried `wget --no-check-certificate -qO - https://packages.fluentbit.io/fluentbit.key | sudo apt-key add -` and was able to add the key but my `apt-get install td-agent-bit -y` is still failing with `Unable to locate package td-agent-bit`
My guess is apt-get is also failing because of expired certificate. 

Any chance the cert can be renewed please?

**Comment by junejie** [comment]
same issue. any updates?

**Comment by patrick-stephens** [comment]
I don't think this is an issue with the certificate but the local node, possibly related to the Lets Encrypt expiry issue last year. Have you refreshed your local certs?
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

```
$ openssl s_client -servername packages.fluentbit.io -connect packages.fluentbit.io:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Dec  1 14:21:38 2021 GMT
notAfter=Mar  1 14:21:37 2022 GMT
```

**Comment by patrick-stephens** [comment]
Sure, the point is there is not much we can do here as the certificate is valid but it looks like the image from Azure has got the old root certificate in it so the chain is then broken. I think you can also exclude the root certificate and other workarounds. Ultimately the issue is that root certificate expiry for Lets Encrypt and the subsequent refresh required, however it is done or ignored.

**Comment by junejie** [comment]
I have this issue in aws ec2 server, 
no issue in my local.
docker inside ec2 works fine to. so I assume not a firewall issue.

I manage to solved it by the ff: steps by  commenting the DST_Root_CA_X3 and update the ca-certificates.

```
vi /etc/ca-certificates.conf
```
find `DST` and comment it by `!` so it becomes `!mozilla/DST_Root_CA_X3.crt`
next 
```
update-ca-certificates
apt-get update
```

credits to: 
https://www.claudiokuenzler.com/blog/1088/how-to-solve-apt-error-server-certificate-verification-failed
https://www.claudiokuenzler.com/blog/1135/lets-encrypt-root-ca-expired-git-server-certificate-verification-failed-x3

**Comment by patrick-stephens** [comment]
I'm going to close as it's not really an issue for Fluent Bit itself but the certificates on local machines. We're going to try to make it a bit more visible in the documentation though to helpfully guide people to the various workarounds to update their local certificates.
