### ISSUE TITLE
in_tail keep a lock on files in windows

### ISSUE THREAD

**Issue by noly** [fluent/fluent-bit#4523]
## Bug Report

**Describe the bug**
fluent-bit v1.8.11 is locking files when tailing a folder. This is specially inconvenient for clean up process since it is not possible to purge those files while fb is running.

**To Reproduce**
- Running in amazon EC2 instance: Microsoft Windows Server 2016 Datacenter
- Install td-agent-bit with .exe following [public documentation](https://docs.fluentbit.io/manual/installation/windows)
- Configure to tail from a folder that contain a log file.
<img width="799" alt="Screen Shot 2021-12-23 at 09 45 29" src="https://user-images.githubusercontent.com/4612272/147242369-146fbf04-d636-444b-bffd-d0edb7ed4381.png">

```
[INPUT]
    Name  tail
    Path  C:\test\*.log
    Buffer_Max_Size  128k
    Skip_Long_Lines  On
    Path_Key  filePath
    Tag  old-logs
    Ignore_Older  10s

[OUTPUT]
    name  stdout
    match *
```

- Run td-agent-bit.
<img width="795" alt="Screen Shot 2021-12-23 at 09 44 19" src="https://user-images.githubusercontent.com/4612272/147242231-0a186641-66e6-4aee-b76f-04b08d8491ac.png">

- Notice in the associated handler for fluent-bit process attached to the log file.
<img width="521" alt="Screen Shot 2021-12-23 at 09 46 13" src="https://user-images.githubusercontent.com/4612272/147242437-a40ec85a-4f54-4d0c-bdb4-b183498122b3.png">

- Run a command to open the file.
```shell
PS C:\Users\Administrator> (New-Object System.IO.FileInfo C:\test\old-logs.log).Open([System.IO.FileMode]::Open, [System
.IO.FileAccess]::ReadWrite, [System.IO.FileShare]::None)
Exception calling "Open" with "3" argument(s): "The process cannot access the file 'C:\test\old-logs.log' because it
is being used by another process."
At line:1 char:1
+ (New-Object System.IO.FileInfo C:\test\old-logs.log).Open([System.IO. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IOException
```
- Once fluent-bit process it's stopped, file it is released and able to open/delete it.
<img width="1435" alt="Screen Shot 2021-12-23 at 09 50 50" src="https://user-images.githubusercontent.com/4612272/147242932-810c970d-5461-45c1-bd74-3fe89de95b0c.png">

**Comment by smil2k** [comment]
Is there any progress on this issue? Fluentbit lock the log files and this creates problems.

**Comment by harvell** [comment]
I'm seeing this with 1.9.2 as well. However, it only seems to affect PowerShell as my other apps writing to logs don't seem to be affected. We are trying to consolidate all of our logging from various PowerShell scripts so we developed a logging module to standardize everything. Now, this is putting a major kink into that plan because once Fluent-bit starts monitoring the newly created log file it is locked for writing.

**Comment by moltubakk** [comment]
Came across this half a year after it was created. In order to understand whether it's worth exploring FluentBit or not, I need to get this: At my Win 2019 test server, FluentBit tailing is locking log files from being written by the application. As soon as I close FluentBit, log files are updated. Does this mean that until this issue is fixed, I can not use FluentBit? Or should I search for other possible issues at my server?

**Comment by smil2k** [comment]
The problem is that you cannot move or delete them. (Even if the application is stopped or the logs are old)

**Comment by moltubakk** [comment]
Thanks for the quick reply, @smil2k ! Then my problem is probably something else: I'm not able to tail logs at all, because they seems to be locked for writing. I will have to test more!

**Comment by hahawu42** [comment]
We have a similar issue like @noly using fluent-bit 1.8.15 on linux. Tail plugin puts a lock on the log file and prevents log rotation.

**Comment by smil2k** [comment]
This is still an issue.

**Comment by PyV-IVL** [comment]
Hi, could we please ha a response on this one ?

Thank you.

**Comment by leonardo-albertovich** [comment]
I'll take a look and get back to you. From what I could see in the code, it sounds like this should not happen but I suspect there could be a problem with the macro used.

**Comment by PyV-IVL** [comment]
Thank you very much !

**Comment by leonardo-albertovich** [comment]
I just verified this in windows server 2019 using both fluent-bit 1.8.15 and 2.0.6 (master). I noticed that fluent-bit is opening the files with the correct flags to allow other processes to manipulate them and that reflects in being able to write to / move / delete the file in other programs such as the shell or total commander (both of which I tested).

At first I wasn't able to reproduce the problem but then noticed the powershell line provided by @noly and gave it a try which failed as reported.

The one thing I noticed with that line was that it was trying to open the file with no sharing flags (ie. exclussive access) which would obviously not work because there already is another process who has that file open.

Once I put the right sharing flags it worked as expected  :

```
(New-Object System.IO.FileInfo C:\test\old-logs.log).Open([System.IO.FileMode]::Open, [System.IO.FileAccess]::ReadWrite, [System.IO.FileShare]::ReadWrite)
```

So, unless I'm missing something, in this case it's not fluent-bit who is locking the files. If the issue you are having is different please share more context so we can get to the bottom of it. 

I think if we are not able to reproduce the issue then leaving this open would be a disservice to the community since it could confuse people so please, if any of those who participated can comment and help us reproduce their results it would be greatly appreciated.

On a side note, please upgrade to 2.x if possible, there are lots of improvements in it.

**Comment by smil2k** [comment]
@leonardo-albertovich is keeping the file open really needed? There are so many processes that might try to access these files, log collection is a only a detail which should not cause problems to the main process. 

Also there are files which did not change for a long time, why keeping a handle open on them?

**Comment by leonardo-albertovich** [comment]
As far as I know keeping the files open is necessary and I personally don't think it's something that should cause any problems at all.

I don't know if this is a misunderstanding but just to be clear, fluent-bit does not lock the files, the test script provided by the author in this issue did.

Do you have a real world use case where this type of access is causing an issue you could share with me? Even though I don't think there is a problem with the system I would like to understand your use case and discuss it to determine if there is any way for us to improve the system to be able to handle it within some reasonable limits.

**Comment by leonardo-albertovich** [comment]
If the log files are permanently open why are the synchronization failures random?
Have you analyzed the logs for that? 
Is it related to rotation or something else?
What exactly do we know about the situation and what exactly does "profile sync" mean in this case?

**Comment by smil2k** [comment]
All the files of the profile are uploaded and downloaded when somebody logs in.
Probably the sync want to open the files exclusive?
We use dates for log filenames, I think the log rotation also caused some problems. I don!t remember anymore.

**Comment by leonardo-albertovich** [comment]
Those are important bits of information so we'll need to clarify them to have a good idea of what are we talking about.

**Comment by smil2k** [comment]
Unfortunately I don't have access to that environment anymore.

**Comment by mwhelfrich** [comment]
I currently have this issue happening in a 2.0.6 version of Fluent-Bit on Windows machines. It doesn't seem to be happening to all files in the directory - only files that are around a month old when its at the beginning of a new month potentially? Previous version 1.8.7 never had this issue but this has now happened 2 months a row necessitating restarts.

**Comment by leonardo-albertovich** [comment]
The best thing you could do if you want to expedite this would be trying to minimize the reproduction of the issue creating a small fluent-bit configuration and writing a script to create the file and reproduce the problematic behavior in a controllable way. 

That I can assure you will greatly improve the results.

**Comment by andrerca** [comment]
hello, i am using version 2.1.2 and this problem persists.
my service write json files to a directory named logs with maximum of 10 files using Serilog.
fluent-bit is reading those files in a smb share (\\server\logs) and locking the files for removal, if i stop fluent-bit service, all files are removed instantly
