### ISSUE TITLE
Multiline logs from app in k8s environment contain docker attributes

### ISSUE THREAD

**Issue by nkuzman** [fluent/fluent-bit#4649]
I'm fetching logs from pods which are logging to stdout and can contain multiline logs.
I've applied Multiline parser which works fine regarding detection, but the problem is with lines which are concatenated with first line, because docker attributes (like timestamp and stream) are not being removed.

This is the example of log which application logs (response for metrics enpoint):

```
[2022-01-21 12:21:20,336] [69ADA7F4-8B85-4EB7-A147-C6003D68C8C0] DEBUG a.b.c.HttpLoggingFilter ###response begin###
[2022-01-21 12:21:20,336] [69ADA7F4-8B85-4EB7-A147-C6003D68C8C0] DEBUG a.b.c.HttpLoggingFilter Status : 200
[2022-01-21 12:21:20,336] [69ADA7F4-8B85-4EB7-A147-C6003D68C8C0] DEBUG a.b.c.HttpLoggingFilter Response body : # HELP tomcat_sessions_active_current_sessions
# TYPE tomcat_sessions_active_current_sessions gauge
tomcat_sessions_active_current_sessions{application="Application",} 0.0
# HELP kafka_consumer_coordinator_rebalance_rate_per_hour The number of successful rebalance events per hour, each event is composed of several failed re-trials until it succeeded
# TYPE kafka_consumer_coordinator_rebalance_rate_per_hour gauge
kafka_consumer_coordinator_rebalance_rate_per_hour{application="Application",client_id="consumer-test-app",kafka_version="2.7.1",spring_id="kafkaConsumerFactory.consumer-test-app",} 0.0
...
[2022-01-21 12:21:20,336] [69ADA7F4-8B85-4EB7-A147-C6003D68C8C0] DEBUG a.b.c.HttpLoggingFilter ###response end###
```

This is the fluent-bit configuration i use to parse logs:

```
[PARSER]
    Name ml-parser
    Format regex
    Regex ^(?<systime>\S*) (?<stream>\S*) (?<logtag>\S*) \[(?<time>[\S]*\s[\S]*)[^ ] \[(?<correlation>\S*)[^ ] (?<level>\S*) (?<logger>\S*) (?<message>.*)
    Time_Keep On
    Time_Key    time
    Time_Format %Y-%m-%d %H:%M:%S,%L

---------------------------

[SERVICE]
    Daemon Off
    Flush 1
    Log_Level info
    Parsers_File parsers.conf
    Parsers_File custom_parsers.conf
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_Port 2020
    Health_Check On

[INPUT]
    Name tail
    Path /var/log/containers/*.log
    Read_from_head true
    Multiline on
    Parser_Firstline ml-parser
    Tag app.*
    Mem_Buf_Limit 50MB
    Skip_Long_Lines Off        

[FILTER]
    Name kubernetes
    Match app.*
    Merge_Log Off
    Keep_Log Off
    K8S-Logging.Parser On
    K8S-Logging.Exclude On

[OUTPUT]
    Name es
    Match app.*
    Host elasticsearch
    Port 9200
    Logstash_Format On
    Logstash_Prefix app
    Replace_Dots On
    Retry_Limit False
```

This is how multiline log is displayed in Elasticsearch ("message" field):

```
Response body  : # HELP tomcat_sessions_active_current_sessions  
2022-01-21T09:25:40.370632977Z stdout F # TYPE tomcat_sessions_active_current_sessions gauge
2022-01-21T09:25:40.370653535Z stdout F tomcat_sessions_active_current_sessions{application="Application",} 0.0
2022-01-21T09:25:40.37065925Z stdout F # HELP kafka_consumer_coordinator_rebalance_rate_per_hour The number of successful rebalance events per hour, each event is composed of several failed re-trials until it succeeded
2022-01-21T09:25:40.370663618Z stdout F # TYPE kafka_consumer_coordinator_rebalance_rate_per_hour gauge
2022-01-21T09:25:40.370669373Z stdout F kafka_consumer_coordinator_rebalance_rate_per_hour{application="Application",client_id="consumer-test-app",kafka_version="2.7.1",spring_id="kafkaConsumerFactory.consumer-test-app",} 0.0
```

So, docker attributes are successfully parsed from start line (as expected), but when other lines are concatenated, they keep docker attributes and I don't see a way to remove them.

**Environment:**

**Kubernetes cluster**
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+IKS", GitCommit:"8d49554e103d584f952cc4d28dcf9f410c268847", GitTreeState:"clean", BuildDate:"2021-11-18T19:18:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

**Elasticsearch** Version 7.16.2

**fluent-bit** Version 1.8.11

**Comment by patrick-stephens** [comment]
So, I think what you're saying is this. 

You have actual log output on the node (ignore what the application log looks like, it's what this looks like on the host which is then parsed by Fluent Bit):
```
<timestamp> <stream> F [2022-01-21 12:21:20,336] [69ADA7F4-8B85-4EB7-A147-C6003D68C8C0] DEBUG <timestamp> <timestamp> <stream> F a.b.c.HttpLoggingFilter Response body : # HELP tomcat_sessions_active_current_sessions
<timestamp> <stream> F # TYPE tomcat_sessions_active_current_sessions gauge
<timestamp> <stream> F tomcat_sessions_active_current_sessions{application="Application",} 0.0
...
```
I think this is actually the CRI format rather than Docker btw.
It might be better to look at the new multiline stuff in 1.8 which includes a CRI filter: https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-and-containers-v1.8

In this case though, those lines are no split by your container runtime, they are split by your application?

As you're using the old style multiline the parser is intended to match the first line and then you can have subsequent parsers for each additional line - or you can have a multiline parser that matches everything between each "first line".

Your actual logs have the container runtime information in them and your parser is now consuming everything until it gets to the next "start of line" regex match. This would match up with what you're seeing: `^(?<systime>\S*) (?<stream>\S*) (?<logtag>\S*) \[(?<time>` - there is no <time> group at that position until the next "line".

Possibly what you want is a `Parser_N` style approach to match these multi-lines in the different format, i.e. the CRI stuff then the `#` for prom metric info. Or you could have a `Parser` or `lua` filter possibly removing the CRI stuff as a later stage.

**Comment by patrick-stephens** [comment]
The key is to parse the logs you have on the host, i.e. after output by the container runtime. My suggestion would be to just take a copy of these locally and iterate with that.
