### ISSUE TITLE
Improve parsing error message 

### ISSUE THREAD

**Issue by pragyaarora** [fluent/fluent-bit#4737]
If we add a comment to fluent-bit.conf like `total_file_size             1G # Max size of a single file.` for s3 config then the error shown is `[error] [output:s3:s3.1] Max total_file_size is 50,000,000,000 bytes` . It should provide a better error message

**Comment by patrick-stephens** [comment]
What's the suggested improvement? Please follow the template if possible so it can capture these things.

I guess what is wanted is that it converts it into units similar to what is in the config file. Although this may get tricky for fractional units, e.g. someone specifies 1025 bytes we do not want to convert that to a Kb. We probably could convert to the largest non-fractional unit and use that in the output.

We probably also should capture the actual size in the message rather than just the limit.

It looks like the code that does this is here:
- https://github.com/fluent/fluent-bit/blob/1fa0e94a09e4155f8a6d8a0efe36a5668cdc074e/plugins/out_s3/s3.c#L613

Do you have a pull request we can merge for the update?
