### ISSUE TITLE
cannot increase buffer: current=4192 requested=36960 max=4192

### ISSUE THREAD

**Issue by tpetrov-lp** [fluent/fluent-bit#4776]
## Bug Report

**Describe the bug**
I see "cannot increase buffer: current=4192 requested=36960 max=4192" in the logs coming from the stackdriver.c, which is not related to a kubernetes filter. Should the buffer be 0, similar to what it is for AWS plugins?

What's the actual effect of this warning? Do we lose logs?

**Your Environment**
* Version used: 1.8.11 (docker fluent/fluent-bit:1.8.11-debug)
* Configuration:
Posting just the stackdriver config here:

```
    [OUTPUT]
        Name                    stackdriver
        Match                   stackdriver.*
        Resource                k8s_container
        Trace_Key               tag
        K8s_Cluster_Name        {{ .clusterName }}
        K8s_Cluster_Location    {{ .clusterLocation }}
        Labels_Key              labels
        Severity_Key            severity
        Log_Name_Key            app
        Custom_k8s_Regex        ^container_(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)$
        Tag_Prefix              k8s_
        Retry_Limit             5
```

A similar discussion can be found at https://github.com/fluent/fluent-bit/issues/4120

**Comment by JeffLuoo** [comment]
This seems to be a fixed value: https://github.com/fluent/fluent-bit/blob/8e2f87d02f03501ac3a4b65491d11b0de0d3466c/plugins/out_stackdriver/stackdriver.c#L2257

cc + @edsiper

**Comment by trallnag** [comment]
Maybe the parameter `buffer_size` is missing from the plugin? Setting that option to `0` solves the issue in other plugins like the kubernetes one.

**Comment by lecaros** [comment]
This not necessarily means you're losing records. This buffer is used to read the response from the HTTP server (Splunk, Elasticsearch, etc.). For stackdriver in particular, this is a fixed size; some other plugins allow to configure this parameter.
This buffer is useful when debugging issues with the HTTP server and you want to see the full response. 
Finally, it's important to read this warning in its context because the messages surrounding it are important to determine if it's part of a failed writing operation or if it's a successful one (usually HTTP code 2xx).

Please let me know if this answers your question.
