### ISSUE TITLE
Kubernetes plugin support for namespace metadata

### ISSUE THREAD

**Issue by jessejlt** [fluent/fluent-bit#4796]
**Is your feature request related to a problem? Please describe.**
The [fluentd](https://github.com/sorend/fluentd-k8s/blob/main/README.md) k8s plugin supports namespace metadata enrichment, which creates a barrier for moving to fluentbit for those that are utilizing this feature.

**Describe the solution you'd like**
Support the same namespace metadata enrichment that fluentd supports.

**Describe alternatives you've considered**
Writing a custom output plugin that enriches the record's metadata before sending it along for further processing.

**Additional context**
Just looking for feature parity to aid in moving from fluentd to fluentbit.

**Comment by mgeriesa** [comment]
Hello,
We are using Fluentbit for log ingestion to Elasticsearch Output plugin. For this needs we use Kubernetes filter.
The issue that Kubernetes filter not help us gather data about name space , pod name etc...
This is because the products we deploy in K8S are huge and old one, each products has its own log file directory, so we move all product logs under _empty-dir_ directory, and read from there the logs to ingest into ES.
The products are not microservices , these are old huge products that are containerized and deployed into K8S.

So in order to gather K8S metadata as name space , pod name and node name, we created another sidecar container that create JSON files contains all required metadata. These file are called as: pod_uid.meta 
So we use Kubernetes filter with : Kube_meta_preload_cache_dir  configuration that containes the directory where all pod_uid.meta exists.
In order to read these files  , we need to change the code of Kubernetes filter and especially the _get_meta_file_info_  function.
This is because file is not composed of namespace and pod name. We need to change code to use pod_uid instead

These changes was done in old version 1.1.2
You can see the changes on:
https://github.com/alvinhom/fluent-bit/commits?author=alvinhom

Now we need to add these changes to 1.8.12 which was the recent version.
I see we have already 1.8.13.

Other thing related to OUTPUT ES plugin, we need to create several indexes according to namespace name.
So each namespace actually is a customer, and we need to add several indexes as namespaces, so each customer has its own index.


Can you please help us in that?
