### ISSUE TITLE
Using fluent-bit in sidecar mode on Kubernetes

### ISSUE THREAD

**Issue by yeplaa** [fluent/fluent-bit#5059]
On Kubernetes, i would like use fluent-bit on Sidecar mode. Indeed i need to retrieve directly logs from my main container. 

Is it possible to collect the stdout/stderr of container? Is there for example a kubernetes plugin available for this feature? 
Currently, i haven't yet found..  
In my use case, i  would to avoid collecting logs via files because I don't have control over the docker images to redirect the logs.

**Comment by novegit** [comment]
I did some investigation on this topic some time ago (openshift cluster) and it seems, that the only way to get the container logs (within the container environment) is, to fetch them via the kubernetes api.

**Comment by BartVB** [comment]
As I understand it you are talking about two different scenarios:
- Retrieving logs directly from a container
- Capturing logs/data/messages sent to stdout/stderr

In the first case a sidecar makes perfect sense, there are some examples here:
https://kubernetes.io/docs/concepts/cluster-administration/logging/

In the second case using a DaemonSet is the easiest way to attain this. This is described in the FluentBit documentation.

It's possible to use both at the same time. Use the DaemonSet for all workloads that are designed for k8s (i.e. sent logs to stdout/stderr), and use a sidecare for specific workloads that write to 'normal' logfiles. When using a sidecar the stdout/stderr should be (mostly) empty.

**Comment by yeplaa** [comment]
Thanks for your reply. In my use case, i would like to avoid retrieving logs directly from a container. Also, i can't collect logs from nodes by Daemonset. 
Do you know if it's possible to fetch logs sent to stdout/stderr from a pod sidecar?

As you indicates @novegit maybe the kubernetes api usage could be a solution. But i don't found of fluent plugin for this feature. When you did investigation on this topic, have you find a tool that fetch logs via the kubernetes api?

**Comment by BartVB** [comment]
I'm not an expert, but AFAIK it's not possible to capture stdout/stderr of containers without access to the node.

Doesn't your cloud provider offer a way to aggregate logs from the containers if you can't access the logs directly?

**Comment by yeplaa** [comment]
i would like that the solution works on all Kubernetes clusters. On some cluster, no aggregate logs available.. And i don't want to have dependancies with infrastructure. in the long term, it's always problematic..

**Comment by novegit** [comment]
only to comlpete this, its against all best practices, but it is possible to access the pods process-pid '1' logoutput, from another process in the same pod via the api. Only a token with valid log permissions and a http client is needed:
This fetches the last 200 lines:
```
curl -k -H"Authorization: Bearer $TOKEN" https://kubernetes.default.svc.cluster.local:443/api/v1/namespaces/$NAMESPACE/pods/$HOSTNAME/log?tailLines=200 | grep journal 
100 18952    0 18952    0     0   319k      0 --:--:-- --:--:-- --:--:--  319k
[0] journal_1m_stats: [1647279122.449323478, {"COUNT(*)"=>95}]
[0] journal_1m_stats: [1647279182.449409557, {"COUNT(*)"=>108}]
[0] journal_1m_stats: [1647279242.449350398, {"COUNT(*)"=>95}]
[0] journal_1m_stats: [1647279302.449340180, {"COUNT(*)"=>94}]
[0] journal_1m_stats: [1647279422.449404499, {"COUNT(*)"=>95}]
[0] journal_1m_stats: [1647279542.449676114, {"COUNT(*)"=>94}]
...
```

**Comment by yeplaa** [comment]
Thanks for your reply. 

@patrick-stephens Have you an implementation example regarding the log to stdout and to a file on the same time? In your dockerfile, first you write to your file and then you create a symbolic link to stdout, that's right? 
Also, with the logs file generated inside the container, it is also necessary to manage the rotation of the logs :(

Regarding the pipe usage, could you more information on your works, tests please? 

Regarding the access to logs from api kubernetes, indeed only some rbac rigths are necessary. I have not yet found of tools, solution using this usage, but otherwise it's possible to create your own docker image.

**Comment by CharlesB2** [comment]
I'm having the same issue, is there any successful implementation that solves this particular problem?
We want to get stdout of a running container with fluentd without ClusterAdmin privileges

**Comment by patrick-stephens** [comment]
Redirect stdout to a file in a shared volume and use that, that's fairly trivial - just a pod in a volume that one container writes and one reads. I did this for Couchbase a while ago: https://github.com/couchbase/couchbase-fluent-bit

Connecting pipes directly is always problematic even in non-containers but you could potentially do it too.

**Comment by litiliu** [comment]
But how can we redirect the stdout  stderr to a  shared volume without changing the main container?

> Redirect stdout to a file in a shared volume and use that, that's fairly trivial - just a pod in a volume that one container writes and one reads. I did this for Couchbase a while ago: https://github.com/couchbase/couchbase-fluent-bit
> 
> Connecting pipes directly is always problematic even in non-containers but you could potentially do it too.

**Comment by patrick-stephens** [comment]
I don't think this is really a Fluent Bit question anymore, it's an architecture one.

You have to work with what you've got really, something needs to be changed. So just some thoughts of possible options (there are likely more and it depends on your specific constraints).

It is possible to configure a cluster to support host volume mounting without cluster admin (although a cluster admin would have to set up the appropriate security config you need).

You could also modify the container runtime config to send logs via [Fluent Forward](https://docs.docker.com/config/containers/logging/fluentd/) rather than to local log files then listen for that in a deployment. This may be possible to target just the pods you want as well. Possibly you could also use [`journald`](https://docs.docker.com/config/containers/logging/journald/) output then just consume that in Fluent Bit rather than host log files - be weird security to prevent local log files but allow journald access though.

You can also create a container based on your current one and add Fluent Bit to the base image to do whatever you need directly within the container, it could also wrap the binaries to redirect stdout/stderr via an entrypoint (I've done that before for other targets). This is no change to your actual binaries in the original container: you're just adding another layer on top. It all depends on what your specific constraints are (e.g. it sounds like you cannot change containers but you can change pod specs?).

Finally you could try to see if you can connect the pipes between your two containers but personally that would be my least preferred option.

None of these may be acceptable for you, but there are options and you need to figure out which one fits your particular use case.
