### ISSUE TITLE
Duplicate logs are forwarded to elasticsearch

### ISSUE THREAD

**Issue by digvijaysk19** [fluent/fluent-bit#5123]
Using fluentbit to forward logs to elasticsearch.
Getting duplicate logs. Generate_Id set to On in output config.
Also, logstash is being used with elasticsearch (does **Generate_Id**= ON work with logstash + elastic search ? ). 

**fluent-bit version:** 1.8.12
Is this a known issue or misconfiguration?

seeing such logs frequently for fluent-bit pod:

`[debug] [http_client] not using http_proxy for header`
`[debug] [output:es:es.0] HTTP Status=200 URI=/_bulk`
`[error] [output:es:es.0] could not pack/validate JSON response`
`ok`
`[debug] [upstream] KA connection #37 to xyz.com:5054 is now available`
`[debug] [out coro] cb_destroy coro_id=4`
`[debug] [retry] new retry created for task_id=0 attempts=1`
`[ warn] [engine] failed to flush chunk '9-1645024771.465981251.flb', retry in 7 seconds: task_id=0, input=tail.0 > output=es.0 (out_id=0)`
`[debug] [upstream] KA connection #37 to xyz.com:5054 has been assigned (recycled)`
` [debug] [http_client] not using http_proxy for header`
` [debug] [output:es:es.0] HTTP Status=200 URI=/_bulk`
` [error] [output:es:es.0] could not pack/validate JSON response`
`ok `

**Comment by patrick-stephens** [comment]
Please follow the template: we need full configuration at least but also anything to help reproduce like example input and ideally a reproducible example.

Have you checked the output via stdout output, does that also show duplicates or is the duplicate just in Opensearch?

**Comment by emilio-cea** [comment]
> Have you checked the output via stdout output, does that also show duplicates or is the duplicate just in Opensearch?

Hi, just for confirmation, I also noticed this on my python app. Some log appears as a duplicate on my ES: it has the same timestamp but contains a different _id. 

I checked the stdout plugin and it shows the two logs as well. **Were you looking for a different behaviour?**

This is my `td-agent-bit` config:
```
[SERVICE]
    Flush 5
    Log_Level info
    Daemon Off
    Parsers_File parsers.conf
    Plugins_File plugins.conf

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24224

[OUTPUT]
    Name es
    Host my_es_uri
    Port 8081
    Index fluent_logger_test
    Type type_logger
    Trace_Output on
    Trace_Error on
    Match *
[OUTPUT]
    Name stdout
    Match *
```

I **know these are duplicate** and should not because my app logs to stdout as well, so I can check both the output of the app **in real time**, the stdout of fluentbit and the ES results.

I am using this python logger library for fluentd: https://pypi.org/project/fluent-logger/

```py       
def get_logger(name, populate = None):

    logger = logging.getLogger(name)
    logger.setLevel(logging.DEBUG)
    log_filter=DatalogFilter()
    logger.addFilter(log_filter)

    log_handler = handler.FluentHandler('test', host='localhost', port=24224, nanosecond_precision=True)
    formatter = handler.FluentRecordFormatter(log_format, fill_missing_fmt_key=True)
    log_handler.setFormatter(formatter)
    logger.addHandler(log_handler)

    return logger
```

When I need to send a log, I call this function and then the appropriate level (debug, info, warning, etc). The DatalogFilter is just to set the json formatting I use.
