### ISSUE TITLE
Catch a message between two tags

### ISSUE THREAD

**Issue by storm1kk** [fluent/fluent-bit#5335]
**Is your feature request related to a problem? Please describe.**
Dear Fluent Bit team, 

I have a problem with the multiline support in FluentBit. For example, I have the next log message:

```
<m> ERROR: Hey Mr. Programmer, look there is an error:
         at here
         at here
         ...a lot of lines here...
Caused by this thing
.... more
</m>
```

As I read in the documentation I can use a multiline parser with regexp to catch such messages. So I use one like this:

```
    [MULTILINE_PARSER]          
        name          multiline-regex
        type          regex
        flush_timeout 500
        rule      "start_state"   "/.*<m>.*/"  "cont"
        rule         "cont"       "/\s+at.*/" "cont"
```

But the problem is that parser doesn't catch the whole message. I tried to modify it to catch "Caused" and "..." but it catches a lot more other messages so I need to adjust flush_timeout. 

I was wondering if there is a possibility to add something to catch the whole message in `<m>... </m>`?

**Describe the solution you'd like**

I would like to have a solution that allows me to catch log messages between some tags. Something like:

```
start_regex "/.*<m>.*/"
end_regex "/.*<\/m>$/"
```

I don't see a part of the message now or catch too many messages.
Thanks in advance!

**Comment by patrick-stephens** [comment]
I think all you need to do is make sure your start_regex matches then capture everything until the next one. This works for your example:
```
[MULTILINE_PARSER]
    name          multiline-regex-test
    type          regex
    flush_timeout 1000
    rule      "start_state"   "/^<m>.*/"  "cont"
    rule         "cont"       "/.*/" "cont"
```
If I run it with 1.9.2 container:
```
$ docker run --rm -v $PWD:/fluent-bit/etc/ ghcr.io/fluent/fluent-bit
Fluent Bit v1.9.2
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/04/22 10:20:22] [ info] [fluent bit] version=1.9.2, commit=27a63c11d3, pid=1
[2022/04/22 10:20:22] [ info] [storage] version=1.1.6, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/04/22 10:20:22] [ info] [cmetrics] version=0.3.0
[2022/04/22 10:20:22] [ info] [input:tail:tail.0] multiline core started
[2022/04/22 10:20:22] [ info] [sp] stream processor started
[2022/04/22 10:20:22] [ info] [input:tail:tail.0] inotify_fs_add(): inode=100270112 watch_fd=1 name=/fluent-bit/etc/test.log
[2022/04/22 10:20:22] [ info] [output:stdout:stdout.0] worker #0 started
[0] tail.0: [1650622822.510727973, {"log"=>"<m> ERROR: Hey Mr. Programmer, look there is an error:
         at here
         at here
         ...a lot of lines here...
Caused by this thing
.... more
</m>
"}]
```
The problem might be if you have your start tag also in the other lines, e.g. a random `<m>` somewhere in there. I modified your original to ensure it was at the start of the line.

**Comment by storm1kk** [comment]
@patrick-stephens thank you for the hint but it doesn't work for me. I tried to use regex you suggested but I still have individual strings instead of the whole message.

**Comment by patrick-stephens** [comment]
@storm1kk you're going to have to provide more details: it seems to work for the example you provided but sounds like you have more complex logs.

From: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing
* A log record will start each time it hits the `start` rule, inherently the end of the previous rule.
* Continuation rules will be included for the current log record, others will be excluded.

An end regex is implicitly handled when the next start rule is hit. 

It sounds like you need specific continuation rules to match only some of the complex log output you have, i.e. include specific things but not others. However it's hard to tell without a specific example. 

My recommendation is always to try to standardise the logs first if you can rather than come up with super complex regex's to maintain (spend the effort where it is most effective). However this is not always possible and sometimes you have to cope with inconsistent log formats. 
Could you just capture more simple regex's generally in these cases and process them further downstream for specific cases (e.g. log file X needs extra work via another parser filter to handle multiline messages but all other logs are ok)?
