### ISSUE TITLE
Throttle: Support retain messages if rate limit is exceeded

### ISSUE THREAD

**Issue by wangzhuzhen** [fluent/fluent-bit#5356]
**Is your feature request related to a problem? Please describe.**

For now, if rate limit is exceeded, throttle will drop the messages. 
For now, if before fluent-bit first running, there is a input with huge messages which exceeded the throttle's (window * rate * interval), then only the first (window * rate * interval) records will be save, the others before fluent-bit running will be dropped.

**Describe the solution you'd like**
Need a turn on/ turn off feature, if turn on, no messages will be dropped (at the cost of some latency if user do not care). If turn off, keep the logic for throttle does now. 

**Describe alternatives you've considered**
Add an config parameter 'Retain' with boolean value, default is false which keep the old logic,. While set Retain as true,  no messages will be dropped (at the cost of some latency if user do not care).

**Additional context**

**Comment by taka-i** [comment]
In my project I want to send large amount of logs to Opensearch but on the Opensearch side it is very likely to reach maximum number of bulk insert API call.
So I want to throttle the rate by this Throttle filter plugin, but it turned out Throttle plugin discard all the data which exceeds the limit.
I want all logs to be preserved and send logs in throttled rate.
I find this commit very useful.
Please somebody implement, the code is already commited.

**Comment by juanpiadmsft** [comment]
I am also in need of this exact feature.
