### ISSUE TITLE
fuzzing test on PR branch

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#5876]
## Bug Report

**Describe the bug**

I sent a PR #5875 and CI reports below error about `flb_hmac.c` and `flb_hmac.h`.
However `flb_hmac.c` and `flb_hmac.h` are not contained on PR branch.
https://github.com/nokute78/fluent-bit/tree/test_out_lib/src
https://github.com/nokute78/fluent-bit/tree/test_out_lib/include/fluent-bit

They are contained at [current master](https://github.com/fluent/fluent-bit/tree/b13acb335d46a6bf556913e8a0d5cb6fbc13f16d)
I think fuzzing test uses a master branch, not a pull request branch.

CI error: 
https://github.com/fluent/fluent-bit/runs/7798534372?check_suite_focus=true
```
[ 31%] Building C object src/CMakeFiles/fluent-bit-static.dir/flb_hmac.c.o
In file included from /src/fluent-bit/src/flb_hmac.c:18:
/src/fluent-bit/include/fluent-bit/flb_hmac.h:22:10: fatal error: 'openssl/err.h' file not found
#include <openssl/err.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/fluent-bit-static.dir/build.make:720: src/CMakeFiles/fluent-bit-static.dir/flb_hmac.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4264: src/CMakeFiles/fluent-bit-static.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**To Reproduce**
- Rubular link if applicable: None
- Example log message if applicable: None
- Steps to reproduce the problem: Create Pull request

**Expected behavior**

Fuzzing test on pull request branch.

**Screenshots**

None 

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

Does oss-fuzz try to clone current master ?
https://github.com/google/oss-fuzz/blob/84ffe92c14ef141e01b437b5359e6eea8abbfe94/projects/fluent-bit/Dockerfile#L18

Cc: @patrick-stephens

**Comment by patrick-stephens** [comment]
@nokute78 unfortunately the fuzzing job is not really my domain, it calls out to the oss-fuzz project so typically I think @DavidKorczynski handles it.

I think the issue might be that the fuzzer seems to only be cloning the default branch of the repo, i.e. `master` rather than the specific PR. We may have to move fuzzing to `master` push events or update the fuzz to check out the right branch+repo.

https://github.com/google/oss-fuzz/blob/84ffe92c14ef141e01b437b5359e6eea8abbfe94/projects/fluent-bit/Dockerfile#L18

**Comment by PettitWesley** [comment]
@nokute78 @patrick-stephens I think that realistically it makes more sense to do fuzzing on the current patch branch and on master. Since fuzzing is fundamentally about randomly catching issues that come from inputs that we didn't think of... so it takes time to find issues. You could run a short fuzz job on a PR and not find anything. Fuzzing also tends to be CPU intensive right? So more expensive to allow for any contributor. 

So I think of fuzzing as a way to catch things missed in PR review after merge but before release.

**Comment by patrick-stephens** [comment]
Yes, I agree with you both - my suggestion was primarily based on the current approach in the fuzzing project but that looks to have been resolved.
Thanks also to @leonardo-albertovich and @DavidKorczynski on this as well, I think this is a significant improvement.

**Comment by patrick-stephens** [comment]
@nokute78 can we close now?
@leonardo-albertovich we may need that change pushed to the 1.9 branch as well to run fuzzers on any backports?

**Comment by DavidKorczynski** [comment]
We should distinguish here fuzzing done by OSS-Fuzz and fuzzing done by CIFuzz, as they are connected but not completely the same.

CIFuzz uses the OSS-Fuzz set up, we can set up the github actions to support more branches than just master. See: https://google.github.io/oss-fuzz/getting-started/continuous-integration/#branches-and-paths

**Comment by nokute78** [comment]
@patrick-stephens Missing OpenSSL header issue was fixed.
However CIFuzz still pulls default branch "master" when we send a pull request, so I think we can't close this issue now.
https://github.com/fluent/fluent-bit/runs/7869341782?check_suite_focus=true#step:4:253
```
Step 3/5 : RUN git clone --depth 1 https://github.com/fluent/fluent-bit/ fluent-bit
 ---> Running in 526e3966b41d
```

**Comment by patrick-stephens** [comment]
@leonardo-albertovich did you fix this? I vaguely recall you looking at it.
