### ISSUE TITLE
Checklist filter and LTSV not working properly?

### ISSUE THREAD

**Issue by atmosx** [fluent/fluent-bit#5884]
## Bug Report

**Describe the bug**
Trying to filter against a list of FQDNs using the `checklist` filter, but `fluent-bit` shows nothing.

**To Reproduce**

See configuration files:

```
[PARSER]
    name        dproxy
    format      ltsv
    time_Key    time
    time_Format %s
    time_Offset +0300
    types       cached:integer duration:integer
```
Fluent bit config file:
```
[SERVICE]
    flush        1
    log_level    info
    parsers_file /opt/software/fluent-bit/parsers.conf

[INPUT]
    name              tail
    path              /var/log/dnscrypt-proxy/query.log
    read_from_head    true
    parser            dproxy

[FILTER]
    name checklist
    match tail
    file /opt/software/fluent-bit/domains.txt
    lookup_key $message
    record malware found
    # log_level debug

[OUTPUT]
    name stdout
    match checklist
```
The `domains.txt` file has one FQDN (e.g. `www.paok.de`) per line.

**Expected behavior**
Show output for domains that match the `domains.txt`.

**Your Environment**

* Version used: 1.9.7
* Configuration: compiled from source using default flags
* Server type and version: bare metal (HP Proliant microserver8)
* Operating System and version: Gentoo Linux 5.15.11-gentoo-x86_64
* Filters and plugins: checklist

**Comment by leonardo-albertovich** [comment]
Hey, it seems like your `match` settings are wrong, if you want to use absolute values you have to put the plugin name and instance id separated by a dot the same way fluent-bit prints it, otherwise you can use the asterisk to match all instances of a single plugin or any instances, I'll put some examples : 

This will not print anything :

```
[SERVICE]
    flush 1
    grace 1
    log_level info

[INPUT]
    name dummy

[INPUT]
    name tail
    path test_input_file_1.log

[INPUT]
    name tail
    path test_input_file_2.log

[OUTPUT]
    name stdout
    match tail
```

This will print whatever is ingested by the tail plugin from `path test_input_file_2.log` :

```
[SERVICE]
    flush 1
    grace 1
    log_level info

[INPUT]
    name dummy

[INPUT]
    name tail
    path test_input_file_1.log

[INPUT]
    name tail
    path test_input_file_2.log

[OUTPUT]
    name stdout
    match tail.1
```

This will print whatever is ingested by the tail plugin from `path test_input_file_1.log` and `path test_input_file_2.log` :

```
[SERVICE]
    flush 1
    grace 1
    log_level info

[INPUT]
    name dummy

[INPUT]
    name tail
    path test_input_file_1.log

[INPUT]
    name tail
    path test_input_file_2.log

[OUTPUT]
    name stdout
    match tail.*
```

This will print whatever is ingested by the tail plugin from `path test_input_file_1.log` and `path test_input_file_2.log` as well as what's produced by the dummy plugin :

```
[SERVICE]
    flush 1
    grace 1
    log_level info

[INPUT]
    name dummy

[INPUT]
    name tail
    path test_input_file_1.log

[INPUT]
    name tail
    path test_input_file_2.log

[OUTPUT]
    name stdout
    match *
```

**Comment by atmosx** [comment]
Thanks for clarifying I got this all wrong.

Using `match tail` works as expected. I was expecting only filtered events to reach `stdout` which is not the case. All events are reaching `stdout`, the filtered ones have the extra key pair `"record" => "malware found"`.
