### ISSUE TITLE
[Tail] Can't tail symlink file when set Path_Key

### ISSUE THREAD

**Issue by scila1996** [fluent/fluent-bit#5964]
Hi. I'm crawling log from K8S. File /var/log/containers/*.log linked to /var/log/pods, when i set `Path_Key file_name`, it error with

```
[input chunk] skip ingesting data with 0 bytes
```

In host, I have folder structure like this

```
/var/log/containers/antrea-agent-x4qbg_kube-system_antrea-agent-tweaker-bc39d2469a20f42601202f72e187da266accd2286047cfb2ca1330419984abc2.log

-> /var/log/pods/kube-system_antrea-agent-x4qbg_001ae657-d01c-4030-ad1a-9299ca112cce/antrea-agent-tweaker/0.log
```

My container volume config

```
    volumeMounts:
    - mountPath: /var/log
      name: logs
  volumes:
  - hostPath:
      path: /var/log
```

My fluentbit-config

```
      [INPUT]
          Name              tail
          Path              /var/log/containers/*.log
          multiline.parser  docker, cri
      [OUTPUT]
          Name    stdout
```

It's work well as expected and output anything in all log file, but when add Key_Path file_name

```
      [INPUT]
          Name              tail
          Path              /var/log/containers/*.log
          Path_Key          file_name
          multiline.parser  docker, cri
```

It's Error as below and do not output anything log content to stdout

> [2022/08/31 13:16:09] [debug] [input chunk] skip ingesting data with 0 bytes
[2022/08/31 13:16:09] [debug] [input chunk] skip ingesting data with 0 bytes
[2022/08/31 13:16:09] [debug] [input chunk] skip ingesting data with 0 bytes
[2022/08/31 13:16:09] [debug] [input chunk] skip ingesting data with 0 bytes
[2022/08/31 13:16:09] [debug] [input chunk] skip ingesting data with 0 bytes

Maybe when I set Path_Key, it's read symlink file content and was not read destination file.

**Comment by RicardoAAD** [comment]
Hello @scila1996, the fix for this issue proposed by @BinaryFissionGames in PR https://github.com/fluent/fluent-bit/issues/6240#event-7644118753, was merged into the master branch and will be released in Fluent-bit v2.0.0.

You can check these articles to test Fluent-Bit v2.0 which includes this fix, but as this is not an official version yet, it is not intended for a production environment.

https://docs.fluentbit.io/manual/installation/sources/download-source-code
https://docs.fluentbit.io/manual/v/2.0-pre/installation/sources/build-and-install

Please note: the master branch will be our next release v2.0.0, you can also test it with an unofficial image https://github.com/fluent/fluent-bit/tree/master/dockerfiles#ghcrio-topology

Ricardo.
