### ISSUE TITLE
Fluent-bit v1.5.0 tail with hostPath/custom log file not working

### ISSUE THREAD

**Issue by adapasuresh** [fluent/fluent-bit#6017]
### Discussed in https://github.com/fluent/fluent-bit/discussions/6016

<div type='discussions-op-text'>

<sup>Originally posted by **adapasuresh** September  6, 2022</sup>
With-in my K8S one of the container writes logs to "/opt/logs/mastercard/JSON/*.log"

bash-4.2# ls
bin  cloudwatch.so  configs  etc  firehose.so  kinesis.so  licenses  log  parsers
bash-4.2# cd bin/
bash-4.2# ./fluent-bit --version
**Fluent Bit v1.5.0**

I have fluent-bit.yaml with, First three sections work fine.
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
    @INCLUDE input-tokenization-kubernetes.conf
    @INCLUDE output-tokenization-elasticsearch.conf

For the tokenization piece, I am trying to read from the host path "/opt/bizmetrics"
Tried below options
Option 1) volumeMounts and volume defined in fluent-bit.yaml
Option 2) volumeMounts and volume defined in app-helm-values.yaml
Option 3) in Dockerfile gave -v<hostPath>:<containerPath>

volumeMounts:
  name: bizmetrics-optlogs
  mountPath: /opt/logs/mastercard/JSON
volumes:
  name: bizmetrics-optlogs
  hostPath:
    path: /opt/bizmetrics
    type: DirectoryOrCreate

In all the Options above, I can see the log files at /opt/logs/mastercard/JSON/bzmetrics.json
But, can't find the hostPath "/opt/bizmetrics" on the node and hence no index and data in my ElasticSearch. 

</div>

**Comment by adapasuresh** [comment]
Upgraded to 1.9.7 / image: amazon/aws-for-fluent-bit:2.28.0
Same issue.

bash-4.2# ps -ef 
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 05:25 ?        00:00:02 /fluent-bit/bin/fluent-bit -e /fluent-bit/firehose.so -e /fluent-bit/cloudwatch.so -e /fluent-bit/kinesis.so -c /fluent-bit/etc/fluent-bit.conf
root        37     0  0 05:29 pts/0    00:00:00 bash
root        46    37  0 05:29 pts/0    00:00:00 ps -ef
bash-4.2# /fluent-bit/bin/fluent-bit --version
Fluent Bit v1.9.7
Git commit: 265783ebe99590cf1687d2f48b300f58febb883d
bash-4.2# cat /fluent-bit/etc/fluent-bit.conf 
[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

@INCLUDE input-kubernetes.conf
@INCLUDE filter-kubernetes.conf
@INCLUDE output-elasticsearch.conf
@INCLUDE input-tokenization-kubernetes.conf
@INCLUDE output-tokenization-elasticsearch.conf
bash-4.2# mount -l | grep /opt
bash-4.2# mount -l | grep -ir '/opt'

**Comment by patrick-stephens** [comment]
Which helm chart are you using?
Can you simplify it down so it does not have all the includes and/or provide the includes? I can't actually see anything tailing the particular file you want.
Can you provide the pod spec `kubectl describe pod ...` so we can see the mounts?

My understanding of your issue is that on your worker node there is a particular log file at "/opt/logs/mastercard/JSON/*.log" but this is not being picked up by Fluent Bit daemonset, is that right?

What permissions are on the node filesystem for those files and all the directories up to it?
Can you run with `log_level` debug to see if there are any warnings or errors reported about the fliepath?
