### ISSUE TITLE
Support for Amazon Linux 2022

### ISSUE THREAD

**Issue by ruilapa** [fluent/fluent-bit#6020]
**Is your feature request related to a problem? Please describe.**
Unable to install on Amazon Linux 2022.

**Describe the solution you'd like**
Install on Amazon Linux 2022

**Additional context**
 curl https://raw.githubusercontent.com/fluent/fluent-bit/master/install.sh | sh
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3105  100  3105    0     0  18705      0 --:--:-- --:--:-- --:--:-- 18818
================================
 Fluent Bit Installation Script
================================
This script requires superuser access to install packages.
You will be prompted for your password by sudo.
[fluent-bit]
name = Fluent Bit
baseurl = https://packages.fluentbit.io/amazonlinux/$releasever/$basearch/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.fluentbit.io/fluentbit.key
enabled=1
Fluent Bit                                                                                                                    198  B/s | 162  B     00:00
Errors during downloading metadata for repository 'fluent-bit':
  - Status code: 404 for https://packages.fluentbit.io/amazonlinux/2022.0.20220831/x86_64/repodata/repomd.xml (IP: 139.178.85.103)
Error: Failed to download metadata for repo 'fluent-bit': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: fluent-bit
Last metadata expiration check: 2:42:51 ago on Tue 06 Sep 2022 11:46:12 AM UTC.
No match for argument: fluent-bit
Error: Unable to find a match: fluent-bit
Fluent Bit                                                                                                                    214  B/s | 162  B     00:00
Errors during downloading metadata for repository 'fluent-bit':
  - Status code: 404 for https://packages.fluentbit.io/amazonlinux/2022.0.20220831/x86_64/repodata/repomd.xml (IP: 139.178.85.103)
Error: Failed to download metadata for repo 'fluent-bit': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: fluent-bit
Last metadata expiration check: 2:42:52 ago on Tue 06 Sep 2022 11:46:12 AM UTC.
No match for argument: td-agent-bit
Error: Unable to find a match: td-agent-bit
```

**Comment by patrick-stephens** [comment]
Amazon Linux 2022 is not officially supported as you say: https://docs.fluentbit.io/manual/installation/supported-platforms
The main reason is that Amazon Linux 2022 is a preview release currently: https://docs.aws.amazon.com/linux/al2022/release-notes/relnotes.html
```
Amazon Linux 2022 is in preview release, and the features, packages, and package versions that are included in the preview release are subject to change.
```

However we should be able to support it once it is stable and it should be a case of modifying the current packaging target: https://github.com/fluent/fluent-bit/tree/master/packaging/distros/amazonlinux
Feel free to submit a PR to cover it, a similar one was recently added for Ubuntu 22.04 support.

**Comment by patrick-stephens** [comment]
We can build AL2022 packages already, we just do not provide any official packages in repositories for them as a supported target.
The primary reason is that it is still not GA, expected Q4 2022: https://aws.amazon.com/linux/amazon-linux-2022/faqs/

This issue is to cover the changes required once we want to support it:

- [ ] One line install script update: https://github.com/fluent/fluent-bit/blob/f092885a4bbdea2104af203a8a727cf6eaa7e4b6/install.sh#L36
- [ ] Add to the build config: https://github.com/fluent/fluent-bit/blob/f092885a4bbdea2104af203a8a727cf6eaa7e4b6/packaging/build-config.json
- [ ] Ensure we include repo in packaging process: https://github.com/fluent/fluent-bit/blob/f092885a4bbdea2104af203a8a727cf6eaa7e4b6/packaging/update-repos.sh#L18
- [ ] Ensure release server provides repository (not exposed here).
- [ ] Update docs for supported platforms: https://github.com/fluent/fluent-bit-docs/blob/master/installation/linux/amazon-linux.md

**Comment by patrick-stephens** [comment]
This should be present in 2.0.
