### ISSUE TITLE
Splunk enhancement: support setting metadata fields for events

### ISSUE THREAD

**Issue by willgorman** [fluent/fluent-bit#609]
When using the Splunk output plugin it would be helpful to be able to set additional metadata on the event, like [host, source, sourcetype, and index](http://docs.splunk.com/Documentation/Splunk/7.1.0/Data/FormateventsforHTTPEventCollector#Event_metadata).  The use case I'm thinking of would be to use filters to manipulate some of the fields from the Kubernetes filter so that Splunk metadata could be derived from Kubernetes metadata.

**Comment by michiel** [comment]
You can build HEC compatible output using 0.13.2 with `modify` and `nest` filters, including setting values for `host`, `source`, etc. I've put together an example in docker-compose here,

https://github.com/michiel/docker-compose-splunk-fluentbit

**Comment by ffscl** [comment]
@willgorman we'll be uploading an example next week for this

**Comment by chlunde** [comment]
@michiel But this does not use `out_splunk`.  If users must use `out_http` instead of `out_splunk` for this, why have `out_splunk` at all?  I assume there is or will be some needs for splunk-specific customizations which will be nicer to handle in `out_splunk` than the generic http plugin.

We're trying out a patch to `out_splunk` which supports this.  I'll send a PR shortly so anyone can take a look.

**Comment by edsiper** [comment]
I've merged #610 that provides an optional way to package the records. 

Should we close this ticket or is there anything pending to solve ?
