### ISSUE TITLE
Forward input plugin stops accepting input after first ACK is sent back

### ISSUE THREAD

**Issue by epsteina16** [fluent/fluent-bit#6384]
## Bug Report

**Describe the bug**
When sending logs to Fluent Bit via the forward protocol, Fluent Bit will stop reading data from the socket after it has sent back the first ACK to the client. I noticed this when upgrading from 1.8.7 to 2.0.4.

**To Reproduce**
I was able to reproduce this with two Fluent Bits communicating over Forward.

Configuration for Fluent Bit 1:
```
[SERVICE]
  flush 1

[INPUT]
  Name dummy
  Tag dummy.log
  Rate 500

[OUTPUT]
  Name forward
  Match *
  Unix_Path /tmp/testsoc
  Require_ack_response True
  retry_limit false
```

Configuration for Fluent Bit 2:
```
[SERVICE]
  flush 1
  storage.sync normal
  storage.path /tmp/storage

[INPUT]
  Name forward
  Unix_Path /tmp/testsoc
  storage.type filesystem
  buffer_chunk_size 1000000
  buffer_max_size 500000

[OUTPUT]
  Name stdout
  Format json_lines
  Match *
```

Note that Requires_ack_response is set to true which makes this problem happen.
Logs are dropped and error messages like the following are see in Fluent Bit 1's log:
[2022/11/10 15:14:26] [error] [output:forward:forward.0] could not write forward header

**Expected behavior**
The forward server, which is the second fluent bit in this case, should continue reading from the open socket after sending the first ACK. This was the behavior of Fluent Bit v1.8.7

**Your Environment**
rhel7 linux
* Version used: 2.0.4

**Additional context**
Some debugging has led me to believe that the issue is that the event associated with the socket's FD is removed from the event loop by the call to flb_io_net_write() in send_ack(). Since the fd is not in the event loop, no reads are ever done from this socket even though there is pending data.
I was able to work around the issue by patching send_ack() in fw_prot.c to add an event back to the event loop after flb_io_net_write() is called.

**Comment by epsteina16** [comment]
This was introduced by https://github.com/fluent/fluent-bit/commit/0d4d7c848d3f7abd640f0c4e7017196acc3980be

**Comment by agup006** [comment]
@leonardo-albertovich @pwhelan adding as I think folks were looking into tls regress

**Comment by leonardo-albertovich** [comment]
@epsteina16 quick question, did you modify your test to use unix sockets in order to make it easier to reproduce? Because what I noticed when debugging that was that the socket that's used to connect to the server (in unix socket mode) [is set to non blocking mode](https://github.com/fluent/fluent-bit/blob/master/plugins/out_forward/forward.c#L818)  (which actually is actually done twice since [flb_net_socket_create](https://github.com/fluent/fluent-bit/blob/master/src/flb_network.c#L273) does it if the second argument is `true`).

But the problem is that [fd_io_read](https://github.com/fluent/fluent-bit/blob/master/src/flb_io.c#L467) is [not able to work with async file descriptors](https://github.com/fluent/fluent-bit/blob/master/src/flb_io.c#L589).

Once I removed the `flb_net_socket_nonblocking` call everything started working as expected but the one thing I noticed was that when executing with more than one worker sometimes the expected ACK value gets mixed up which is definitely not cool : 

```
[2022/11/17 15:43:27] [ info] [fluent bit] version=2.0.6, commit=a99d7c6a19, pid=2249334
[2022/11/17 15:43:27] [ info] [storage] ver=1.1.6, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/11/17 15:43:27] [ info] [cmetrics] version=0.5.7
[2022/11/17 15:43:27] [ info] [ctraces ] version=0.2.5
[2022/11/17 15:43:27] [ info] [input:dummy:dummy.0] initializing
[2022/11/17 15:43:27] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2022/11/17 15:43:27] [ info] [sp] stream processor started
[2022/11/17 15:43:27] [ info] [output:forward:forward.0] worker #0 started
[2022/11/17 15:43:27] [ info] [output:forward:forward.0] worker #1 started
[2022/11/17 15:43:49] [error] [output:forward:forward.0] ACK: mismatch received=5f2c56f5ab4e1eb0e0c7dd4220460890, expected=(7a03a12cd32b97ce4d1722f72d61051c)
[2022/11/17 15:43:49] [error] [output:forward:forward.0] ACK: mismatch received=7a03a12cd32b97ce4d1722f72d61051c, expected=(5f2c56f5ab4e1eb0e0c7dd4220460890)
```

I'll make a note of this and change my configuration to use `TCP` in an effort to get reproduce your results before switching topics.

**Comment by leonardo-albertovich** [comment]
I modified my configuration files to look like this : 

```
# client
[SERVICE]
  flush 1
  log_level debug

[INPUT]
  Name dummy
  Tag dummy.log
  Rate 10
  #Samples 10

[OUTPUT]
  Name forward
  Match *
  host 127.0.0.1
  port 9555
  Require_ack_response True
  retry_limit false
  workers 1
```

```
#server
[SERVICE]
  flush 1
  storage.sync normal
  storage.path /tmp/storage

[INPUT]
  Name forward
  listen 127.0.0.1
  port 9555
  storage.type filesystem
  buffer_chunk_size 1000000
  buffer_max_size 500000

[OUTPUT]
  Name stdout
  Format json_lines
  Match *
```

And I see the ACKs being received : 

```
[2022/11/17 16:04:10] [debug] [output:forward:forward.0] send options records=10 chunk='25d38e48ee7208520dbaf1adcf21f116'
[2022/11/17 16:04:10] [debug] [output:forward:forward.0] protocol: received ACK 25d38e48ee7208520dbaf1adcf21f116
```

I still have to raise the worker count to determine if the mixed ACK is limited to UDS or a global issue but that's not the point in this particular test.

Any input would be highly appreciated.

**Comment by epsteina16** [comment]
> @epsteina16 quick question, did you modify your test to use unix sockets in order to make it easier to reproduce?
No, we use only use unix sockets to send logs via Forward to Fluent Bit. This is done to avoid hitting the max TCP connections on our servers.

**Comment by epsteina16** [comment]
flb_io_net_write() is used to send the ACK back in in_forward/fw_prot.c 
I will try your patch.

**Comment by epsteina16** [comment]
@leonardo-albertovich I think I maybe was not clear where my issue was. I think there is a regression in the forward input plugin that causes the file descriptor to be removed from the event loop after the first ACK is sent. In my situation I have a C++ forward client that I use to send logs to fluent bit over a Unix Domain Socket. For the purpose of making this reproducible, I turned this into using two Fluent Bits. The issue is in the receiver, i.e. the one with the input forward plugin.

I tried removing flb_net_socket_nonblocking call here: https://github.com/fluent/fluent-bit/blob/master/plugins/in_forward/fw.c#L230
and saw the same issue.

My workaround (which works) is adding 
'mk_event_add(in->config->evl, conn->connection->fd, FLB_ENGINE_EV_CUSTOM, MK_EVENT_READ, &conn->connection->event);' here: https://github.com/fluent/fluent-bit/blob/master/plugins/in_forward/fw_prot.c#L168
Which adds back the file descriptor to the event loop.

**Comment by leonardo-albertovich** [comment]
The removal of the `flb_net_socket_nonblocking` call was only meant to be applied in the output plugin. I understand what you are saying but I'd like to be able to reproduce the bug which is not happening to me. 

Any ideas?

**Comment by epsteina16** [comment]
I tried the configuration files you shared and can confirm this behavior does not exist with TCP.

**Comment by leonardo-albertovich** [comment]
Could you help me reproduce it using UDS? I'm currently using the same configuration files except instead of `host`/`listen`/`port` I'm setting `Unix_Path`  (it's basically your configuration file) but once I patched `out_forward` I stopped seeing the issue altogether.

**Comment by epsteina16** [comment]
Does the forward output plugin try to reuse the same connection?

**Comment by leonardo-albertovich** [comment]
That's what I understand but [just for unix sockets](https://github.com/fluent/fluent-bit/blob/master/plugins/out_forward/forward.c#L885). 

If you look at [this](https://github.com/fluent/fluent-bit/blob/master/plugins/out_forward/forward.c#L1320) section of the code you'll notice that an outgoing connection is only requested if the plugin is running in TCP mode.

And then you can check any of the references to the `io_write` pointer pass both the connection pointer which is ignored when working in UDS mode and the unix socket connection fd (ie. https://github.com/fluent/fluent-bit/blob/master/plugins/out_forward/forward.c#L1145)

**Comment by leonardo-albertovich** [comment]
> I ask because our implementation does not try and establish a new connection unless the connection is broken. I could see why this behavior would not exist in a setting where the sender always made a new connection, since the issue is that the Forward server (forward input plugin) is not paying attention to the file descriptor after an ACK is sent.

That's not what I'm saying though, the only whenario when having a single connection is a problem is having multiple workers sending data through the same socket. That's when the ACKs get mixed up and the reason why it doesn't happen when running in TCP mode. 

But that's really not related to your issue.

Could you try to reproduce your issue with fluent-bit once you apply that patch I mentioned to the output plugin? I will send a PR to fix that soon but I want to be sure before I do.

**Comment by epsteina16** [comment]
I tried the patch to the output plugin. It did not solve the issue for me. I still see:
`[2022/11/17 13:57:10] [error] [output:forward:forward.0] could not write forward header`

**Comment by leonardo-albertovich** [comment]
I'll create a branch with the patched version tomorrow morning just to be sure we are testing the same thing.

**Comment by leonardo-albertovich** [comment]
I just sent PR #6417 I'm still doing QA on it but it should fix both the non blocking socket issue as well as the concurrency issue in the output plugin. It's chunkier than I'd like and most definitely not the best approach but it should fix the issue.

The main changes that I wanted you to do to your version are changing `fd = flb_net_socket_create(AF_UNIX, FLB_TRUE);` to `fd = flb_net_socket_create(AF_UNIX, FLB_FALSE);` in line 802 and removing `    flb_net_socket_nonblocking(config->unix_fd);` in line 818.

Feel free to test the code in the PR, it shouldn't cause any issues and if you want to be extra safe you can set `workers 0` in the output plugin so you get the simplest version of the interaction between those. 

Feel free to ping me on slack if you want to have a more fluid conversation in order to help me reproduce your issue.

**Comment by leonardo-albertovich** [comment]
Good news everyone!

First of all, I was able to reproduce the issue and have a [PR](https://github.com/fluent/fluent-bit/pull/6425) to fix it on the way (which I would appreciate any feedback on). 

It turned out that this defective behavior was exposed by [this](https://github.com/fluent/fluent-bit/pull/6340/commits/f254050296c0f9bf5bc813a16fe92d0caa86d065) when I accidentally 
assigned the value used for `FLB_IO_ASYNC` to `FLB_INPUT_NET_SERVER` which I had to add in order to differentiate input plugins that received information starting a listener from 
those that issued outgoing connections (in order to properly let users know that they need to provide a certificate and private key for those that start listeners if they want to use TLS).

That mistake I made in PR #6340 also exposed an error documented in [issue 6404](https://github.com/fluent/fluent-bit/issues/6404).

When PR #6415 was merged downstream connections stoppped having the `FLB_IO_ASYNC` flag which caused `flb_io_net_write` to go through `net_io_write` instead of `net_io_write_async` and since
I was working on master I couldn't see the error because it simply didn't happen in my system.

Now, the original behavior was introduced in [this](https://github.com/fluent/fluent-bit/commit/b06f64e12028843cccaab192344157f780288d2e) which makes sense since at the time the only ones
using that were output plugins and they knew what they wanted to do and when but that won't do the trick anymore.

The reason I was set on reproducing the issue rather than just re-registering the connection in that input plugin was that I thought this could be a systemic issue that we needed to erradicate 
rather than work around and I'm glad I did because even though PR #6415 means the behavior is not exposed anymore it doesn't mean we won't want to be able to enable that in the future (in fact, 
we will).

As a side note, I'm fairly sure that the TLS layer has the same issue, it's quite clear if you look at `io_tls_event_switch`, `flb_tls_net_read_async`, `flb_tls_net_write_async` and 
`flb_tls_session_create` but I don't want to rush or spend the rest of my Sunday fixing that. I guess once someone reviews PR #6425 and validates the findings / approach we can apply the 
same concept to the TLS layer. (maybe we should simply add a secondary event structure to the connection structure and add a set of functions to backup / restore so we don't have to repeat that 
logic in the TLS layer).

I'd really appreciate it if you could take a few minutes to review this information and the PR so we can be sure there aren't any loose threads.

Regards.

**Comment by epsteina16** [comment]
Thank you @leonardo-albertovich
I reviewed the PR and this analysis. The PR fixes the regression for me and I reviewed the code path as well. This is a more sufficient fix then my workaround. I agree that the same issue exists in TLS but have not tested that.

**Comment by leonardo-albertovich** [comment]
Thanks for taking the time to review everything, I'll try to get someone to double check it and then I'll do the same for TLS (for which I think I should be able to reuse the test case with tls on) and make a PR for that so it's included in the next release.

**Comment by leonardo-albertovich** [comment]
I have verified that the same issue is present in TLS (making the required changes to the code to be able to run the input plugin in thread mode with asynchronous I/O and using socat as a UDS to TCP+TLS transparent proxy) and also confirmed that the same approach would work so a fix for that is also on the way.
