### ISSUE TITLE
Logs: add support for metadata in Fluent Bit internal structure

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#6666]
There are many use cases where having logs with metadata separated from the record is highly necessary. 

We are opening this issue to brainstorm and propose solutions to implement a new Log format that's capable to handle metadata. 

Our current internal representation of a record is as follows:

```
[TIMESTAMP, {RECORD}]
```

On this representation, `TIMESTAMP` is already a type of metadata; we are looking to extend this with the less-invasive changes possible; a proposal would be:

```
[[TIMESTAMP, {METADATA}], {RECORD}]
```

#### Priorities

1. Internal log representation with metadata support: Fluent Bit
2. API to modify metadata
3. Plugins support with metadata, e.g: stdout, forward (input / output)
4. Fluentd compatibility (we don't expect Fluentd to support metadata, but we must offer a compatible mode)

**Comment by edsiper** [comment]
cc: @leonardo-albertovich

**Comment by cosmo0920** [comment]
I like this idea. 
Because some of inputs need to store their metadata information with "the unified way".
Currently, we need to determine some of special keys such as `@meta` inside records to handle metadata.

One of the candidates of actual metadata usage is a plugin for endpoints of Elasticsearch/OpenSearch Bulk API.

**Comment by cosmo0920** [comment]
> 4\. Fluentd compatibility (we don't expect Fluentd to support metadata, but we must offer a compatible mode)

For requesting on this specification on Fluentd side, we need to revised edition of forward protocol v2 or something like that.

**Comment by nokute78** [comment]
```
[[TIMESTAMP, {METADATA}], {RECORD}]
```
We need to create a new API and modify all native/go plugins.
Because every plugins implement following routine processing.

## Input plugin

1. Create msgpack array
2. Push timestamp as ext format.
3. Encode record as a second element of the array.

## Filter/Output plugin

1. Check if incoming msgpack data is an array 
2. Pop timestamp from the array. Timestamp should be integer or ext format.
3. Decode second element as a record.

**Comment by Syn3rman** [comment]
Wouldn't it be better to have it as an optional third field?

**Comment by nokute78** [comment]
> We need to create a new API and modify all native/go plugins.

I proposed a patch #6694 to create a new decoder API for filter/output plugins.
It also supports changing event format since the API hides decoding way from plugins.

**Comment by edsiper** [comment]
note: the goal of the change is backward compatibility. 

@leonardo-albertovich thoughts on comments and #6694 ?

**Comment by nokute78** [comment]
Fluent-bit v2.1.0 may sent a new format using out_forward and it may affect fluentd and old fluent-bit.
https://github.com/fluent/fluent-bit/issues/7240

**Comment by PettitWesley** [comment]
So the goal here is to save space when storing logs? Since metadata might all be the same for chunk? Otherwise if its just a format change, seems not worth it.

**Comment by amarora-tibco** [comment]
Is this change implemented? I need to add some fields in metadata, like name of index. Scenario is my events are flowing to Open search. And there are different types of event, hence different index, hence took decision to add index_name in event as new field using lua script, and open search plugin is using that for index. But using this, this field (index_name) is also getting indexed in open search. It would be better if this can be added as meta data in event (like tag) which are used to take decision can be accessed like variable, but eventually discarded and not getting ingested in Open search
