### ISSUE TITLE
tail plugin read file don't keep offset

### ISSUE THREAD

**Issue by Barbazoo** [fluent/fluent-bit#689]
**Is your feature request related to a problem? Please describe.**

Since the fluent-bit tail plugin reads the file, it will read from the file header.I used fluent-bit to configure a db parameter to record the offset of the file. Now because of the large amount of log files, the io operation of the db file reaches 40 times per second, causing the io wait of the cpu to be relatively high. What parameters can control the fluent-bit read file only reads the current file append similar to linux's tail -f mode , so I can directly remove the db file to reduce the cpu io wait time, thanks!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by edsiper** [comment]
The database file is backed by SQLite, in order to control the sync mode and it penalties, please refer to the following links:

- https://fluentbit.io/documentation/0.13/input/tail.html  (DB.Sync)
- https://www.sqlite.org/pragma.html#pragma_synchronous

Basically you can choose between: Extra, Full, Normal, Off

Now about 'tail -f' real mode is something pending to be implemented shortly.

**Comment by Barbazoo** [comment]
The version I am using is 0.12. I just found a bug fix.
Https://github.com/fluent/fluent-bit/issues/474
In fact, what I want is this effect. By default, I only read and write from the end. I am going to try it up to 0.13.

**Comment by edsiper** [comment]
Closing this one as a dup of #474
