### ISSUE TITLE
Exec input plugin not sending netifyd logs as expected

### ISSUE THREAD

**Issue by Balukn11** [fluent/fluent-bit#6947]
## Bug Report

**Describe the bug**
When netifyd unix socket logs are read using the exec input plugin, the contents read are stored in the buffer and only getting sent to the elasticsearch output plugin when the fluent-bit service is stopped. Untill then it is just collecting the logs and storing it in the buffer. How can i configure the fluent-bit input to send the logs as soon as it reads the input?

**Expected behavior**
The netifyd logs will be written to the socket in the interval of few nano seconds. Such that the exec input plugin must run the command to read the logs present in the socket and send it to elasticsearch without any delay. The contributors can assume something like mpstat command in linux. 

**Your Environment**

* Configuration:

[INPUT]
    Name          exec
    Tag              exec_netifyd
    Command   nc -U /var/run/netifyd/netifyd.sock
    Oneshot      true

[OUTPUT]
    Name es
    Match *
    Host xx.xxx.xxx.xxx
    Port 9200
    Logstash_Format On
    Index test4

* Operating System and version: Ubuntu 22.04

**Comment by leonardo-albertovich** [comment]
The problem is that this plugin spawns the program and then reads until the program exits which is not your case.

The easiest way to make it work in this case is to add `threaded on` to the input plugin which means that plugin will keep running that busy loop in its own thread ingesting those lines and letting the main thread filter and route the data to the output plugin instances.

**Comment by Balukn11** [comment]
Thanks @leonardo-albertovich. It's working!
