### ISSUE TITLE
flb_sds_printf() doesn't increase buffer to accommodate copied string in some cases

### ISSUE THREAD

**Issue by zhenyami** [fluent/fluent-bit#7042]
## Bug Report

**Describe the bug**
While investigating a problem with auth in the BigQuery output plugin, I noticed that function `flb_sds_printf()` doesn't work properly if the copied (printed) string is the same size as the target `flb_sds_t` buffer – the last character of the string gets truncated.

```c
flb_sds_t flb_sds_printf(flb_sds_t *sds, const char *fmt, ...);
```

Per my understanding of the `flb_sds_printf()` code, it's supposed to resize the target buffer to accommodate the whole copied string. However, this doesn't happen if the buffer and the copied string have the same length: 
* https://github.com/fluent/fluent-bit/blob/master/src/flb_sds.c#L437

This function uses `vsnprintf()`. From its [man page](https://man7.org/linux/man-pages/man3/vsnprintf.3.html):
> int vsnprintf(char *str, size_t size, const char \*format, va_list ap);
> 
> The functions _snprintf()_ and _vsnprintf()_ do not write more than _size_ bytes (including the terminating null byte ('\0')).  If the output was truncated due to this limit, then the return value is the number of characters (excluding the terminating null byte) which would have been written to the final string if enough space had been available.  Thus, **a return value of _size_** or more means that the output was truncated.

I created some tests to validate this: https://github.com/fluent/fluent-bit/pull/7041.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**
Function `flb_sds_printf()` copies the whole string to the buffer.

**Screenshots**

**Your Environment**

* Version used: 1.9.9
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): 
* Server type and version: AWS EC2
* Operating System and version: Amazon Linux
* Filters and plugins:

**Additional context**

**Comment by zhenyami** [comment]
This is related to a common function used in many places within Fluent Bit. Therefore, I would like to check with other developers whether my understanding of the expected behaviour of `flb_sds_printf()` is correct. 🙇

**Comment by edsiper** [comment]
@leonardo-albertovich or @nokute78 can you please take a look at this ?

**Comment by leonardo-albertovich** [comment]
I think @zhenyami is correct in that there is a bug in that function because `flb_sds_avail` returns the result of the subtraction of the allocated size minus the current length without taking in consideration the additional null character so the actual line that causes the original issue in this case would be 420 which should be `<=` instead.

Of course with this approach line 437 should  be `>=` but honestly, I think the real issue is we are trying to estimate the required size by measuring the format string which in many cases would not reflect the real space needed (ie. `%016x`) and even though the usual "calling vsnprintf with NULL as output buffer and zero as size to get a proper required size" is more expensive I would argue that by definition this is an "expensive" function which involves memory manipulation which means we should favor easy to read and safe code.

**Comment by zhenyami** [comment]
Closing as it was handled in a different PR.
