### ISSUE TITLE
Configurable and restricted chunk size

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#7331]
Historically Fluent Bit group records in a Chunk, which size is soft-limited to 2MB, but nothing restricts a plugin ingests a 10M content into a Chunk. The issue with this scenario is when an output plugin tries to process that Chunk, and the remote endpoint might not support a considerable payload. Many users have asked to have a way to configure the chunk sizes to avoid this.

What I think should be implemented is the following:

- Configurable chunk size: note this is for __advanced__ users that knows what they are doing. 2MB has worked fine for years.
- Restrict chunk size: if a payload of 10M is ingested, split the content in parts of 2M (or the size set by the configurable chunk size).

Another option to solve the problem of sizes hitting the output destination is to implement a logic in which each route, besides the chunk and the payload, keeps an offset and tries to flush N times as required by using an offset (this design might need a document).

all the options might make it work but there are pros and cons, I would love to have a way where users cannot do mistakes with whatever is the best option to follow.

**Comment by leonardo-albertovich** [comment]
Last week I proposed a change to [input_chunk_get](https://github.com/fluent/fluent-bit/blob/master/src/flb_input_chunk.c#L1234) to enforce such a limit. 

This doesn't contemplate the use case where a plugin calls `input_chunk_append_raw` with an extremely large packet that exceeds the limit but that case (which would involve splitting a chunk) could be implemented in [input_log_append](https://github.com/fluent/fluent-bit/blob/master/src/flb_input_log.c#L65).

Overall I agree that enforcing a limit even if it's the current 2MB one rather than relying on flush based locking would be preferable, especially if / when we incorporate the circuit breaker feature.
