### ISSUE TITLE
Enhance fluent-bit Lua API to allow enqueueing records for a future timestamp

### ISSUE THREAD

**Issue by tarruda** [fluent/fluent-bit#7344]
The idea is to add a single builtin function to the Lua environment that has 3 arguments:

- record object
- time delta: milliseconds in the future where the record would be added to the pipeline
- tag: optionally push the record under a different tag

This enhancement would allow Lua scripts to have much more power than they currently do. 

The main current use case for this enhancement is allowing "aggregate" and "sampling" processing rules to work without in_dummy configuration hacks, but this would enable the full "stream processing" capabilities on Lua scripts.

**Comment by leonardo-albertovich** [comment]
If I'm correct the only place where fluent-bit executes LUA code is `filter_lua` and in this particular use case the script returns the timestamp as part of its result.

Could you elaborate?

**Comment by edsiper** [comment]
maybe is this something that can be implemented at the new processors level in Fluent Bit ? where we can have some buffering capabilities and timers associated ? (we need more thinking...)

**Comment by leonardo-albertovich** [comment]
There are two issues there, the first one being that the LUA script is running in a filter which regardless of if we expose the "emitter" feature to it or if we put it in a processor it will still depend data input for activation.

The second issue is building on top of LUA rather than something better suited / future proof such as go but that's a more nuanced opinion than anything.

So maybe we need a new category for this type of pipeline component that can set up a "flush" timer of its own.
