### ISSUE TITLE
filter.geoip2 broken since 2.1

### ISSUE THREAD

**Issue by genofire** [fluent/fluent-bit#7351]
## Bug Report

**Describe the bug**

**To Reproduce**
- Upgrade from 2.0.11 to 2.1.x
- Example log message if applicable:
```
Log event encoder error : -12
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 2.1.2
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): 
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

---
if really needed i give more information, but after downgrade works well ... so problem should not been in my setup.

**Comment by leonardo-albertovich** [comment]
Hi @genofire, the problem is not your setup, we'll look into it and get back to you. 

Thanks for taking the time to report the issue.

**Comment by migueltoroaguilar** [comment]
Hi @leonardo-albertovich  I have been facing the same issue, i thought there was a misconfiguration from my side. on 2.0.11 worked fine. this is my status:

`[0] locotest: [[1683834240.700053339, {}], {"remote_addr"=>"8.8.8.8"}] 
[error] [filter:geoip2:geoip2.2] Log event encoder error : -12`

**Comment by migueltoroaguilar** [comment]
even the log looks odd and different, on v 2.0 the logs where inside the { } and now they are empty

**Comment by leonardo-albertovich** [comment]
Thanks for reporting the incident @migueltoroaguilar, the more information we have the better.
The log structure in your case is not empty, in that example you shared `1683834240.700053339` is the timestamp, `{}` is the metadata (which for most cases will be empty) and `{"remote_addr"=>"8.8.8.8"}` is the data (which could be incomplete, I'm not familiar with that plugin).

This issue is still in our work queue and someone from the team will take care of it as soon as possible.

**Comment by leonardo-albertovich** [comment]
@cosmo0920 fixed the issue, I don't have an ETA for the next release yet but rest assured that this will be included and if you want to test it as soon as possible you could run the nightly build (well, starting tomorrow I guess).
