### ISSUE TITLE
Make Fluent Bit packageable for ROS

### ISSUE THREAD

**Issue by Minipada** [fluent/fluent-bit#7543]
**Is your feature request related to a problem? Please describe.**
The request is to be able to use Fluent Bit, especially its API into [ROS](https://www.ros.org/). I am not a ROS maintainer myself but have talked to some already.

To give some context,  _The Robot Operating System (ROS) is a set of software libraries and tools that help you build robot applications. From drivers to state-of-the-art algorithms, and with powerful developer tools, ROS has what you need for your next robotics project. And it's all open source._

ROS uses package.xml files for each of its package, that look like this

```xml
<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>package_name</name>
  <version>1.2.3</version>
  <description>Description</description>
  <maintainer email="maintainer@gmail.com">FirstName LastName</maintainer>
  <license>MPL-2.0</license>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>

  <depend>rclcpp</depend>
</package>
``` 

One of the ROS tools is rosdep, which allows to install its dependencies listed in the package.xml and make it easy to ship software. All dependencies are found and installed in the built process and installed with the package provider (apt, pacman...). Those dependencies are referenced on the [rosdistro](https://github.com/ros/rosdistro) repository. Each ROS distribution has its own reference. It's a sort of a match between the name written in the package.xml and the package provided by the repositories. Taking Ubuntu as an example, note that only packages from Ubuntu and ROS repositories can be fetched with rosdep, see [here](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#expected-rosdep-sources).

I create this issue because I am working on a [data collection framework for ROS 2](https://github.com/Minipada/ros2_data_collection), using Fluent Bit in the backend and I would like to have Fluent Bit installed easily as a dependency to one of my package.

Even though Fluent Bit current installation is straight forward, it requires to add the Fluent it repository and then execute apt install, making it non compliant with ROS installation.

**Describe the solution you'd like**
Ideally, if Fluent Bit was available on the Ubuntu repository, directly with apt-get, this would solve everything.

The ROS maintainer I talked to supposes the reason it is not there is because of the 3rd party dependency Fluent Bit has, but confirmation from a Fluent Bit maintainer would be great.

**Describe alternatives you've considered**
I discussed with ROS maintainers, an alternative would have been to use a ROS vendored package, another way of packaging 3rd party packages like Fluent Bit but it cannot be done since Fluent Bit has 3rd party dependencies inside the repository.

**Additional context**

I am willing to support you, hands-on if I can but I would need feedback first.

Thanks

**Comment by patrick-stephens** [comment]
We cannot comment on adding Fluent Bit to Ubuntu repos, I think that's a separate ask.

Fluent Bit itself is provided as a single package in its own repository with dependencies on just Ubuntu repositories: https://github.com/fluent/fluent-bit/blob/master/packaging/distros/ubuntu/Dockerfile
For older targets we have to bring in a apt.kitware.com version of cmake that is more recent but otherwise it should just be standard packages from Ubuntu repositories defined in the container image used to build it.

Realistically the only good way I see here for ROS is to provide it via the rosdep/rosdistro process directly, i.e. replicate the build or push the package directly to it. What third party dependencies would prevent this? As I say, all should be just Ubuntu ones.

**Comment by nuclearsandwich** [comment]
Thank you for taking a look @patrick-stephens. I'm one of the member of the ROS infrastructure and release engineering teams. The third party dependencies are not external to the fluent-bit package, if they were that would actually match our process more readily since we could work to package those dependencies first before packaging fluent-bit. Like Debian, we don't permit packages to vendor or bundle dependencies and instead require them to use the system version of the library, or the version explicitly vendored in ROS if there is not yet a package in our upstream distribution.

fluent-bit appears to have quite a few third party libraries bundled in https://github.com/fluent/fluent-bit/tree/master/lib and a quick scan of the build scripts does not suggest to me that there is a way to use system libraries instead of those, which is a blocker for us and other projects like Debian and Fedora which have policies against bundling libraries: https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling

If I've missed something and it is possible to use external copies of these libraries, that's great! @Minipada can make sure that the ROS builds are configured to do so.
If it's not currently possible to use external libraries instead of the bundled ones, would this project accept contributions which make it possible?

**Comment by patrick-stephens** [comment]
Thanks @nuclearsandwich for the context 

The internal dependencies are vendored ones - there are [some PRs](https://github.com/fluent/fluent-bit/pull/7286) looking at using system ones but primarily the intention was Fluent Bit is self contained and tries to manage all its dependencies. Occasionally there are issues or incompatibilities which is why I think this was done although it's not a full static build (e.g. libc).

Now, saying that I think we do try to link statically as much as we can (sometimes it is not possible or not available). If we know which libraries that are the problem then can look at them - do we have this information?

@leonardo-albertovich may be able to provide some more insight but I understand the issue now - the problem is including additional libraries that are already provided separately. We can also look at a static build which should be supported but it not used for official releases.

**Comment by patrick-stephens** [comment]
I think supporting the possibility of using system libraries is an option but it may take a bit of tweaking of CMake to get it to pick them all up (ignoring Windows/macOS). However it seems a reasonable request to me although contribution would speed it up.

**Comment by Minipada** [comment]
Thanks @nuclearsandwich for jumping in and clarifying.

Currently I am using a shared linking, see https://github.com/Minipada/ros2_data_collection/blob/humble/dc_destinations/CMakeLists.txt#L76, it uses the libfluent-bit.so that I compile 
Then I only include the default file: `#include <fluent-bit.h>`. I did not list which internal library I use when doing so. Like @nuclearsandwich mentioned msgpack, some other libraries, like mk_core, cfl are mentioned in the include but I did not go through the whole tree to know.

I like the idea of having the flexibility to using system libraries if available, effort to which I would gladly contribute to.

While I currently don't use many fluent bit C api calls, I think it would be good to have them working on the long term, which makes me realize we would need to handle all libraries listed here https://github.com/fluent/fluent-bit/tree/master/lib .
