### ISSUE TITLE
TLS is not supported when proxy is enabled

### ISSUE THREAD

**Issue by SharathSunny** [fluent/fluent-bit#7554]
In a container env, I am trying forward logs to a remote ec-2 (fluentbit server is on). Now I have enabled both proxy and tls through http plugin.
````
[output]
    Name http
    Match *
    Host <ec-2_host>
    Port <port>
    Retry_Limit False
    tls  On
    tls.verify Off
    tls.debug 4
    tls.ca_file /fluentbit/cert/ca.crt.pem
    tls.crt_file /fluentbit/cert/client.crt.pem
    tls.key_file /fluentbit/cert/client.key.pem
    tls.key_passwd Server1!
    Proxy http://<proxy>:<port>
````
Error msg found
````
[tls] error: unexpected EOF
[2023/06/05 05:16:25] [error] [output:http:http.1] no upstream connections available to <proxy>:<port>
[2023/06/05 05:16:25] [ warn] [engine] failed to flush chunk '1-1685942144.693892904.flb', retry in 51 seconds: task_id=0, input=tail.0 > output=http.1 (out_id=1)
````
I am not sure weather I have configured it wrong or is that is not supported, I have found a similar issue with https://github.com/fluent/fluent-bit/issues/1323 but there is no solution related to this (suggested to use fluentd). When I use proxy without TLS it is working as expected and vise versa it is working with tls (tls on with out proxy).
This is some what critical can you plz look into it as soon as possible

**Comment by SharathSunny** [comment]
@edsiper any update on this

**Comment by SharathSunny** [comment]
@edsiper it is bit imp can you look into this.

**Comment by patrick-stephens** [comment]
I have no idea I'm afraid.
You have not specified which version of Fluent Bit (please use the issue template to capture all this, particularly if it is urgent as you say otherwise it wastes time trying to get it). Have you tried the latest version?

Looking at the docs it says to set the env var: https://docs.fluentbit.io/manual/administration/http-proxy

In fact, looking at the docs it says not to do what you've done and use the HTTP_PROXY approach I think - it seems to imply this is the only way to do HTTPS which marries up with what you're seeing. I would suggest trying that as documented.
![Screenshot from 2023-06-26 16-33-13](https://github.com/fluent/fluent-bit/assets/6388272/ea2fa635-77ed-40ec-bdfc-9672d8426661)
```
Note: The [HTTP output plugin](https://docs.fluentbit.io/manual/pipeline/outputs/http) also supports configuring an HTTP proxy. This configuration continues to work, however it should not be used together with the HTTP_PROXY or http_proxy environment variable. This is because under the hood, the environment variable based proxy configuration is implemented by setting up a TCP connection tunnel via [HTTP CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT). Unlike the plugin's implementation, this supports both HTTP and HTTPS egress traffic.
```
