### ISSUE TITLE
Logs continuity Issue when one of the Output is offline in multi-output fluent-bit pipeline.

### ISSUE THREAD

**Issue by karan56625** [fluent/fluent-bit#7658]
**Is your feature request related to a problem? Please describe.**

Currently, when utilizing multiple outputs in Fluent Bit and encountering an offline status of one of the outputs, Fluent Bit will pause the tail input plugin once the buffer reaches its capacity. The input remains halted until the offline output becomes available. However, a pertinent question arises: what if the offline output never becomes available?

The objective is to ensure high availability of logs in the event that one of the outputs goes offline. In order to achieve this, it is necessary to stop the input only if all outputs are offline. Thus, Fluent Bit should continue processing and forwarding logs as long as at least one output is online, even if certain outputs remain inaccessible.

**Describe the solution you'd like**

One possible solution is to implement individual buffers for each output. In this approach, if an output goes offline, the data intended for that output will be stored in its corresponding buffer, up to the defined buffer size. However, the other outputs will continue receiving data without any interruption or issue. By implementing separate buffers for each output, the high availability of logs can be maintained, ensuring that data is not lost even when certain outputs are temporarily unavailable

**Describe alternatives you've considered**

There may exist several other alternatives for this situation. Essentially, the requirement is to ensure a high availability of logs in the event that one of the outputs is offline.

**Additional context**

**Comment by adiforluls** [comment]
cc: @edsiper @leonardo-albertovich

**Comment by adiforluls** [comment]
To add to this, the current mechanism has mapping as I understand between buffers and input. It does not take into account that I might be running multiple log stores just for this scenario where one of the outputs might be down for a long time and I'd want that logs should find their way to the available outputs. In kubernetes, there's a high probability of losing a lot of container logs because of pausing for a long time due to log rotation.

If it's possible to also be able to form mapping/relation between output and buffer optionally, such that I can enter how much I want to store for an output before logs get flushed, we might get something but need more thoughts. But mostly want to highlight that back pressure handling today can be problematic for some inputs so need a smarter mechanism that can help minimise log loss and doesn't affect availability in case of BackPressure.

**Comment by adiforluls** [comment]
Also looping in @patrick-stephens

**Comment by dmpe** [comment]
I think I am also hitting this issue. I have 2 opensearch instances, and 1 of them has stopped working for several days, and it will take some days to fix it. What i also observe is that logs are not being send to the opensearch instance which is working - which creates a question if it is really like that or there is some fluent bit option to skip the OS instance which is not working.

I would avoid to deploy 2 fluent bit instances (which is of course possible as well)

**Comment by leonardo-albertovich** [comment]
Could you share your configuration file @dmpe?

**Comment by dmpe** [comment]
Hi @leonardo-albertovich, 

I am sorry i should correct myself. It is not 2 servers that I have in a single fluent bit configuration file, but rather 3 OpenSearch servers (please, dont ask why :). 

Let's say for the moment that 2 of them are working (SERVER1+SERVER3) properly while 3rd one (SERVER2) is not:

Applications are writing their logs and SERVER1 gets all of them according to the `Match`. 
Then, different applications are supposed to send their logs into SERVER2 - and that fails. Reason being is that SERVER2 is not working either at all, or properly - that does not matter, let's say server has been deleted and it will be rebuild within few days. 

Now, the real issue that I have lies with Server3 - in this case I would expect that `fluentbit` ignores/skips SERVER2 and goes directly to the SERVER3 - i.e. a bunch of different logs are processed and would be send to SERVER3 because it is working just fine. However, that does not happen. The logs are not delivered to Server3, even though I would expect them to be.

I have already confirmed that configuration on the server side has not been changed, e.g. passwords are ok, Firewall rules are ok, enough Disk space... 

Let's assume also for the moment, that Server1 and Server3 are 1:1 same - they have just a different URL (and IP address behind them). 

```
   [OUTPUT] # This server is always available, so never any issues to send logs here
        Name opensearch
        Match apps_test1.*
        Host            SERVER1       
        Port            9200
        HTTP_User       ${LOGGING_USER}
        HTTP_Passwd     ${LOGGING_PASS}
        Logstash_Format On
        Logstash_Prefix test1
        Replace_Dots On
        tls on
        tls.verify Off
        Retry_Limit False
        Buffer_Size False
        Generate_ID On
        Workers 3
        Trace_Error On
        Suppress_Type_Name On

    [OUTPUT] # This server is NOT available for the last few days, so FluentBit cannot reach it
        Name opensearch
        Match apps_test2.*
        Host            SERVER2
        Port            9200
        HTTP_User       ${LOGGING_USER}
        HTTP_Passwd     ${LOGGING_PASS}
        Logstash_Format On
        Logstash_Prefix test2
        Replace_Dots On
        tls on
        tls.verify Off
        Retry_Limit False
        Buffer_Size False
        Generate_ID On
        Workers 3
        Trace_Error On
        Suppress_Type_Name On

    [OUTPUT] # This server is available, so never any issues to send logs here. But
             # what really happens is that fluentbit only sends logs to the SERVER1 (correctly). 
             # SERVER2 is ignored (correctly), because it is down. 
             # And where the issue really lies is SERVER3 where I would expect that logs can be forwarded to
             # but it does not happen, unfortunately. 
        Name opensearch
        Match apps_test3.*
        Host            SERVER3
        Port            9200
        HTTP_User       ${LOGGING_USER}
        HTTP_Passwd     ${LOGGING_PASS}
        Logstash_Format On
        Logstash_Prefix test3
        Replace_Dots On
        tls on
        tls.verify Off
        Retry_Limit False
        Buffer_Size False
        Generate_ID On
        Workers 3
        Trace_Error On
        Suppress_Type_Name On
```

>  Thus, Fluent Bit should continue processing and forwarding logs as long as at least one output is online, even if certain outputs remain inaccessible.

THIS would be my expectation as well.


Thank you for looking into this.

**Comment by leonardo-albertovich** [comment]
Could you share the rest of the file as well? The input sections are important and this just doesn't raise any alarms (except maybe you want to be conservative with your workers setting depending on how many CPUs and cores you have at your disposal).

**Comment by dmpe** [comment]
Sure, I have adjusted my previous comment [with a github gist, also including it here.](https://gist.github.com/dmpe/ef0a927184d245fdc9a3700b2246866f)

**Comment by leonardo-albertovich** [comment]
Great, do you happen to have any logs that you could share with us either here or in private? We'll take a look at it but I can't give you an ETA right now.

**Comment by data-dude** [comment]
I just run multiple pipelines.  one goes down the other continues working.
