### ISSUE TITLE
fluent-bit occasionally stops sending logs to Kinesis FIrehose

### ISSUE THREAD

**Issue by dvishniakov** [fluent/fluent-bit#7803]
## Bug Report

**Describe the bug**
On several occasions we've noticed that fluent-bit stopped sending logs to the Kinesis Firehose output.
Output records (and/or) bytes are usually dropped to 0 or very close to it compared to the recent past. At the same time, storage metrics start to increase and don't resolve even if given tens of minutes of even 1h+.

Deleting the pod usually fixes the issue as the new pod starts to log new data and re-tries backup data.

Logs which seems to be related and unique to pods experienced the issue, in order of appearance:
Search pattern: `"aws_*" OR "tls" OR "creds" OR "credentials" OR "STS" OR "role"`
```bash
# a bunch of common logs in various order:
[tls] syscall error: error:00000005:lib(0):func(0):DH lib
[error] [/src/fluent-bit/src/tls/openssl.c:486 errno=32] Broken pipe
[error] [tls] error: error:00000006:lib(0):func(0):EVP lib 
[error] [tls] error: error:00000001:lib(0):func(0):reason(1) 
#

# More unique logs related to the issue
[ info] [aws_client] auth error, refreshing creds 
[error] [aws_credentials] Shared credentials file /<HOME_DIR>/.aws/credentials does not exist 
[error] [tls] error: unexpected EOF
[error] [aws_client] connection initialization error # common
[error] [aws_credentials] STS assume role request failed
```

Potentially transient logs which are present around or between the above lines, or which non-affected container have as well, in no specific order:
```
[error] [aws_client] connection initialization error
[error] [tls] syscall error: error:00000005:lib(0):func(0):DH lib
[error] [tls] error: error:00000006:lib(0):func(0):EVP lib
[error] [tls] error: error:00000001:lib(0):func(0):reason(1)
[error] [/src/fluent-bit/src/tls/openssl.c:486 errno=32] Broken pipe
[error] [/src/fluent-bit/src/tls/openssl.c:433 errno=0] Success
[error] [/src/fluent-bit/src/tls/openssl.c:* errno=104] Connection reset by peer
[error] [/src/fluent-bit/src/tls/openssl.c:* errno=110] Connection timed out
[error] [net] connection #* timeout after 10 seconds to: sts.us-east-1.amazonaws.com:443

[error] [http_client] broken connection to firehose.us-east-1.amazonaws.com:443 ?
and usual lines about unable to send logs, unsuccessful retries, failed to flush chunk, etc
```

Log shipping metrics were nowhere near Kinesis metrics which are visible in AWS Console.

**To Reproduce**
- Steps to reproduce the problem: not sure since it doesn't happens often. 
- One idea could be to temporarily break STS auth for a running app (STS endpoint in container's /etc/resolv.conf?)  and restore if after some time. 
- Could it be AWS API throttling?
- There is hardcoded 60s timeout which fluent-bit's AWS credentials code uses as to when to start refreshing credentials, which could be related here.

**Expected behavior**

Log shipping is resumed or a better error log is produced.

As potentially related suggestion, it would be great to have credentials refresh timeout configurable to start that process earlier than a minute prior to creds expiration as a workaround for long outages.

**Screenshots**

One such pod from August 3, until termination
<img width="1245" alt="Screenshot 2023-08-03 at 16 02 47" src="https://github.com/fluent/fluent-bit/assets/11319948/2128d843-8dc6-496b-8b36-85aa78856ea7">

There were many occurrences of storage metrics increase between August 3rd and 4th, but only one pod got stuck (or wasn't terminated). 

**Your Environment**

* Version used: 2.0.11
* Configuration: Tail input, Kinesis Firehose output
* Environment name and version: Managed Kubernetes, 1.24
* Server type and version:
* Operating System and version: Linux
* Filters and plugins:

**Comment by dvmdb** [comment]
After briefly searching through code, I don't understand how exactly this is implemented:
> * For safety a refresh can be performed only **once**
> * **per** FLB_AWS_CREDENTIAL_REFRESH_LIMIT.

Is it retried only once? I don't see `aws_client->refresh_limit` reset after the expiration, unless it's in a different place

- https://github.com/fluent/fluent-bit/blob/5686334b56ee9d92f0654b0a621113943b175b94/src/aws/flb_aws_util.c#L199
- https://github.com/fluent/fluent-bit/blob/5686334b56ee9d92f0654b0a621113943b175b94/include/fluent-bit/flb_aws_util.h#L98

**Comment by dvmdb** [comment]
It seems that I've narrowed this down to specific details.

### High level

AWS credentials providers are not unlocked due to EC2(IMDS) credential refresh, resulting in stale role credentials, when all of these conditions are true:
- Fluent-bit is running within a **container** on AWS EC2 hosts having [IMDS v2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-metadata-v2-how-it-works.html#) enabled with default settings (hop limit (time to live) of 1). i.e. on EKS.
- Credentials used need to be refreshed periodically, i.e. by assuming a role to access AWS resources (by default it's 1h and I don't see any settings in this repo to modify the duration).
- At least 1 AWS service in Outputs (haven't tried with 0 services) to trigger credentials refreshes. I.e. Firehose.
- All means to refresh credentials (i.e. env, profile, EKS) other than IMDS are broken (not configured), either:
  - a) From the start of fluent-bit (easy to reproduce)
  - b) Right at the moment when fluent-bit refreshes the credentials (for one or a few minutes around temporary credentials expiration time, for example during an outage at AWS, network partition, firewall issue, rbac modifications, etc)

### Low level:

- When [get_credentials_fn_standard_chain()](https://github.com/fluent/fluent-bit/blob/1d83649441e9e9fdbb5ba83bffca11ac4ac7b83c/src/aws/flb_aws_credentials.c#L117-L120) tries EC2(IMDS) provider for the first time [here](https://github.com/fluent/fluent-bit/blob/1d83649441e9e9fdbb5ba83bffca11ac4ac7b83c/src/aws/flb_aws_credentials.c#L95-L96), it goes through  [refresh_imds_v2_token()](https://github.com/fluent/fluent-bit/blob/1d83649441e9e9fdbb5ba83bffca11ac4ac7b83c/src/aws/flb_aws_imds.c#L332-L333), http client's request(), gets available connection with base settings and ultimately calls net_io_read()/recv().
- On the first time this results in expected timeout and message `[ warn] [net] sync io_read #27 timeout after 1 seconds from: tcp://169.254.169.254:80`. At this point, the timeout set in [cb_aws_init()](https://github.com/fluent/fluent-bit/blob/1d83649441e9e9fdbb5ba83bffca11ac4ac7b83c/plugins/filter_aws/aws.c#L164-L169) are still active. With default  host settings, containerized apps are not supposed to access IMDS.
- Soon after an AWS Output plugin is initialized and resets net settings including `base.net.io_timeout`. I.e. Firehose init calls [upstream_set()](https://github.com/fluent/fluent-bit/blob/1d83649441e9e9fdbb5ba83bffca11ac4ac7b83c/plugins/out_kinesis_firehose/firehose.c#L242-L243), [upstream_set_fn_standard_chain()](https://github.com/fluent/fluent-bit/blob/1d83649441e9e9fdbb5ba83bffca11ac4ac7b83c/src/aws/flb_aws_credentials.c#L222-L238), which applies settings from [upstream_net[]](https://github.com/fluent/fluent-bit/blob/1d83649441e9e9fdbb5ba83bffca11ac4ac7b83c/src/flb_upstream.c#L69-L70). This resets `net.io_timeout` from 1 second to 0 (indefinite).
- On the second time when EC2(IMDS) provider gets down fd_io_read()/recv, it never returns because `net.io_timeout` is reset, so the EC2 provider and the standard chain provider are not unlocked
- Subsequent calls to `get_credentials_fn_standard_chain` can't obtain lock on the chain provider, let credentials expire and never refresh them again (can't obtain the lock).

Custom logs with slightly shifted line numbers, showing the reset of `net.io_timeout` from 1 to seconds for the IMDS upstream, as well as for EKS provider upstream. Upstreams and their net's are different objects, according to their addresses.
```
[ warn] /src/fluent-bit/plugins/out_kinesis_firehose/firehose.c:242
	[custom_debug:cb_firehose_init()] BEFORE FIREHOSE AWS PROVIDER UPSTREAM SET, aws_provider=0x7f371804db20
[ warn] [aws_credentials] upstream_set_fn_standard_chain, provider=0x7f371804db20, ins=0x55ee6b837e30
[ warn] /src/fluent-bit/src/flb_output.c:1417
	[custom_debug:flb_output_upstream_set()] before... upstream=0x7f371804def0, for sts.us-east-1.amazonaws.com:443, net=0x7f371804df40, net.io_timeout = 125 seconds
[ warn] /src/fluent-bit/src/flb_output.c:1420
	[custom_debug:flb_output_upstream_set()] after... upstream=0x7f371804def0, for sts.us-east-1.amazonaws.com:443, net=0x7f371804df40, net.io_timeout = 0 seconds
[ warn] /src/fluent-bit/src/flb_output.c:1417
	[custom_debug:flb_output_upstream_set()] before... upstream=0x7f371804e140, for 169.254.169.254:80, net=0x7f371804e190, net.io_timeout = 1 seconds
[ warn] /src/fluent-bit/src/flb_output.c:1420
	[custom_debug:flb_output_upstream_set()] after... upstream=0x7f371804e140, for 169.254.169.254:80, net=0x7f371804e190, net.io_timeout = 0 seconds
[ warn] [aws_credentials] upstream_set_fn_standard_chain end
[ warn] /src/fluent-bit/plugins/out_kinesis_firehose/firehose.c:244
	[custom_debug:cb_firehose_init()] AFTER FIREHOSE AWS PROVIDER UPSTREAM SET
```

### Notes
- EC2(IMDS) provider is created and added to the standard chain [unconditionally](https://github.com/fluent/fluent-bit/blob/1d83649441e9e9fdbb5ba83bffca11ac4ac7b83c/src/aws/flb_aws_credentials.c#L591-L598). I don't see an obvious configuration parameter to skip its creation, so building a custom image without these lines seem like a quick temporary fix. Having a configurable option in the official image would be better, if the actual fix would take much more time. Unless I've missed something.
- Since requirements for `net.io_timeout` are different for each upstream, using config parameter other than 0 to mitigate this issue wouldn't fit all use cases.
- I'll leave suggestion for the best way to reset net settings and preserve some configurable overrides to the fluent-bit developers as  they have better context knowledge than me.
- Tagging @leonardo-albertovich as this might be related to this [change](https://github.com/fluent/fluent-bit/commit/98c03999dd02515f8ed60940c20f591a239f8b4a#diff-29e9ca7aaa7bb37f7a2fe3439c791597bf1856f4d2461071cf69d7645329104cL252-R254)

Also:
- It could be nice to add info level message with obtained credentials expiration value, somewhere around [here](https://github.com/fluent/fluent-bit/blob/5686334b56ee9d92f0654b0a621113943b175b94/src/aws/flb_aws_credentials_sts.c#L780)
- It would be nice to start credentials refresh (FLB_AWS_REFRESH_WINDOW, FLB_AWS_CREDENTIAL_REFRESH_LIMIT) earlier than 60 seconds and even be configurable. This should help to avoid noticing short outages.

**Comment by kclinden** [comment]
I am also seeing this issue on 2.1.10 on Windows Server when the machine is deployed on an vSphere VM. It eventually reconnects, but seems like most of the time I get an error.

**Comment by cdancy** [comment]
Seeing the same on 2.2.0
```
2023/11/29 19:40:27] [error] [http_client] broken connection to logs.us-east-1.amazonaws.com:443 ?
[2023/11/29 19:40:27] [error] [http_client] broken connection to logs.us-east-1.amazonaws.com:443 ?
[2023/11/29 19:40:27] [error] [tls] error: error:00000006:lib(0):func(0):EVP lib
[2023/11/29 19:40:27] [error] [/src/fluent-bit/src/flb_http_client.c:1231 errno=32] Broken pipe
[2023/11/29 19:40:27] [error] [output:cloudwatch_logs:cloudwatch_logs.7] Failed to send log events
[2023/11/29 19:40:27] [error] [output:cloudwatch_logs:cloudwatch_logs.7] Failed to send log events
[2023/11/29 19:40:27] [error] [output:cloudwatch_logs:cloudwatch_logs.7] Failed to send events
```

**Comment by carlosrmendes** [comment]
facing the same with v2.2.1, any feedback?
