### ISSUE TITLE
Build fails on macOS due to invalid use of `strerror_r`

### ISSUE THREAD

**Issue by mavam** [fluent/fluent-bit#7838]
## Bug Report

**Describe the bug**
Compiling on macOS fails with the following error:

```
[ 41%] Building C object src/CMakeFiles/fluent-bit-static.dir/flb_network.c.o
../fluent/fluent-bit/src/flb_network.c:526:17: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
            str = strerror_r(error, so_error_buf, sizeof(so_error_buf));
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

The error seems correct. The signature of `strerror_r` looks like this:

```
     int
     strerror_r(int errnum, char *strerrbuf, size_t buflen);
```

👆 This was taken from the manpage, which says:

```
     The strerror_r() function renders the same result into strerrbuf for a
     maximum of buflen characters and returns 0 upon success.
```

**To Reproduce**
- Checked out `master`
- `cd build`
- `cmake -G 'Unix Makefiles' ..`
- Disable LuaJIT related things via `ccmake .`

**Expected behavior**
A clean build.

**Your Environment**
* Version used: `master` as of 8ae604e5a64fae58c958543a27ea870dda20070d
* Configuration: see above
* Operating System and version: macOS 13.4.1 (Darwin Kernel Version 22.5.0)
* Filters and plugins: all except for LuaJIT

**Comment by leonardo-albertovich** [comment]
I'm a little surprised about it because I built master macOS 13.4.1 a few days ago (both the native m1 binary and the x86_64 binary using rosetta). The only diference is I didn't explicitly select `Unix Makefiles` but I did generate regular makefiles (I just double checked to be sure).

I normally use these options when building in macos `cmake -DFLB_DEV=on -DFLB_LUAJIT=off -DFLB_BACKTRACE=off ../` which I would expect to actually heighten error detection instead of dampening it but the first thing that comes to mind (which I didn't test) is it looks as if in your case there's an implicit `-Werror` which sounds odd since I know for a fact that there are many warnings in other places.

My system is up to date (including xcode) and I used clang 14.0.3, could you  check yours? it doesn't really affect the issue but I'm curious and would like to understand why does it just fail in your system.

In any case, that particular line is wrong but we should be cautious about removing the  `_GNU_SOURCE` definition to switch to the XSI version of it because we don't know if there are any other more sensitive functions that require it which means we should investigate it before.

The alternative path is using preprocessor conditionals to define the result type based on the platform and another preprocessor conditional after the call (because the GNU version might return a pointer to a static buffer instead of writing the message to the user provided buffer in some cases) which is messy.

Would you like to give it a try?

**Comment by mavam** [comment]
> I'm a little surprised about it because I built master macOS 13.4.1 a few days ago (both the native m1 binary and the x86_64 binary using rosetta). The only dif[f]erence is I didn't explicitly select `Unix Makefiles` but I did generate regular makefiles (I just double checked to be sure).

I'm also on a M1. I specified the generator explicitly only because my local environment defaults to Ninja.

That said, I tried this specific build with **Clang 16.0.6** from Homebrew, as opposed to XCode version that is still Clang 14.0.3. I tried your invocation with an older compiler:

```bash
cmake -DFLB_DEV=on -DFLB_LUAJIT=off -DFLB_BACKTRACE=off ..
```

This indeed runs through flawlessly. I tried pinning it down by first removing `-DFLB_DEV=on`, but it still compiled. Then I removed `-DFLB_BACKTRACE=off`, and it still compiles. Only `-DFLB_LUAJIT=off` had to stay to get the build with Clang 14.0.3 working.

For Clang 16.0.6, the above invocation fails with the reported error.

> In any case, that particular line is wrong but we should be cautious about removing the `_GNU_SOURCE` definition to switch to the XSI version of it because we don't know if there are any other more sensitive functions that require it which means we should investigate it before.

Some preprocessor flag avoids compilation of this code for Clang 14 because the invocation of `strerror_r` is invalid. I think you probably know better which one. Let me know if you need to test something.
