### ISSUE TITLE
[Question] prometheus metrics - LTS - different endpoints

### ISSUE THREAD

**Issue by toby181** [fluent/fluent-bit#7881]
Hi guys,

It seems there are 3 different options to expose prometheus metrics. Which one is the way to go and supported on long term?
For me personally /api/v2/metrics/prometheus seems like the way to got since it provides the metrics for pipeline and storage out of the box.

1. /api/**v1**/metrics/prometheus
Docu: https://docs.fluentbit.io/manual/administration/monitoring#rest-api-interface
Config: out of the box
Metrics: pipeline
2. Fluent Bit Metrics plugin
Docu: https://docs.fluentbit.io/manual/pipeline/inputs/fluentbit-metrics
Config: via pipeline
Metrics: pipeline + storage (includes metrics about the plugin itself)
3. /api/**v2**/metrics/prometheus
Docu: No official documentation, just mentioned in a few comments and this code snippet https://github.com/search?q=repo%3Afluent%2Ffluent-bit+%2Fapi%2Fv2%2Fmetrics%2Fprometheus&type=code
Config: out of the box
Metrics: pipeline + storage

Thank you!

**Comment by patrick-stephens** [comment]
I think a few things are being mixed here together.

Prometheus is one metrics format - there are others but it is popular. 

The endpoints you list above are those provided by the webserver. The webserver must be enabled to provide this (not everyone wants that) and the endpoints must be scraped/polled/pulled rather than pushed (e.g. with Prometheus Remote Write). The webserver provides these endpoints rather than a specific output plugin.

Fluent Bit metrics plugin collects metrics for you, it can be connected to metrics outputs (even multiple ones) in whatever format you want. It is an input plugin the same as any other. You can connect it to `prometheus_exporter` or `prometheus_remote_write` for example (or others supporting metrics).
- https://docs.fluentbit.io/manual/pipeline/outputs/prometheus-remote-write
- https://docs.fluentbit.io/manual/pipeline/outputs/prometheus-exporter

Other stuff can also be plumbed into a metrics pipeline using the input plugin to output, e.g. adding labels - this is not possible with the webserver endpoints so would have to be done by the object scraping them.

**Comment by toby181** [comment]
Thanks for the explanation @patrick-stephens , got it.
I forgot that the webserver has to be explicitly enabled, which is done by default when using the HelmChart.

Do you know whether the /api/v2 endpoint, of the webserver, is stable and can be used productively?

**Comment by patrick-stephens** [comment]
> Do you know whether the /api/v2 endpoint, of the webserver, is stable and can be used productively?

@leonardo-albertovich is probably better placed to answer, I think so but it may be improved/extended and eventually there may be a v3 potentially and v1 will be retired too.

It seems from your question though you just want what Fluent Bit metrics provides, i.e. storage + metrics, so why not use that with `prometheus_exporter` output? You can then add more metrics from other inputs and customise things in the future easily. Or does it miss something the v2 endpoint provides? That's probably something that should be fixed then.

Missing docs - please submit a PR to improve them @toby181.
https://github.com/fluent/fluent-bit-docs/blob/master/administration/monitoring.md
