### ISSUE TITLE
fluentbit.io not resolving from Gitlab.com containers

### ISSUE THREAD

**Issue by RonaldDuncan** [fluent/fluent-bit#7921]
## Bug Report

**Describe the bug**
DNS problem resolving fluentbit.io

**To Reproduce**
- try to access from a gitlab container building on gitlab.com
-  curl.exe -L -o C:\Windows\Temp\fluent-bit.zip https://fluentbit.io/releases/1.9/fluent-bit-1.9.9-win64.zip

- Steps to reproduce the problem:

**Expected behavior**
DNS resolves and file downloads

**Screenshots**
Running install for flavour 'aspnet'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0curl: (6) Could not resolve host: fluentbit.io

**Your Environment**

* Windows container build on Gitlab.com

**Additional context**
Can not build containers

**Comment by patrick-stephens** [comment]
It should work but it is not actually the documented location to get releases from: https://docs.fluentbit.io/manual/installation/windows

From memory I think there is a Cloudflare rewrite in there but the target should be `releases.fluentbit.io`: https://releases.fluentbit.io/1.9/fluent-bit-1.9.9-win64.zip

Everything seems to resolve for me and unfortunately I do not have any Gitlab stuff set up to check if it was a failure there.

On a related note we do actually provide Windows containers now as well: https://hub.docker.com/r/fluent/fluent-bit/tags
This is since the 2.0.6 version. 
They do need some love so any improvements would be appreciated: https://github.com/fluent/fluent-bit/blob/master/dockerfiles/Dockerfile.windows

**Comment by patrick-stephens** [comment]
We also have a Checkly test running across multiple regions for fluentbit.io that's not shown any errors for quite a while: https://status.calyptia.com/

We did see a failure at 12:22 yesterday (UTC+1) but that seems to have been transient and certainly nothing was changed to cause or as a result of it.
