### ISSUE TITLE
Input winevtlog errors when channel doesnt exist

### ISSUE THREAD

**Issue by kclinden** [fluent/fluent-bit#8082]
## Bug Report

**Describe the bug**
When using winevtlog input and specifying a channel that doesnt exist, the fluentbit errors with a non-descriptive error of `[lib] backend failed`. Using the same input configuration with winlog does not cause an issue. Troubleshot issue, by reducing number of channels and fluentbit started successfully. Narrowed down list of channels to identify which one was causing the issue (Sysmon) which was not installed on the system.

**To Reproduce**
- Configure fluentbit with winevtlog and a non-existent channel

**Expected behavior**
- Channel would not be found, and process would run without collecting anything from that event channel.

**Screenshots**
none

**Your Environment**
* Version used: 2.1.9
* Configuration: 
   ```
   [Input]
   name winevtlog
   channels: Microsoft-Windows-Sysmon/Operational
   interval_sec: 1
   db winevtlog.db
   ```
* Environment name and version (e.g. Kubernetes? What version?): Windows
* Operating System and version: Windows Server 2019 Datacenter

**Additional context**
Have to remove channel from ansible configuration or only configure if sysmon is installed

**Comment by c0d3fau1t** [comment]
@kclinden I see this is an old issue. The functionality requested exists since version 2.0.3 although it is not documented. You need to add "ignore_missing_channels=true" in winevtlog input for it to work. Parameter value defaults to false.
Refer to this [issue comment](https://github.com/fluent/fluent-bit/pull/6176#issuecomment-1273918496) for an example.
