### ISSUE TITLE
open security vulnerabilities on the latest fluent-bit version

### ISSUE THREAD

**Issue by altafrattani** [fluent/fluent-bit#8117]
There are several vulnerabilities, some over 10 years old, that are still present in the latest version. Do we have an ETA on when will these get resolved?

Here is the list

CVE-2010-0928
CVE-2011-3389
CVE-2013-4392
CVE-2015-3276
CVE-2017-14159
CVE-2017-17740
CVE-2018-20796
CVE-2018-5709
CVE-2018-6829
CVE-2020-13529
CVE-2020-15719
CVE-2021-33560
CVE-2022-1304
CVE-2022-41862
CVE-2022-4899

**Comment by patrick-stephens** [comment]
What OS/target are you looking at and with what tool?

If the CVEs are related to the OS supplied libraries that Fluent Bit depends on so the resolution would need to be provided by those upstream providers (if they deem it necessary to fix). If it is related to the vendored dependencies (see https://github.com/fluent/fluent-bit/tree/master/lib) then these can indeed be controlled by Fluent Bit and ETA will be greatly improved by submitting a PR to contribute the change.

What analysis have you done to confirm these are indeed relevant and impacting Fluent Bit?
I am not trying to shift responsibility but focus the limited time and effort we have for open source maintenance on prioritising the most critical/exploitable CVEs for fix. Any analysis you can share will help speed things up.

I had a look at the first one initially to check and this is marked as won't fix by Red Hat for example (https://nvd.nist.gov/vuln/detail/CVE-2010-0928) plus seems to be referencing OpenSSL 0.9.8 - depending on the target we should be using either OpenSSL 1.x+ or 3.x+ (see https://github.com/fluent/fluent-bit/issues/7644 for work to step up) so it feels like this is a false positive or something dragged in by other dependencies. Again, likely target-specific but it's hard to say without those details.

**Comment by t0klian** [comment]
And CVE-2023-4911 as well. We need to wait for the next release to fix the vulnerabilities since the docker image is distroles and it requires additional effort to perform package upgrade on your own

**Comment by ira-gordin-sap** [comment]
I am not sure which Debian version is used here, because I see several in Dockerfile.
https://security-tracker.debian.org/tracker/CVE-2022-1304 for example is fixed in Debian 12 (bookworm) so I suppose Debian 11 (bullseye) is used here.
When do you plan to move Debian 12? (It will automatically fix CVE-2022-1304 and 14 more CVE's I see in fluent-bit version 2.1.10. Please let me know if it already fixed it in fluent-bit 2.2.0.)

**Comment by patrick-stephens** [comment]
Distroless images are used as the base image for the production image: https://github.com/fluent/fluent-bit/blob/3ce15c6f68d40075acbaabb5941036f278091c4c/dockerfiles/Dockerfile#L155

The system dependencies are pulled at the time of image build (i.e. for the release) so it should pull any fixes from upstream repositories at that point. Each time a release is made it will get a snapshot of the system dependencies at that point - these are outside of Fluent Bit control.

As new CVEs are found and fixed all the time you should be stepping up to the latest release - backporting of fixes is not done for older releases for OSS versions. We do not overwrite images once released. Enterprise providers exist if you need this: https://fluentbit.io/enterprise/

Stepping up to Bookworm should just be a case of updating the Dockerfile (assuming there is a distroless version for it) so please submit a PR as contribution will always help speed it up. We may need to handle any dependency changes (e.g. a package may be renamed or extra packages are required or some can be removed).

We also have nightly builds if you want to verify if something is fixed in the next release: `ghcr.io/fluent/fluent-bit/unstable:master`.

**Comment by patrick-stephens** [comment]
I will again implore folks to look at https://github.com/fluent/fluent-bit/issues/8117#issuecomment-1790395129.

Specifically the analysis aspect and any time you can contribute to help improve the overall product will benefit yourselves and the rest of the community.

**Comment by ira-gordin-sap** [comment]
@patrick-stephens 
Let's analyze the results you got with Grype at this specific point in time.
Let's look on openssl lines: `openssl           1.1.1w-0+deb11u1`.
If we go to https://tracker.debian.org/pkg/openssl, we can see the following:
```
oldstable: [1.1.1w-0+deb11u1](https://packages.debian.org/source/oldstable/openssl)
old-sec: [1.1.1n-0+deb11u5](https://packages.debian.org/source/oldstable-security/openssl)
stable: [3.0.11-1~deb12u2](https://packages.debian.org/source/stable/openssl)
stable-sec: [3.0.11-1~deb12u2](https://packages.debian.org/source/stable-security/openssl)
```
It means that the basic image is oldstable. Why? Can/should it be changed to stable-sec?

**Comment by patrick-stephens** [comment]
Sure, I suspect it is a hangover from the previous OpenSSL 1 usage which is still in place for older targets but there is an [open issue on updating to OpenSSL 3](https://github.com/fluent/fluent-bit/issues/7644) which should be supported now. 

https://github.com/fluent/fluent-bit/blob/3ce15c6f68d40075acbaabb5941036f278091c4c/dockerfiles/Dockerfile#L111

The only problematic area might be transitive dependencies - if any of the other dependencies pull in OpenSSL 1.

So, feel free to submit a PR to update the container image to do so. This will be the quickest way to test and verify it plus get it into a release then.

Similar for any other dependencies there, if you think it needs updating please add it.

**Comment by vasuarv** [comment]
I have been working on this issue as well, and I have a patch for this, which moves the base image to bookworm (debian-12). The also causes an issue with the dependent projects like the grafana-labs fluent-bit plugin, which use this base image as well.

**Comment by patrick-stephens** [comment]
Do you have a PR @vasuarv ?

**Comment by vasuarv** [comment]
I thought I had posted the comment previously. The build from the main branch did not have this issue.

**Comment by patrick-stephens** [comment]
https://github.com/fluent/fluent-bit/pull/8916 should update the base image too

**Comment by nr-rkallempudi** [comment]
<img width="1016" alt="Screenshot 2024-11-15 at 11 22 33 AM" src="https://github.com/user-attachments/assets/d6537bd8-fa60-49bc-8f93-8dd48c97dc0c">

Critical  CVE-2023-45853  is coming from upstream, How do we assess the criticality of this vulnerability in Fluent Bit context?
