### ISSUE TITLE
read error, check permissions & error scanning path

### ISSUE THREAD

**Issue by Roshan2346** [fluent/fluent-bit#8369]
## Bug Report

**Describe the bug**
We have noticed below error and warning logs,
These error messages will come when config path set is not having any logs inside the defined path. 

**To Reproduce**
- Rubular link if applicable:
- We can use the path with asterisk (*) mark, whenever we are using the * mark and if there are no logs inside that path, then we are observing this issue. Custom log path: ```logpath ---->/logs/abc/*.json```
- Example log message if applicable:
```
[input:tail:file0]read error, check permissions: /logs/abc/*.json;
[input:tail:file0]read error, check permissions: /logs/abc/*.json;
```
- Steps to reproduce the problem:
- We can use the path with asterisk (*) mark, whenever we are using the * mark and if there are no logs inside that path, then we are observing this issue. Custom log path: ```logpath ---->/logs/abc/*.json```

**Expected behavior**
Fluent bit should not throw error, because if we try using /logs/abc/.json, and if there are no logs inside the path, then we don't get any error. So, using * should also not throw any errors. Instead, whenever we use **/logs/abc/*.json**, then it should show all the files ending with **.json**, else nothing(no error messages), if there are no logs inside that path.

**Screenshots**

**Your Environment**

* Version used: **fluent-bit-version: 2.1.10**
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by ekxxsho** [comment]
Hi, adding to this discussion, we have communicated the team via Slack and please find the discussion below,

Shobana
Hello, In fluentbit we use tail input plugin and we configure the file path for harvesting, but there are few usecases, where the input log folder will not be available as soon as Fluentbit getting started. So we have configured, with /foldername/*. But we get below issue,
[input:tail:file0]read error, check permissions: /logs/abc/*.json;
[input:tail:file0]read error, check permissions: /logs/abc/*.json;
But also if we specify the absolute path even the folder and file not exist, fluentbit is not printing this error, which is very strange. Since the behavior is different for both the usecases.
This error logs are very repetitive; how can this be fixed? Also we wanted to understand why this behavior is happening. 


Braydon Kains
Does the user running Fluent Bit have read access to the directory you're trying to read from? If it's something at / you probably need to either run Fluent Bit as root or give the user running Fluent Bit proper read access to the folder.


Shobana
No, the folder itself not available for sometime, Say for example,
If I configure, /logs/test.log - > Even the logs directory is not present, Fluentbit will not throw this read error,
But if I configure, /logs/*.log, then read error comes, if folder not present.
This is our query, why such change in behavior?


Braydon Kains

Ah I think I understand your question now. This is because of the underlying glob.h behaviour.
Given a specific path to a direct file that doesn't exist (whether the directory it's in exists or not), glob will return GLOB_NOMATCH. When Fluent Bit encounters this error, it will try to stat the file, and if it doesn't exist it will produce a debug log, but otherwise be silent.
Given a path with a wildcard in it that is in a directory which doesn't exist, glob will return GLOB_ABORTED. This is probably because it can't actually run a wildcard search in a directory that doesn't exist.
You can see that code in the in_tail glob scanning backend: https://github.com/fluent/fluent-bit/blob/40bb0fbe17efa6b4b1a96940e9ff7374b1a0c3eb/plugins/in_tail/tail_scan_glob.c#L187



Braydon Kains
Arguably read error, check permissions is a misleading error message given this other possible scenario for a GLOB_ABORTED. It could be worth opening a GitHub Issue to bring that up.

**Comment by basudevk** [comment]
Does fluent-bit tail input plugin automatically start reading from files when the directory gets created later along with files in it?

**Comment by basudevk** [comment]
I am unable to read from custom folders provided to "Path" options of the "Tail" input plugin. Do I need to do any extra configuration for it? I keep getting this error - [input:tail:tail.0] read error, check permissions: /var/log/jenkins_log/*.log

**Comment by Ants5** [comment]
I would like to ask if this problem has been solved. I have also encountered such a problem. When the configuration path is /var/log/app/*/trace.log with an * in the middle, this error will appear:

```
[error] [input:tail:tail.0] read error, check permissions: /var/log/app/*/trace.log
[warn] [input:tail:tail.0] error scanning path: /var/log/app/*/trace.log
```
