### ISSUE TITLE
[out_stackdriver] Support different options to extract project_id label

### ISSUE THREAD

**Issue by JeffLuoo** [fluent/fluent-bit#8387]
**Is your feature request related to a problem? Please describe.**

Many users might use credentials from different project for cloud logging, this will cause unmatched `project_id` when users view logs from the GCP UI.

**Describe the solution you'd like**
Option 1: Add a different field called `displayed_project_id` to overwrite the label of `project_id`.

Option 2: Reuse existing `export_to_project_id` to overwrite the `project_id` fetched from the credential file.
 
**Describe alternatives you've considered**

**Additional context**

**Comment by JeffLuoo** [comment]
cc: @braydonk

**Comment by braydonk** [comment]
It appears that just setting `project_id` manually in the config will do what you need. I don't think there's need for `displayed_project_id` since it would be functionally the same as `project_id` being set manually.

**Comment by JeffLuoo** [comment]
Hi @braydonk `project_id` doesn't seem to be a configurable option.

**Comment by JeffLuoo** [comment]
The principle is that the `project_id` in the resource type should always match the project the workload is created under, rather than the destination project the logs will be sent to.

**Comment by braydonk** [comment]
I misspoke, I meant `export_to_project_id`. This is not overwritten by the project from the credentials, so if a user sets this then the problem mentioned in the first comment shouldn't occur; if they use credentials from a different project, the project specified in `export_to_project_id` will take precedence for sending the logs.
https://github.com/fluent/fluent-bit/blob/master/plugins/out_stackdriver/stackdriver.c#L1307
The problem with the project ID not matching in resources is different. The resource label extraction code incorrectly assumes that the project ID from the credentials file will be what's used in the resource labels. Perhaps we could add a field `source_project_id` that will:
* Always be used in resources
* Be set to `export_to_project_id` if not explicitly specified
* `project_id` extracted from credentials remains the fallback to `export_to_project_id` and thus also the fallback from `source_project_id`
(`source_project_id` name might be debatable, but I suggest this because I think of it as "where the logs are coming from" which maps nicely to it being used in resource labels)
