### ISSUE TITLE
Package repos install service with fluent-bit.conf path

### ISSUE THREAD

**Issue by Saya47** [fluent/fluent-bit#8500]
When we use package repos to install Fluent-bit, the installed service uses path `fluent-bit.conf` (classic config) by default, since we are on v2 when can we expect for `.yaml` path to be used instead by default? Because I have to change the path every time I update Fluent-bit!

**Comment by fulldeck** [comment]
echo this, I am moving to 3.x and the container still uses the .conf.

/fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf

**Comment by dorianm** [comment]
Hello, this issue is close because of staled, but a new install of Fluent-Bit v4.0.3 on Ubuntu 24.04 still uses `.conf` configuration as default (in the `/etc/fluent-bit/`, referenced in the systemd unit).

The `conf` format will be deprecated at the end of the year according the documentation, do you plan to change this behavior?

*Edit*: The PR https://github.com/fluent/fluent-bit/pull/9837 is open since the begin of the year. I'm going to check conversation over there.
