### ISSUE TITLE
Release 2.2.3 link is broken https://fluentbit.io/announcements/v2.2.3/

### ISSUE THREAD

**Issue by nikhil-bhat** [fluent/fluent-bit#8879]
## Bug Report

**Describe the bug**
[Release 2.2.3 link](https://fluentbit.io/announcements/v2.2.3/) is broken .
According to the [blog post ](https://fluentbit.io/blog/2024/05/21/statement-on-cve-2024-4323-and-its-fix/) Release 2.2.3 contains the backported fix for the CVE-2024-4323 

**To Reproduce**
- Navigate to release llink for 2.2.3 it points to non existent page.
-  Also this version is not listed [at](https://docs.fluentbit.io/manual/installation/docker)

**Comment by patrick-stephens** [comment]
The announcement post usually comes up a little delayed so I'll ping @edsiper on that. 

This is a CVE fix release so the priority was to get that out 

The docs PR will be for the 2.2 series branch but there are some other changes from the auto PR so that needs looking at https://github.com/fluent/fluent-bit-docs/pull/1375
The docs link you have is for the main release so we could push there as well but it's getting a bit messy so I think better to keep the 2.2 series docs only up to date

**Comment by lecaros** [comment]
Release notes were published. Thanks @nikhil-bhat for reporting this.
