### ISSUE TITLE
Excessive memory usage on kubernetes

### ISSUE THREAD

**Issue by tomstreet** [fluent/fluent-bit#894]
Running on Azure Kubernetes Service (kubernetes v1.11.3) as a daemon set using the fluent/fluent-bit:0.14.6 image. The nodes are quite small with each one running roughly 15 containers that are sending JSON logs over tcp. The pod memory limit is currently set to 200Mi and fluent-bit keeps hitting this and restarting. Any suggestions? Here is the config:

```
[SERVICE]
    Flush         5
    Log_Level     info
    Daemon        off
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

[INPUT]
    Name      tcp
    Listen    0.0.0.0
    Port      5170

[OUTPUT]
    Name      null
    Match     *
```

parsers.conf:
```
[PARSER]
    Name   json
    Format json
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z
```

**Comment by tomstreet** [comment]
Is this even excessive memory usage? Are there any recommendations for what the resource limits/requests should be?

**Comment by edsiper** [comment]
If all Pods send around 200MB of data within 5 seconds, yeah, it will be killed.

While Fluent Bit receives data, it will not deliver the logs until the Flush time expiration, my suggestion is to set Flush to 1 (one second) and append a Mem_Buf_Limit option into the TCP input plugin just for protection, you can read more about memory handling here:

https://docs.fluentbit.io/manual/configuration/backpressure

**Comment by tomstreet** [comment]
@edsiper It takes about 10-15 minutes for the fluentbit pod to be killed - it just has a nice straight memory graph that looks like it never cleans up any memory:
![image](https://user-images.githubusercontent.com/722381/49287535-c2c82080-f495-11e8-8832-48a39828e749.png)
The drop in memory usage is when the pod gets killed:
![image](https://user-images.githubusercontent.com/722381/49287672-484bd080-f496-11e8-8677-4794a0481334.png)

I have tried various settings for the Mem_Buf_Limit but none of them make any difference.

**Comment by edsiper** [comment]
Did u try Flush 1?

**Comment by tomstreet** [comment]
Yeh - those graphs are with it set to Flush 1

**Comment by edsiper** [comment]
@tomstreet I am curious to learn more about the issue. My expectation is that Fluent Bit will protect it self from that scenario. Would you please share some steps to reproduce the problem ?

**Comment by HarishHothi** [comment]
Similar problem,
Observing very high memory usage on fluentbit pod. We observed around 10GB of memory usage. We have not specified resource limit on pod for the testing.
```
kubectl top po -n logging fluent-bit-gmnrt 
NAME               CPU(cores)   MEMORY(bytes) 
fluent-bit-gmnrt    46m             9861Mi 
``` 
When elastic search is heavily loaded it will give HTTP 429 Error to fluent bit. And fluent bit will keep unsent logs in its main memory for retry. Fluent bit is retrying for X number of times (as configured in output plugin's `Retry_Limit` setting). [Retry_Limit](https://fluentbit.io/documentation/current/installation/kubernetes.html). After X number of retries it should discard the message. Over here I am not sure it is discarding or keeping in its memory.
`Mem_Buf_Limit` is also set to 5MB but still 10GB is used by fluent bit.

**To Reproduce**
Start application and fluentbit when elastic search is heavily loaded.

**Expected behavior**
Once retry limit is reached fluentbit should not keep the record in its memory. 


**Your Environment**
Kubernetes version is **v1.12.2**
Fluent bit version **0.14.7**
Snippet of fluentbit Configuration
```
    [INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    Parser            docker
    DB                /var/log/flb_kube.db
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Refresh_Interval  10
    ignore_older        1d
 
   [OUTPUT]
    Name            es
    Match           *
    Host            ${FLUENT_ELASTICSEARCH_HOST}
    Port            ${FLUENT_ELASTICSEARCH_PORT}
    Logstash_Format On
    Retry_Limit     2
    Buffer_Size     False

    [FILTER]
     Name record_modifier
     Match *
     Remove_key time

    [FILTER]
        Name            grep
        Match           *
        Regex           log [a-zA-Z1-9]*SOME_STRING[a-zA-Z1-9]*
```

**Comment by mcauto** [comment]
This issue does not appear to have been resolved.
