### ISSUE TITLE
Duplication of sent data

### ISSUE THREAD

**Issue by MarloGrayhat** [fluent/fluent-bit#8955]
I am facing this problem: fluent bit sends already sent data. Suppose there are 4 lines in log file, fluetnt bit sends them successfully, then 2 more lines are added to the file and fluetn bit sends 6 lines. Thus, I get 10 lines in the database instead of 6.

This problem can be solved at the database level, but I don't think this is a good solution to the problem. Maybe there is some flag to solve my problem.

At the moment I am just trying your tool and here is the conf file I have at the moment (without `FILTER` and `OUTPUT`)

```
[SERVICE].
    Flush 1
    Daemon Off
    Log_Level debug
    Parsers_File parsers.conf
[INPUT]
    name tail
    path /var/log/*.log
    Offset_Key offset
    log tag
    Parser json
```

**Comment by patrick-stephens** [comment]
Please follow the issue template - what OS and versions are you using?

Tail should function like `tail -f` so will only read new lines added to the file since Fluent Bit started. 

You are not reading from head or using a database to persist state for tail so it should only read the new lines if the file is appended which is confusing. Is this on a platform or a framework that rewrites the whole file?

**Comment by MarloGrayhat** [comment]
Thanks for the tips! When running `tail -f` I was getting the error `tail: logfile.log: file truncated` which is why I was getting duplicates

**Comment by tth-trang** [comment]
Is there any way to prevent the data from being duplicated by config fluent-bit ?
