### ISSUE TITLE
Collecting Traces from Container stdout and Sending to Jaeger

### ISSUE THREAD

**Issue by muhmedabdelhalim** [fluent/fluent-bit#9040]
Hello team,

I am exploring ways to enhance observability within my containerized environments and have a specific requirement. I am looking to collect trace data directly from the standard output (stdout) of containers and send this data to Jaeger for visualization and analysis.

Is there an existing feature in fluent-bit that supports this kind of data capture from stdout?
If not, could this be considered for a new feature?
What would be the recommended approach to implement this functionality if it doesn’t currently exist?

**Comment by patrick-stephens** [comment]
Does Jaegar support OTEL? If so you can send via the OTEL output to it, or maybe the HTTP one if not.
https://docs.fluentbit.io/manual/pipeline/outputs/opentelemetry

For capturing from stdout, typically that goes to the kubelet log files and then is consumed that way like any other log file Fluent Bit would consume. Typically though these would be treated as log types rather than trace types I think though.
There is also an OTEL input for this if you wanted to send direct that way: https://docs.fluentbit.io/manual/pipeline/inputs/opentelemetry
