### ISSUE TITLE
output loki remove_keys in nest key  not work properly

### ISSUE THREAD

**Issue by owanio1992** [fluent/fluent-bit#9091]
## Bug Report
can't not set multiple remove_keys in a nest key

**Describe the bug**
sample data
```
   {
      "time""=>""2024-07-16T03:25:43.552908882Z",
      "stream""=>""stderr",
      "_p""=>""F",
      "log""=>""2024-07-16 03:25:43,552 INFO     werkzeug 10.42.3.1 - - [16/Jul/2024 03:25:43] "GET / HTTP/1.1" 200 -",
      "kubernetes""=>"{
         "pod_name""=>""data-coll-nbl-exporter-5c89f6c5f9-mfqb5",
         "namespace_name""=>""devconn",
         "pod_id""=>""7b3883ec-c05a-49b3-b506-a10d21092151",
         "labels""=>"{
            "app.kubernetes.io/instance""=>""data-coll",
            "app.kubernetes.io/managed-by""=>""Helm",
            "app.kubernetes.io/name""=>""nbl-exporter",
            "app.kubernetes.io/version""=>""main",
            "date""=>""1721099472",
            "helm.sh/chart""=>""nbl-exporter-0.1.0",
            "pod-template-hash""=>""5c89f6c5f9"
         },
         "annotations""=>"{
            "prometheus.io.scheme""=>""http",
            "prometheus.io/path""=>""/metric_redis_llen",
            "prometheus.io/port""=>""50000",
            "prometheus.io/scrape""=>""true"
         },

   }
``` 

case1 , it's can work
```
remove_keys kubernetes['namespace_name']
```

case2 , it's can work
```
remove_keys kubernetes['pod_id']
```

case3 , only pod_id remove 
```
remove_keys kubernetes['namespace_name'],kubernetes['pod_id']
```

case4 , only namespace_name remove 
```
remove_keys kubernetes['pod_id'],kubernetes['namespace_name']
```

**Expected behavior**
all specific key will be remove

**Your Environment**

* Version used: 3.1.2
* Environment name and version : Kubernetes 1.29
* Filters and plugins: 
fliter: kubernetes

**Comment by fivetran-aleksandarkostic** [comment]
I am facing the same issue, keys referenced as either labels or structured_metadata are not being removed from kubernetes map automatically, and it is also impossible to remove them manually as shown in this issue. 
I believe that the underlying issue is sorting as described in this comment: https://github.com/fluent/fluent-bit/issues/5546#issuecomment-1159669541 as I was able to get different keys like `namespace_name` or `container_name` to be removed automatically when changing the ordering in `label-map.json`, but not all of them.
