### ISSUE TITLE
Parsing the Same Log in Different Ways

### ISSUE THREAD

**Issue by skreddykoppula** [fluent/fluent-bit#9179]
Hi
Can I parse the same log in different ways, such as using one method to take the entire log and another method to split it based on regex patterns?
Note: My output destination is same

**Comment by patrick-stephens** [comment]
Do you mean two different parsers for the same log?
If so, yes although you would have to use the parser filter rather than configuring it in `tail` directly.

You can also use the `parser` filter to apply further parsers on top of existing records to extract new keys and you can keep the original record as well.

It's not exactly clear what you're after but I think the answer is yes. It may help to provide example input and output you want.

However I'll also say this is not a bug or feature request so may be better to discuss in Slack.

**Comment by skreddykoppula** [comment]
[INPUT]
          Name              tail
          Tag               kube.*
          Path              /var/log/containers/*.log, /var/log/nginx/access.log, /var/log/nginx/error.log
          Parser            cri
          DB                /var/log/flb_kube.db
          Mem_Buf_Limit     5MB
          Skip_Long_Lines   off
          Refresh_Interval  20
          Buffer_Chunk_Size 1M
          Buffer_Max_Size   1M
          Ignore_Older      1D
          Rotate_Wait       60

[PARSER]
         Name cri
         Format regex
         Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<user>[^ ]*) - - \[(?<requestTime>[^\]]+)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<statuscode>[^ ]*) (?<timeInms    >[^ ]*) ms (?<contentLength>[^ ]*) (?<businessHeader>[^"]+) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)"$
         Time_Key    time
         Time_Format %Y-%m-%dT%H:%M:%S.%L%z
         
         
   I used this code to parse my Kubernetes logs what I need is I also want to store entire log as 1 field
   
   I never find any documentation to do that

**Comment by patrick-stephens** [comment]
So don't parse it in tail and you'll get it all in one key.
Then you can use the `parser` filter to apply a parser on top to make another set of keys.

However, you're also using a custom CRI parser which is not recommended - it does not cope with various edge cases or multiline split by the kubelet.

**Comment by patrick-stephens** [comment]
You can also have a separate LUA filter after parsing that combines what you want into a new field too.
