### ISSUE TITLE
Microsoft recommendations to improve security and resilience in the fluent-bit service

### ISSUE THREAD

**Issue by sairinraychoudhury** [fluent/fluent-bit#9402]
Hi Everyone,

Needed advice from community members. We have deployed fluentbit 1.9.5 using helm in Microsoft Azure Kubernetes Service (AKS). Also during an assessment of our platform towards improved security & resilience angle received below recommendations from Microsoft experts to be implemented.

1. Usage of pod HostPath volume mounts should be restricted to a known list to restrict node access from compromised containers
2. The root access inside the service container should be avoided.

We are not sure if above actions when implemented will have an impact on fluentbit since we used default fluentbit configs which are in helm chart for fluentbit.

Could anyone from the community please help or guide us  on below queries?
1. Have you tried implementing custom configs apart from default configs provided?
2. Do you have a view of the impact by any means if we go ahead and implement this?
3. Are there any other general recommendation towards achieving this?

**Comment by patrick-stephens** [comment]
1.9.5 is very old and no longer supported by OSS so that would also be a security and resilience recommendation to upgrade.

It's not clear exactly what you're deploying on or how.
The only recommended way to function on K8S is with the official helm chart: https://docs.fluentbit.io/manual/installation/kubernetes#installing-with-helm-chart
Are you using this? What platform are your nodes? Linux or Windows?

> Usage of pod HostPath volume mounts should be restricted to a known list to restrict node access from compromised containers

If so then I think you will have to justify `hostPath` mounts explicitly as the use case is to mount the container logs from the host into the container so they can be read. Otherwise how would it ever be able to see them? You could also deploy agents to the actual node that read the logs directly natively without using K8S daemonsets.

If you do not care about container logs then yes, do not mount them.

> The root access inside the service container should be avoided.

Modify your security context to not run as root then but ensure your log files are mounted with appropriate configuration to allow the container user to read them.

> Have you tried implementing custom configs apart from default configs provided?

Not sure the question here, yes of course other configurations can be used. A lot of users do not use Elasticsearch for example as an output.

This feels more like a question for enterprise support so I'd reach out to providers there: https://docs.fluentbit.io/manual/installation/getting-started-with-fluent-bit#enterprise-packages

I'm going to close as I think I covered the questions but feel free to reply.
